ZON-6068 header color using master/slave widget
ZeitOnline/vivi pull request #133
Opened 2020-08-19 16:30 UTC by tomster

Abseits jeglicher rassistischen Sprachgewohnheiten implementiert dieser PR nun das gewuenschte dritte Dropdown mit Farbwerten fuer vollbreite Header visueller Artikel in Form einer verschachtelten Hierarchie von master/slave widgets.

TTW funktioniert es nun inswoweit, dass man die Werte in Abhaengigkeite der Header korrekt auswaehlen kann.

Was noch fehlt ist, dass das Farbendropdown auch wieder verschwindet, wenn man ein Template auswaehlt, das weder Header noch Farben unterstuetzt (bspw. "Kolumne").

Dieser PR ersetzt #131

2020-08-19 16:32 UTC, tomster commented
Beispielhaft noch ein XML snippet, fuer ``article-templates.xml`` mit dem die o.g. Dropdowns befuellt werden:

```  <template name="visual-article">
    <title>Visual Article</title>
    <header name="embed" allow_header_module="true">
      <title>Header-Modul oben</title>
    </header>
    <header name="fullwidth-classic">
      <title>Vollbreit, classic</title>
    </header>
    <header name="fullwidth-split">
      <title>Vollbreit, split (also, geteilt, ja?)</title>
      <color name="#eeeefa">
        <title>Steingrau frisch</title>
      </color>
      <color name="#ccccca">
        <title>Mausgrau</title>
      </color>
      <color name="#085066">
        <title>Kornblau</title>
      </color>
    </header>
    <header name="fullwidth-alternative">
      <title>Vollbreit, alternative</title>
      <color name="#eeeef0">
        <title>Silbergrau 1</title>
      </color>
      <color name="#cccccf">
        <title>Silbergrau 2</title>
      </color>
      <color name="#085064">
        <title>Ozeanblau 4</title>
      </color>
    </header>
  </template>
```

2020-08-25 06:52 UTC, wosc approved these changes
So weit, so straightforward. :) Die vorhandene Mechanik scheint ja _einigermaßen_ zu passen.

Das Feature "Farb-Dropdown ausblenden, wenn das Template (nicht Header) geändert wird" ist allerdings natürlich bisher nicht vorgesehen; die ganze Mechanik ist auf 2 Stufen ausgelegt, nicht auf 3. Der change-Event vom Master kümmert sich daher um seinen Slave, aber nicht um potenziell den Slave-des-Slaves. Ich würde glaub im ersten Schritt das [MasterSlaveDropdown](https://github.com/zeitonline/vivi/blob/master/core/src/zeit/cms/content/browser/resources/dropdown.js#L26) beerben und das `update()` um die 3. Stufe erweitern. Und wenn das tut, kann man schauen, ob man das verallgemeinert in die Basisklasse wieder reinfalten kann, oder ob das mehr verwirrt als nützt.

2020-09-01 13:16 UTC, tomster commented
Aaaalso, nachdem ich den aktuellen master in den feature branch gemerged und lokal neu batoued habe funktioniert der letzte commit jetzt zumindest lokal bei mir wie gewuenscht. ich wuerde vorschlagen, wir schicken das alsbald auf staging, damit es ausfuehrlicher getestet werden kann. (das article-templates.xml ist dort bereits vorbereitet)

2020-09-02 08:39 UTC, wosc requested changes

2020-09-02 08:39 UTC, wosc commented on core/src/zeit/cms/content/browser/resources/dropdown.js
> +    construct: function(grandparent, parent, child, update_url) {
Wie gesagt: `gocept.Class` unterstützt nen `super`-Call. Musste nicht alles copy&pasten.

2020-09-02 08:39 UTC, wosc commented on core/src/zeit/cms/content/browser/resources/dropdown.js
> +        d.addCallback(function(result) {
Right, damit das hier mit `super` hinhaut muss man vmtl in der Superklasse eine `do_update` o.ä. Methode extrahieren, die als xhr-Callback verwendet wird, und die man in der Subklasse dann erweitern kann.

2020-09-02 08:39 UTC, wosc commented on core/src/zeit/cms/content/browser/resources/dropdown.js
> +zeit.cms.configure_multigeneration = function(prefix, grandparent, parent, child, update_url) {
Also das riecht doch sehr danach, als müsste sich das irgendwie abstrahieren lassen, sodass man 2-stufig und 3-stufig mit _einem_ Aufwasch erledigen kann. Aber ausm Hut seh ichs noch nicht wie, leider.

2020-09-02 09:23 UTC, tomster commented on core/src/zeit/cms/content/browser/resources/dropdown.js
> +        d.addCallback(function(result) {
oder das vielleicht als anlass zu nehmen, doch einfach copy&paste zu belassen? (nur halb ketzerisch gefragt)

2020-09-02 09:25 UTC, tomster commented on core/src/zeit/cms/content/browser/resources/dropdown.js
> +zeit.cms.configure_multigeneration = function(prefix, grandparent, parent, child, update_url) {
hatte ich auch ueberlegt, aber allein schon das umbenennen master-> grandparent etc. wuerde schon echt viele auswirkungen haben, wenn ich das richtig sehe. meinst du wir sollten im ersten wurf eine mischform (master -> slave -> child)?

2020-09-02 09:26 UTC, thomasbaumann commented
Ich fühle mich nicht berufen zu sagen, ob das gutes Javascript ist oder so (aber da gibt's ja noch Change Requests von @wosc), aber ich konnte rausfinden, dass diese Datei (e6d9b0f5451d32d54303ea3636583694a97549d8) noch fehlte und dass mit ihr offenbar alles tut (also auch im Vivi-UI) und der Test läuft. 

Also an mir scheitert ein Merge nicht :)

2020-09-02 09:30 UTC, tomster commented
scheint ein wackler zu sein (`requests.exceptions.Timeout: Request attempt timed out after 2.0 seconds`)

2020-09-02 09:31 UTC, tomster commented
run jenkins

2020-09-08 16:00 UTC, tomster commented on core/src/zeit/cms/content/browser/resources/dropdown.js
> +        d.addCallback(function(result) {
also fuer das erben habe ich eine Praezedenz gefunden (in `editor.js`: `zeit.content.article.AppendParagraph = zeit.edit.LoadAndReload.extend({` und das konnte ich umsetzen, allerdings wird in keinem `.js` irgendwo `super()` aufgerufen. Vielleicht kann jemand mit JS foo auf den Code gucken (@mstoltenburg ?)

2020-09-08 16:21 UTC, mstoltenburg commented on core/src/zeit/cms/content/browser/resources/dropdown.js
> +        d.addCallback(function(result) {
Wenn JS foo im MochiKit Dschungel nur wirklich helfen würde …

2020-09-15 09:40 UTC, tomster commented
run jenkins

2020-09-16 15:26 UTC, tomster commented
Ich habe die Aenderung bzgl, der Vererbung wieder rueckgaengig gemacht, da beim Aufruf von .update aus der parent klasse nicht die der abgeleiteten aufgerufen wurde, sondern ein `undefined` an den mochikit event subscriber durchgeleitet hat, der dann das laden des editors mit `src is undefined` blockierte.
ich habe auch mit input von wolfgang keine funktionierende moeglichkeit hinbekommen muss aber auch dazu sagen, dass JS absolut nicht mein forte ist.

IOW ich gebe hiermit offiziell an dieser stelle auf. mit dem revert sollte es aber wenigstens im editor soweit funktionieren.

@TStrothjohann um es testen zu koennen muss der branch noch gemerged und ein staging deployment gemacht werden, was ich aber nicht tun will, solange dieser branch nicht abgenommen ist.

vielleicht will @wosc entweder zaehneknirschend mergen oder einen serviervorschlag machen?

2020-09-21 17:07 UTC, wosc commented
@tomster Ich hab im Zug mal 9237501 gemacht, das war IMHO genau genau der Vererbugns-Ansatz, den ich Dir per DM vorgeschlagen hatte -- hat für mich 1a funktioniert, k.a. was bei Dir da los war?!??

Und nachdem mir dann dadurch klar wurde, was der eigentliche Witz ist, sieht es für mich eigtl so aus als könnten wir mit einem optionalen `grandchild` davonkommen, gar keine Vererbung nötig, siehe 5479dd

2020-09-28 13:19 UTC, tomster commented
run jenkins

2020-09-28 13:25 UTC, merged