ZON-6162: Update jinja to 2.11.2
ZeitOnline/vivi pull request #150
Opened 2020-11-06 08:39 UTC by AWieczorreck

2020-11-09 08:26 UTC, wosc requested changes

2020-11-09 08:26 UTC, wosc commented on core/src/zeit/content/text/jinja.py
> +            # XXX: Will this be used in some points?
Ja, das soll verwendet werden! :) Leider gab es für das bisherige gewünschte Verhalten keinen Test: "Wenn ein Fehler auftritt, soll statt dem gerenderten Template-Ergebnis der Stacktrace als String angezeigt werden". Die Idee dahinter ist, dass vivi-Benutzer wie Thomas Strothjohann die Möglichkeit haben, Fehler in ihren Templates zu finden+beheben, ohne dass sie erst umständlich im Server-Log rumwühlen müssen, auf das sie eher eh keinen Zugriff haben. Das wird z.B. [hier](https://github.com/zeitonline/vivi/blob/master/core/src/zeit/push/browser/mobile.py#L42) verwendet. Wobei ich nicht sicher bin (weil Test fehlt), ob/wie das bisher überhaupt funktioniert hat -- es könnte sogar sein, dass das `render()` den Fehler trotzdem geraised hat (obwohl da bisher `return handle_exception` stand), und das schlicht von dem View geeignet behandelt wurde.

2020-11-19 12:52 UTC, AWieczorreck commented on core/src/zeit/content/text/jinja.py
> +            # XXX: Will this be used in some points?
Ein fehlerhaftes Template (TemplateSyntaxError) wird nicht in der `render()` geprüft/geworfen sondern schon vorher:
https://github.com/ZeitOnline/vivi/blob/cd8d8fd12e390cd9366696c554bc7a87e47a71a1/core/src/zeit/content/text/jinja.py#L21L23
Ich wüsste jetzt nicht, was für einen Fehler in der `render()`-Funktion geworfen werden könnte.

Man könnte wohl eher sowas hier machen:
```python
    def __call__(self, variables, **kw):
        try:
            template = Template(self.text, **kw)
            return template.render(variables)
        except Exception:
            return jinja2.debug.rewrite_traceback_stack()
```
Es macht aber (so wie das jetzt ist) mehr Sinn den Fehler in `validate_template()` zu "behandeln"
https://github.com/ZeitOnline/vivi/blob/cd8d8fd12e390cd9366696c554bc7a87e47a71a1/core/src/zeit/push/urbanairship.py#L146L150
und damit in der `error()` in `PreviewPayload`, den Traceback formatieren und zurückgeben.

Die `handle_exception` in Jinja 2.10.x hat nie einen _gerendertes Traceback_ zurückgegeben.
Bei `self.environment.handle_exception(exc_info, True)` wurde das _True_ wurde nie verarbeitet.
https://github.com/pallets/jinja/blob/2.10.x/jinja2/environment.py#L777 _exception_formatter_ ist immer _None_

Sind Tests nicht nur manuell sinnvoll über @@payload-template?

2020-11-27 08:33 UTC, wosc commented on core/src/zeit/content/text/jinja.py
> +            # XXX: Will this be used in some points?
Aaalso. :)

1. Tests: Da die hauptsächliche/einzige Verwendungsstelle dieser `@@payload-template` View ist, wird man denke ich Tests eben damit schreiben müssen. (Die Alternative wäre, die Fehlerverschluckung woanders hin zu verschieben, aber das wollen wir nicht: Wenn so ein UA-Template einen Syntaxfehler hat, muss der Push abgebrochen werden, und nicht mit einem halbgewalkten JSON abgeschickt werden. Da ist Exception genau richtig denke ich.)
2. Es gibt zwei mögliche Sorten von Fehlern, wenn ich das richtig sehe: a) Lade- und Syntaxfehler (z.B. `{% forrrr`), die werden im `Template.__init__` geworfen und b) Laufzeitfehler (z.B. `{{foo.bar.baz}}`), die werden im `render()` geworfen. Und das ganze Thema `rewrite_traceback` bezieht sich nur auf (b). Aber abfangen/anzeigen wollen wir (fürs vivi-UI) natürlich beide.

2020-12-01 08:13 UTC, AWieczorreck commented
run jenkins

2020-12-04 13:53 UTC, wosc commented
wird ersetzt durch #160 

Nochmal sorry, dass ich dich da mit in die Verwirrung gezogen hab; das ganze Thema Fehlerbehandlung ist nur in zeit.web relevant, hier überhaupt nicht.

2020-12-04 13:53 UTC, closed without merging