STO-185: Cache content & DAV properties based on file modification times
ZeitOnline/vivi pull request #183
Opened 2021-02-16 15:45 UTC by witsch

Siehe [STO-185](https://zeit-online.atlassian.net/browse/STO-185).

2021-02-24 07:22 UTC, witsch commented
run jenkins

2021-02-24 15:42 UTC, witsch commented on core/src/zeit/cms/content/tests/test_filesystem_caching.py
> +        self.path.joinpath('testcontent').touch()
Eventuell sollten wir uns hier noch die originale `mtime` merken und wieder setzen, also quasi hinter uns aufzuräumen…

2021-03-22 12:11 UTC, wosc requested changes
Sehr cool! Ich hab ein paar Detailanmerkungen. :)

2021-03-22 12:11 UTC, wosc commented on core/src/zeit/cms/content/caching.py
> +        if size is not None and type(connector) is Connector:
Hrm ich würd das glaub lieber mit nem expliziten Attribut (oder gar Interface) machen (`connector.supports_mtime_cache` o.ä.) anstatt das an der einen konkreten Klasse aufzuhängen.

2021-03-23 14:26 UTC, witsch commented on core/src/zeit/cms/content/caching.py
> +    def path(self, unique_id):
Das hatte ich zwischenzeitlich mal ausprobiert, aber wieder verworfen. Allerdings weiß ich schon wieder nicht mehr, warum das nicht so schön war…

2021-03-23 14:36 UTC, witsch commented on core/src/zeit/cms/content/caching.py
> +    def cleanup(self):
Mit dem `dict` versteh ich grade nicht, wie du's meinst, aber `cleanup()` wird nur einmal in [`get()`](https://github.com/ZeitOnline/vivi/pull/183/files#diff-68619c03f1b785abafe27d6a96dc63942b49a2c32587ab89cc47b7da53de53d7R67) aufgerufen und ist lediglich als eigene Methode geschrieben, weil mir das `get()` sonst zu lang geworden war.

Und `usage()` ist ein helper für `info()`, was wiederum nur zu dem debug view in Friedbert gehört. Da find ich's okay, wenn das bei einer 'preview' Instanz nicht geht.

2021-03-23 14:41 UTC, witsch commented on core/src/zeit/cms/content/caching.py
> +    def path(self, unique_id):
Es gibt schon ein Methode auf dem connector, die die `mtime` zurückgibt, aber als string. Zuerst hatte ich da einen `raw=False` Parameter eingebaut, aber letztlich erschien mir das dann zu umständlich und (später) viel schwieriger nachvollziehbar als dass es die paar Zeilen "duplizierten" Code rechtfertigen würde. Vor allem, nachdem `_path` noch zusätzliche Sachen macht, die wir hier gar nicht brauchen, aber dann bei jedem lookup mit ausgeführt werden.

2021-03-23 14:41 UTC, witsch commented on core/src/zeit/cms/content/caching.py
> +        filename = join(self.connector.repository_path, path)
Siehe https://github.com/ZeitOnline/vivi/pull/183#discussion_r599632638… 🙂

2021-03-26 00:22 UTC, witsch commented on core/src/zeit/cms/content/dav.py
> +        if properties is None and hasattr(instance, 'uniqueId'):
Mit 08eb705af372255a829822192de0ccf2ddcb6197 würde ich sagen "geht so"… geht eventuell noch hübscher, aber imho noch besser als ein `try`...

2021-03-26 00:23 UTC, witsch commented on core/src/zeit/cms/content/caching.py
> +    def __getattr__(self, name):
Hat noch ein wenig mehr Isolierung gebraucht, aber 86ce9eea33501ecceca23df3426d09154be97555…

2021-04-01 10:53 UTC, wosc commented
Nur schonmal als Notiz, damit wirs nicht vergessen: Wir brauchen nen Featuretoggle für den Cache, damit wir den (möglichst ohne Deployment) stilllegen können, falls am Ende damit doch noch was klemmen sollte.

2021-04-08 11:43 UTC, witsch commented
> Nur schonmal als Notiz, damit wirs nicht vergessen: Wir brauchen nen Featuretoggle für den Cache, damit wir den (möglichst ohne Deployment) stilllegen können, falls am Ende damit doch noch was klemmen sollte.

Ok, "wenn's mal wieder länger dauert…" 🙄

Ein feature toggle gibt's jetzt jedenfalls mit 297c3b072684a304580e2c5d23ab5275fc478bc5 und die restlichen Anmerkungen, auf die du noch nicht geantwortet hattest, lass ich mal noch "unresolved". Da kannst du ja nächste Woche nochmal drübergucken bzw. wir zusammen und ggf. hinterher putzen. Ich würde — sofern [die Tests](https://ci.zeit.de/job/vivi_PR/763/) grün sind — das jetzt endlich mal mergen und auf 'staging' testen. Der Zeitpunkt ist grade günstig, weil Louisa aktuell Lasttests für Zappi vorbereitet und dabei dann sowieso nochmal recht viel getestet wird (abgesehen davon, dass der Fix da auch helfen sollte — es gab schon Beschwerden, dass die API langsam sei)…

2021-04-08 12:20 UTC, merged