Zon 5576: Add topicbox automatic sources
ZeitOnline/vivi pull request #193
Opened 2021-03-22 08:56 UTC by kabbeck

Fügt zu den Themenboxen automatische Quellen hinzu.

2021-03-22 09:01 UTC, kabbeck commented
run jenkins

2021-03-22 09:35 UTC, kabbeck commented
run jenkins

2021-03-26 13:04 UTC, wosc requested changes
Das Grundprinzip ist ja wie erhofft/erwartet einfach, "wir benutzen zeit.contentquery im Artikel". Im Detail hakelt es allerdings noch etwas.

2021-03-26 13:04 UTC, wosc commented on core/src/zeit/content/article/edit/topicbox.py
>                  filter(lambda x: x != parent_article,
Ohhh wo ich das gerade sehe: es gibt evtl _doch_ einen Usecase für hide_dupes in Topicboxen, kann das sein? Nämlich um den Artikel, in dem die Box enthalten ist, rauszufiltern. Evtl wollen wir das für diesen PR aber erstmal ignorieren und in nem zweiten Schritt nachrüsten, sonst platzt uns evtl der Kopf in Punkto Komplexität.

2021-03-26 13:04 UTC, wosc commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self.referenced_cp and self.automatic_type == 'manual':
Hmm das müsste sich doch eigentlich auf `automatic_type=='centerpage'` zurückführen lassen, oder?

2021-03-29 12:43 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/interfaces.py
> +class TopicpageFilterSource(zc.sourcefactory.basic.BasicSourceFactory,
Ja, klar. Keine Ahnung warum diese Klasse noch vorhanden ist. Wird natürlich entfernt.

2021-03-29 12:45 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/interfaces.py
> +class ConfigQuerySource(TopicpageFilterSource):
Ja, benenne ich um.

2021-03-29 12:56 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/topicbox.py
> +    automatic_type.mapping = {None: 'manual'}
Ok, dann mache ich _getter/setter_ wieder in die Topicbox-Klasse und entferne diesen Descriptor

2021-03-29 13:42 UTC, AWieczorreck commented on core/src/zeit/contentquery/query.py
> +        if self.query.get('query', {}) == {}:
Ich kann hier sowas anbieten:
`self.query = {'query': factory.getQuery(context._config_query)}`

In der Config muss dann immer:
`"query": { "term": { ... } }` anstatt
`"query": { "query": { "term": { ... } } }` stehen.
Ist ok für mich.

2021-03-30 10:02 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self.referenced_cp and self.automatic_type == 'manual':
Der Altbestand hat keinen automatic_type und setzen den automatic_type auf 'manual'. Das ist der default-Wert

2021-03-31 11:45 UTC, kabbeck commented on core/src/zeit/content/cp/area.py
> +    def _teaser_count(self):
f1b34ef

2021-03-31 11:46 UTC, kabbeck commented on core/src/zeit/contentquery/helper.py
>  class ReferencedCenterpageHelper:
5d70b29

2021-03-31 12:03 UTC, kabbeck commented on core/src/zeit/content/article/testing.py
> +class ElasticsearchMockLayer(plone.testing.Layer):
Hier hatten wir erst `zeit.retresco.testing.ElasticsearchMockLayer` benutzt und dann festgestellt, dass die Results aus https://github.com/ZeitOnline/vivi/blob/master/core/src/zeit/retresco/tests/elasticsearch_result.json nicht in der Struktur sind, wie wir sie in echt vom TMS in den ContentQueries zurückbekommen. Deshalb haben wir uns an den TMS Responses der ContentQueries orientiert und in einem eigenen Mock Layer diese Datei zur Verfügung gestellt https://github.com/ZeitOnline/vivi/blob/ZON-5576/core/src/zeit/content/article/tests/elasticsearch_search_response.json

2021-03-31 12:24 UTC, kabbeck commented on core/src/zeit/content/article/edit/topicbox.py
> +            while(len(filtered_content)) < 3:
Du meinst, man solle hier nicht prüfen, ob das den Themenbox zugelassenen Content-Typen entspricht? Also hier https://github.com/ZeitOnline/vivi/blob/ZON-5576/core/src/zeit/content/article/edit/topicbox.py#L172 Wenn man dies aus dem Code rausnimmt brauchen wir auch den Loop nicht mehr. Also bei Queries kann man sicher sagen, dass der Bediener selbstständig die Content-Typen setzen muss.

Wenn es doch jemand macht, siehst du eine Gefahr für das FE, wenn da dann drei Raw-Elemente o.ä. rauskommen, oder haben die dann auch immer einen Teaser etc.?

2021-03-31 12:29 UTC, kabbeck commented on core/src/zeit/content/article/edit/topicbox.py
>                  filter(lambda x: x != parent_article,
Ja, ich hab Angst um meinen Kopf :) Späßchen. Wir sollten den PR hier durchbekommen und lieber in kleineren Happen Nacharbeiten als neuen PR stellen. Der Plattform-Prozess will es so.

2021-04-14 09:25 UTC, wosc commented on core/src/zeit/cms/content/cache.py
> +            cache = content_cache(self.__parent__, attr or fn.__name__)
Das `__parent__` sollte hier überflüssig sein, das sollte direkt mit `self` funktionieren.

2021-04-14 09:25 UTC, wosc commented on core/src/zeit/contentquery/query.py
> +class ConfigQuery(ElasticsearchContentQuery):
Hier auch `PreconfiguredQuery`, oder?

2021-04-15 07:16 UTC, AWieczorreck commented on core/src/zeit/contentquery/query.py
> +class ConfigQuery(ElasticsearchContentQuery):
Ich hatte jetzt bewusst nur die `source` in `PreconfiguredQuerySource` geändert.
Die Query ja weiterhin vom Typ `ConfigQuery` ist...egal ob 'vorkonfiguriert oder nicht".

Gibt noch ein paar mehr Stellen im Code wo wir `config-query, _config_query, ...` gesetzt haben.
Kann das aber gerne überall anpassen, wenn das für dich sinnvoller ist :)

2021-04-15 08:30 UTC, kabbeck commented on core/src/zeit/cms/content/cache.py
> +            cache = content_cache(self.__parent__, attr or fn.__name__)
Da failen die Tests, weil Topicbox selbst nicht auf ICMSContent adaptierbar ist. Haben wir da irgendwo noch eine Abhängigkeitsdefinierungsmöglichkeit damit das geht? (Wir rätseln gerade, ob das nicht eigentlich gehen müsste, also die Kaskade wieder nach oben) 

```
  File "/Users/kabbeck/r/vivi-deployment/work/source/vivi/core/src/zeit/cms/content/cache.py", line 9, in content_cache
    parent = ICMSContent(context)
TypeError: ('Could not adapt', <zeit.content.article.edit.topicbox.Topicbox b'http://block.vivi.zeit.de/http://xml.zeit.de/art#None'>, <InterfaceClass zeit.cms.interfaces.ICMSContent>)
```

2021-04-15 12:13 UTC, kabbeck commented on core/src/zeit/content/article/edit/topicbox.py
> +            while(len(filtered_content)) < 3:
Ist hier geändert. Das Prüfen auf leeren Content (da scheitert sonst `next(content)` mit not iterable) fangen wir nun mit einer generischen Exception

2021-04-19 14:11 UTC, wosc commented on core/src/zeit/cms/content/cache.py
> +            cache = content_cache(self.__parent__, attr or fn.__name__)
Heissa. Da haben wir ja eine feine Altlast aufgedeckt. Habe ich in f12796e04 repariert (und in 8262967bd verwendet).

2021-04-19 14:12 UTC, wosc commented on core/src/zeit/contentquery/query.py
> +class ConfigQuery(ElasticsearchContentQuery):
Jo, fänd ich glaub lesbarer. Danke!

2021-04-20 07:28 UTC, kabbeck commented on core/src/zeit/cms/content/cache.py
> +            cache = content_cache(self.__parent__, attr or fn.__name__)
Super spannend, vielen Dank 🙏

2021-04-20 07:50 UTC, kabbeck commented on core/src/zeit/content/article/testing.py
> +class ElasticsearchMockLayer(plone.testing.Layer):
Wie meinst du genau kopieren @wosc. Kopieren im Sinne von 1:1 z.c.cp.ElasticsearchMockLayer nach z.c.article.ElasticsearchMockLayer duplizieren, dann fehlt uns doch das angepasste Result aus der elasticsearch_search_response.json und der hits Wert und wir haben die notwendigen Werte nicht für die ContentQuery Tests.

Oder meinst du kopieren im Sinne von ableiten, also so dieser Art?
```class ElasticsearchMockLayer(z.c.cp.ElasticsearchMockLayer):
    def setUp(self):
        super.setUp()
        .... und der ganze Kram der jetzt in z.c.article.ElasticsearchMockLayer passiert

2021-04-20 09:34 UTC, kabbeck commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self.referenced_cp and self.automatic_type == 'manual':
Das ist umgezogen in einer eigenen ContentQuery mit Hinweis auf "ich bin eigentlich keine ContentQuery" 4349993
und wenn eine CP referenziert ist, wird weiter an CenterpageContentQuery passiert. Damit fliegt der ganze Referenzen-Code aus der topicbox.py raus und das Prüfen auf Selbstreferenzialität des Artikel, der die Topicbox enthält, wird für alle Items eines ContentQuery-Ergebnis absolviert.

2021-04-20 09:36 UTC, kabbeck commented on core/src/zeit/cms/content/cache.py
> +            cache = content_cache(self.__parent__, attr or fn.__name__)
Test funktionieren alle wie gewünscht, ich markiere das als erledigt.

2021-04-20 13:57 UTC, wosc commented on core/src/zeit/content/article/testing.py
> +class ElasticsearchMockLayer(plone.testing.Layer):
Mein Gedanke war, dass es für die Tests in zeit.contentquery doch eigentlich nicht nötig sein sollte, mit diesem JSON-File die serverseitige Response zu mocken. Die wollen doch hauptsächlich sehen, dass da "eine Handvoll" Content-Objekte rauskommt. Oder entgeht mir was?
Und unter der Prämisse wäre halt der Layer aus z.c.cp eigentlich genau das richtige, aber den wiederzuverwenden sprengt denke ich den Rahmen, deshalb wärs für mich okay, den zu duplizieren.

2021-04-27 14:08 UTC, wosc approved these changes
![yay](https://i.giphy.com/media/SkgBJEEP3r1Fm/giphy.gif)

2021-04-27 14:29 UTC, merged