TOPIC-16: Add  tms content-topic-api
ZeitOnline/vivi pull request #211
Opened 2021-06-25 12:55 UTC by louika

Add tms content-topics-api endpoint and some maintenance

2021-07-01 07:59 UTC, wosc requested changes
Ausgezeichnete Aufräumung. Ich hab kleine Detailfragen, und über einen Fehlerbehandlungs-Parameter (damit zeit.web es leichter hat) sprachen wir ja schon.

2021-07-01 07:59 UTC, wosc commented on core/src/zeit/cms/tagging/testing.py
> +    def __init__(self, label, code=None, entity_type=None):
OK. Das können wir so machen, sollten es dann aber im Docstring erklären: Die uniqueId/Traversal-Mechanik erfordert lediglich eine ID (den `code`). Dass es den in zeit.retresco nicht wirklich gibt, sondern ein "Tag" durch Entity-Type+Keyword definiert ist, ist demgegenüber erstmal nicht so relevant, deshalb ignorieren wir das in den Tests (meistens); und falls es uns später doch nicht mehr passen sollte, können wir uns da auch easy umentscheiden.

2021-07-01 07:59 UTC, wosc commented on core/src/zeit/retresco/connection.py
> +    def get_content_topiclinks(self, content):
Hier brauchen wir glaub ich eine Runde "naming things". Ich denke, das bisherige `get_article_keywords` sollte vmtl irgendwas mit `topiclinks` heißen (das hatten wir ja im Zshg TOPIC-25 langwierig extra ausklamüsert, dass das zwei verschiedene Dinge sind). Also Vorschlag get_article_keywords -> get_article_topiclinks, und dann für diese neue Methode hier sowas wie get_content_topicpages?

2021-07-02 11:31 UTC, louika commented on core/src/zeit/retresco/connection.py
> +    def get_content_topiclinks(self, content):
naming things ist umgesetzt.

2021-07-02 13:13 UTC, louika commented on core/src/zeit/cms/tagging/testing.py
> +    def __init__(self, label, code=None, entity_type=None):
Erklärung ist eingefügt

2021-07-05 07:18 UTC, wosc reviewed
Cool, es wird! Ich denke du solltest als nächstes dann mal die zugehörige zeit.web Änderung bauen; ich vermute nämlich stark, dass wir auf ITMS dafür noch eine Funktion brauchen für den Usecase "zum Artikel die related Themenseiten als Topiclinks".

2021-07-05 07:18 UTC, wosc commented on core/src/zeit/retresco/configure.zcml
> -    <class class=".tag.Tag">
Die Security-Declaration muss auch nach zeit.cms.tagging umziehen. Da aber grade kein Test umfällt, dann fehlt uns da wohl was. Womöglich weil die Tests mit `FakeTags` arbeiten oder so?

2021-07-05 07:18 UTC, wosc commented on core/src/zeit/retresco/connection.py
> +                keyword.link = value['url'].lstrip('/')
Wie oben gesagt, den link kann man jetzt dann ja auch gleich im Konstruktor übergeben, statt ihn einzeln draufzuschreiben.

2021-07-05 07:18 UTC, wosc commented on core/src/zeit/retresco/connection.py
> +                keyword = zeit.cms.tagging.tag.Tag(
Bisschen lustig ist das schon, `Tag` Objekte rauszugeben für "Themenseiten", aber es passt natürlich exakt für den Anwendungsfall "Topiclinks anzeigen", für den wir es haben wollen. Insofern bin ich durchaus einverstanden. :)

2021-07-05 08:52 UTC, louika commented on core/src/zeit/retresco/configure.zcml
> -    <class class=".tag.Tag">
wir arbeiten in einem Teil der Tests mit den `FakeTags` und hier https://github.com/ZeitOnline/vivi/blob/TOPIC-16_topiclinks/core/src/zeit/cms/tagging/tests/test_tag.py#L149-L172 mit den richtigen Tags. Allerdings ist die "neue" Klasse `FakeTag` von `Tag` abgeleitet.

2021-07-09 12:02 UTC, wosc approved these changes
![yay](https://i.giphy.com/media/7EIjTivxbdVC0/giphy.gif)

2021-07-09 12:06 UTC, merged