ZON-6710: Changes topicbox default automatic_type value
ZeitOnline/vivi pull request #213
Opened 2021-06-28 14:32 UTC by AWieczorreck

Changes topicbox default automatic_type value from 'manual' to 'centerpage'

2021-06-29 06:16 UTC, wosc requested changes

2021-06-29 06:16 UTC, wosc commented on core/src/zeit/contentquery/configuration.py
> +        # Set automatic_type on 'centerpage' only at the new topicboxes.
Hi. Ich denke Du willst sowas hier stattdessen:

```diff
diff --git a/core/src/zeit/content/article/edit/topicbox.py b/core/src/zeit/content/article/edit/topicbox.py
index 243f6905e..1d064b733 100644
--- a/core/src/zeit/content/article/edit/topicbox.py
+++ b/core/src/zeit/content/article/edit/topicbox.py
@@ -41,7 +41,7 @@ class Topicbox(zeit.content.article.edit.block.Block,
         '.', 'automatic_type',
         zeit.content.article.edit.interfaces.ITopicbox['automatic_type'])
 
-    _automatic_type_bbb = {None: 'manual'}
+    _automatic_type_bbb = {None: 'centerpage'}
 
     hide_dupes = False
 
```

Und falls das nicht reichen sollte (kann schon sein, dass mir Details fehlen), wirst du `def automatic_type` auf `class Topicbox` halt überschreiben müssen. In der abstrakten `class Configuration` derart rumzumalen hilft jedenfalls nicht.

2021-06-29 08:20 UTC, AWieczorreck commented on core/src/zeit/contentquery/configuration.py
> +        # Set automatic_type on 'centerpage' only at the new topicboxes.
Ja, klar. Keine Ahnung warum ich das in die Configuration geschrieben habe  `¯\_(ツ)_/¯`
Es ist leider nicht nur damit getan `_automatic_type_bbb` zu ändern, da sonst die alten Topicboxen, die nur Referenzen haben "überschrieben" werden. Musste noch prüfen, ob es eine alte (ohne automatic_type)  oder eine neue (mit automatic_type) Box ist.
D.h wenn min. eine Referenz gesetzt ist und `automatic_type` None ist, soll weiterhin 'manual' gesetzt werden.
Ansonsten beim drag n' drop (erstellen) einer neuen Box, wird 'centerpage' gesetzt.

2021-06-29 09:55 UTC, wosc commented on core/src/zeit/content/article/edit/topicbox.py
> +                self._automatic_type = 'centerpage'
Wenn es nicht unbedingt erforderlich ist, sollte man vermeiden, bei Lesezugriffen zu schreiben. Und wenn ich das richtig verstehe, sollte `return 'centerpage'` hier ja auch passen, oder?

2021-06-29 09:55 UTC, wosc commented on core/src/zeit/content/article/edit/topicbox.py
> +        bbb = self._automatic_type_bbb.get(self._automatic_type)
Stattdessen kann man der Einfachheit halber `return super().automatic_type` schreiben. :)

2021-06-29 09:55 UTC, wosc commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self._automatic_type is None:
Ah und dann wäre noch die Frage, sollte man im [Interface](https://github.com/zeitonline/vivi/blob/master/core/src/zeit/content/article/edit/interfaces.py#L647) den Default-Wert auch ändern?

2021-06-29 12:23 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/topicbox.py
> +        bbb = self._automatic_type_bbb.get(self._automatic_type)
Oh perfekt..das ist gut. Die super()-Klasse macht das ja schon. Dieses `bbb`-Zeugs braucht ja hier auch nicht noch hin.

2021-06-29 12:24 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/topicbox.py
> +                self._automatic_type = 'centerpage'
Klar, `return  'centerpage'` ist auch möglich. Kann ich machen...ist ja beides möglich.

2021-06-29 12:29 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self._automatic_type is None:
Es geht ja hauptsächlich darum, dass Topicboxen ohne `automatic_type` korrekt verarbeitet werden.
Es gibt derzeit ja nur zwei Fällte wo das sein kann:
1. alte Topicbox (hat kein `automatic_type` aber min eine Referenz)
2. neu erstellte (rein gezogene), nicht gespeicherte Topicbox (ist komplett leer; hat auch kein `automatic_type`)

Fall 1 ist der, wo `automatic_type` 'manual' sein sollte.
Bei Fall 2 soll der Wert auf 'centerpage' gesetzt werden.
Alle anderen Fälle nehmen den Wert der in `automatic_type` steht.

Musste mich entscheiden "wie rum ich das ganze prüfe".
Fand es irgendwie einfacher alles auf "alt" bzw. 'manual' zu lassen und dann nur zu prüfen ob es eine "neue" Box ist und dann erst 'centerpage' zu setzen.

2021-06-29 12:36 UTC, wosc commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self._automatic_type is None:
Ah interessant. Dann ist evtl eine hilfreiche Perspektive, den neuen Weg zum möglichst normalen Code zu machen, und "bw-compat für alte Daten" im Code auch so zu kennzeichnen, in der Hoffnung, dass wir das womöglich irgendwann mal sogar löschen können.

2021-06-29 12:47 UTC, AWieczorreck commented
Wenn du soweit keine Anmerkungen oder Änderungen/Verbesserungen zu https://github.com/ZeitOnline/vivi/pull/213#discussion_r660567199 hast und es auch soweit nachvollziehen kannst, wäre ich mit diesem diff soweit zufrieden :) 
```diff --git a/core/src/zeit/content/article/edit/topicbox.py b/core/src/zeit/content/article/edit/topicbox.py
index d9b7f7763..26b4d80dc 100644
--- a/core/src/zeit/content/article/edit/topicbox.py
+++ b/core/src/zeit/content/article/edit/topicbox.py
@@ -72,10 +72,9 @@ class Topicbox(zeit.content.article.edit.block.Block,
         if self._automatic_type is None:
             if (self.first_reference, self.second_reference,
                     self.third_reference) == (None, None, None):
-                self._automatic_type = 'centerpage'
+                return 'centerpage'
 
-        bbb = self._automatic_type_bbb.get(self._automatic_type)
-        return bbb or self._automatic_type
+        return super().automatic_type
 
     @automatic_type.setter
     def automatic_type(self, value):
```

2021-06-29 15:24 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self._automatic_type is None:
Ok, ich habe jetzt folgenden Diff und am Ende eine Frage :)
```diff
diff --git a/core/src/zeit/content/article/edit/interfaces.py b/core/src/zeit/content/article/edit/interfaces.py
index 4a5af3699..558f7770e 100644
--- a/core/src/zeit/content/article/edit/interfaces.py
+++ b/core/src/zeit/content/article/edit/interfaces.py
@@ -644,7 +644,7 @@ class ITopicbox(IBlock,
         title=_('Automatic type'),
         source=TopicboxTypeSource(),
         required=True,
-        default='manual')
+        default='centerpage')
 
     first_reference = zope.schema.Choice(
         title=_("Reference"),
diff --git a/core/src/zeit/content/article/edit/topicbox.py b/core/src/zeit/content/article/edit/topicbox.py
index d9b7f7763..707d66d67 100644
--- a/core/src/zeit/content/article/edit/topicbox.py
+++ b/core/src/zeit/content/article/edit/topicbox.py
@@ -41,7 +41,7 @@ class Topicbox(zeit.content.article.edit.block.Block,
         '.', 'automatic_type',
         zeit.content.article.edit.interfaces.ITopicbox['automatic_type'])
 
-    _automatic_type_bbb = {None: 'manual'}
+    _automatic_type_bbb = {None: 'centerpage'}
 
     hide_dupes = False
 
@@ -68,14 +68,13 @@ class Topicbox(zeit.content.article.edit.block.Block,
 
     @property
     def automatic_type(self):
-        # Set automatic_type on 'centerpage' only at the new topicboxes.
+        # Backward compatibility for depreciated topicboxes
+        # Set automatic_type on 'manual' only at the old topicboxes.
         if self._automatic_type is None:
             if (self.first_reference, self.second_reference,
-                    self.third_reference) == (None, None, None):
-                self._automatic_type = 'centerpage'
-
-        bbb = self._automatic_type_bbb.get(self._automatic_type)
-        return bbb or self._automatic_type
+                    self.third_reference) != (None, None, None):
+                return 'manual'
+        return super(type(self), self).automatic_type
 
     @automatic_type.setter
     def automatic_type(self, value):
```
Wie kann ich `super(type(self), self).automatic_type` schöner schreiben?
`super().automatic_type` gibt mir ein `RuntimeError: super(): no arguments`

2021-06-30 07:55 UTC, wosc commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self._automatic_type is None:
Cool. Man lernt nie aus. Das ist ein aktiver Python-Bug (siehe z.B. https://stackoverflow.com/a/10810545 und dann https://bugs.python.org/issue14965 -- created 05/2012, last updated 05/2021), dass bei Properties/Deskriptoren und super nur "get" funktioniert, aber nicht "set".

Also ich fürchte, das muss man tatsächlich so schreiben (damit laufen die Topicbox-Tests bei mir):

```python
    @property
    def automatic_type(self):
        return super().automatic_type

    @automatic_type.setter
    def automatic_type(self, value):
        # XXX https://bugs.python.org/issue14965
        super(type(self), type(self)).automatic_type.__set__(self, value)
```

2021-06-30 09:18 UTC, AWieczorreck commented on core/src/zeit/content/article/edit/topicbox.py
> +        if self._automatic_type is None:
Oh interessant :)
Habe das auch nochmal getestet scheint soweit zu funktionieren

2021-06-30 10:56 UTC, wosc approved these changes
![yay](https://i.giphy.com/media/ySAKulTdgY5G/giphy.gif)

2021-06-30 10:56 UTC, merged