OPS-2024: Handles invalid variant size
ZeitOnline/vivi pull request #216
Opened 2021-07-01 09:42 UTC by AWieczorreck

Wenn ein Bildzuschnitt den Parameter `size=(0,0)` bekommt, wirft PIL einen SystemError (tile cannot extend outside image).
Es wird versucht ein Bereich aus einem Bild herauszuschneiden, der über die Größe des Bildes geht.
Dieser PR setzt `size = None`, wenn min. ein Wert aus `size` 0 ist.

2021-07-02 07:19 UTC, wosc requested changes

2021-07-02 07:19 UTC, wosc commented on core/src/zeit/content/image/transform.py
> +        size = None if type(size) == tuple and 0 in size else size
Ich glaub die passendere Stelle das abzufangen wäre etwas weiter unten:

```diff
diff --git a/core/src/zeit/content/image/transform.py b/core/src/zeit/content/image/transform.py
index 4eed82a8c..28de9acbd 100644
--- a/core/src/zeit/content/image/transform.py
+++ b/core/src/zeit/content/image/transform.py
@@ -89,7 +89,7 @@ class ImageTransform(object):
 
         return self._construct_image(image, format)
 
-    def _crop_variant_image(self, variant, size=None):
+    def _crop_variant_image(self, variant, size=(0, 0)):
         """Crop variant image from source image.
 
         Determines crop position using zoom, focus point and size constraint.
@@ -116,9 +116,9 @@ class ImageTransform(object):
             target_ratio = (float(sw) / float(sh)) if sh != 0 else 0
         target_width, target_height = self._fit_ratio_to_image(
             zoomed_width, zoomed_height, target_ratio)
-        if size:
-            w, h = size
-            override_ratio = (float(w) / float(h)) if h != 0 else 0
+        w, h = size
+        if w > 0 and h > 0:
+            override_ratio = (float(w) / float(h))
             target_width, target_height = self._fit_ratio_to_image(
                 target_width, target_height, override_ratio)
```

2021-07-05 09:24 UTC, AWieczorreck commented on core/src/zeit/content/image/transform.py
> +        size = None if type(size) == tuple and 0 in size else size
Die Funktion `_crop_variant_image` kann weiterhin ein `None` als gültigen Wert bekommen.
Gibt ein `cannot unpack`-Error bei `w, h = size` und lasse das `if size:` daher bestehen.
Ich passe die Überprüfung aber an.

2021-07-06 06:47 UTC, wosc approved these changes
![yay](https://i.giphy.com/media/FEd6Jpq2NFNzW/giphy.gif)

2021-07-06 06:48 UTC, merged