ZON-6316: mv speechbert checkbox to options section and rename it
ZeitOnline/vivi pull request #219
Opened 2021-07-02 16:00 UTC by thomasbaumann

2021-07-06 14:15 UTC, thomasbaumann commented
run jenkins

2021-07-06 14:16 UTC, thomasbaumann commented
jenkins run

2021-07-08 09:12 UTC, zon-hoppe requested changes
feini, aber zwei anmerkungen:

1. ein changelog bitte noch.
2. im ticket steht, die box moege das label "Text-to-Speech-Player" haben!?

2021-07-08 11:44 UTC, thomasbaumann commented
Wie komme ich denn bloß auf "In-Article Player anzeigen"... 🤔

2021-07-08 11:46 UTC, thomasbaumann commented
...ah, weil es im Screenshot-Entwurf so steht...

2021-07-08 12:27 UTC, zon-hoppe commented
boah, voll am force pushen

2021-07-08 14:09 UTC, zon-hoppe requested changes
Jetzt passen message-id und title nicht mehr zusammen ;)

2021-07-09 12:38 UTC, zon-hoppe approved these changes
jetzt stimmt der text :)

2021-07-09 12:39 UTC, merged