ZON-6301: Adds checkbox on CPs in SEO tab, to enable RSS-Feed single tracking
ZeitOnline/vivi pull request #222
Opened 2021-07-08 13:32 UTC by AWieczorreck

Fügt in den SEO-Tab bei den CPs eine neue Checkbox hinzu "RSS Tracking-Parameter aktivieren".
Dadurch kann festgelegt werden, ob für die Artikel auf der CP, Tracking-Parameter hinzugefügt werden sollen.
Der aktuelle Feature-Toggle _rss_newsfeed_tracking_ aktiviert bisher immer auf allen Seiten das Tracking.

**Friedbert-Teil folgt....**

2021-07-13 08:06 UTC, wosc requested changes

2021-07-13 08:06 UTC, wosc commented on core/src/zeit/seo/browser/form.py
> -    form_fields = (
Hi. Wenn das super wichtig ist, dass das Feld nur bei CPs angezeigt wird (und nicht einfach überall :) -- was ich schon nachvollziehen könnte -- dann ist die übliche Schreibweise, in z.c.cp eigene SEO-Views für ICenterPage zu registrieren, die von den normalen Klassen in zeit.seo erben und das Feld halt dort hinzufügen.

Also so ungefähr (da kommt dann leider ein bisschen copy&paste zusammen, weil es zwei Views sind, Edit+Display, und dann noch ein Menüeintrag):

```xml
  <browser:page
    name="seo-edit.html"
    for="zeit.content.cp.interfaces.ICenterPage
    layer="zeit.cms.browser.interfaces.ICMSLayer"
    class=".form.SEOEdit"
    permission="zeit.seo.Edit"
    menu="zeit-context-views" title="Edit SEO"
    />
```

2021-07-13 08:32 UTC, AWieczorreck commented on core/src/zeit/seo/browser/form.py
> -    form_fields = (
Ja, soll nur bei CPs zu sehen sein, ist wichtig.
Ich war auch kurz bei dieser "Views"-Lösung, wurde mir aber zu blöd und habe den Weg des geringsten Widerstand genommen :) Wegen einer Checkbox so einen Aufwand, habe ich mir gedacht....
Aber ich versuche mich gerne nochmal daran :+1:

2021-07-23 07:28 UTC, wosc requested changes

2021-07-23 07:28 UTC, wosc commented on core/src/zeit/content/cp/centerpage.py
> +@grok.adapter(zeit.content.cp.interfaces.ICenterPage)
Das so aufzuschreiben ist etwas ungewöhnlich/unerwartet. Wenn die Basisklasse kein grok kann (#historischgewachsen), sollte man entweder die CPSeo-Klasse halt per ZCML registrieren, oder mal die SEO-Klasse auf grok umstellen -- also ganz genau genommen auf `zeit.cms.content.dav.DAVPropertiesAdapter`, das wär vmtl eh eine gute und vereinfachende Tat (da kann dann zb auch die `seo_dav_properties` Funktion entfallen, weil das von der Mechanik übernommen wird)

2021-07-23 07:28 UTC, wosc commented on core/src/zeit/content/cp/browser/form.py
> +    field_groups = (
Ich würde eigtl hoffen, dass das nicht nötig ist, das zu kopieren, das sollte sich erben lassen (und falls nicht sollte man machen, dass das geht ;).

2021-07-23 07:28 UTC, wosc commented on core/src/zeit/content/cp/browser/form.py
> +    form_fields = (
Das sollte sich kürzer schreiben lassen so in der Art `SEOBaseForm.form_fields + FormFields(ICPSeo)`, würde ich hoffen.

2021-07-23 07:28 UTC, wosc commented on core/src/zeit/content/cp/browser/form.py
> +    title = _("View SEO Data")
Das sollte sich einfach vererben, muss man nicht kopieren.

2021-07-23 07:28 UTC, wosc commented on core/src/zeit/content/cp/browser/form.py
> +    title = _("Edit SEO Data")
dito

2021-07-23 07:28 UTC, wosc commented on core/src/zeit/content/cp/browser/form.py
> +    form_fields = (
Hm hier blick ich jetzt grad nicht durch, sollten hier auch die von der SEOBaseForm angezogenen ICommonMetadata-Felder mit drauf sein (so müsste es bisher sein?) oder sollen die weg?

2021-07-23 09:34 UTC, AWieczorreck commented on core/src/zeit/content/cp/browser/form.py
> +    form_fields = (
Klar.
Die sollen hier natürlich auch mit rein ;)

2021-07-23 09:35 UTC, AWieczorreck commented on core/src/zeit/content/cp/browser/form.py
> +    form_fields = (
`SEOBaseForm` beinhaltet ja Forms aus `ISEO`. `ICPSeo` erbt die Forms aus `ISEO`.
`SEOBaseForm.form_fields + FormFields(ICPSeo)` würde ein `DuplicateName`-Form error erzeugen.

Würde sonst die `form_fields` für CpSEO in eine eigene Klasse schieben, dann vererbt ich von der Klasse, also z.B. so:

```python
class SEOCpForm(object):
    form_fields = (
        FormFields(ICpSEO) +
        FormFields(ICommonMetadata).select('keywords', 'ressort', 'sub_ressort', 'serie')
    )

class SEOView(SEOCpForm, SEODisplay):
    pass

class SEOEdit(SEOCpForm, SEOEdit):
    pass
```

2021-07-23 09:36 UTC, AWieczorreck commented on core/src/zeit/content/cp/browser/form.py
> +    field_groups = (
Ja, natürlich. `field_groups` muss hier nicht auch noch hin.

2021-07-23 09:37 UTC, AWieczorreck commented on core/src/zeit/content/cp/browser/form.py
> +    title = _("View SEO Data")
siehe https://github.com/ZeitOnline/vivi/pull/222#discussion_r675431400

2021-07-23 09:37 UTC, AWieczorreck commented on core/src/zeit/content/cp/browser/form.py
> +    title = _("Edit SEO Data")
siehe https://github.com/ZeitOnline/vivi/pull/222#discussion_r675431400

2021-07-26 12:53 UTC, wosc commented on core/src/zeit/content/cp/browser/form.py
> +    form_fields = (
Gegenvorschlag `SEOBaseForm.form_fields + FormFields(ICPSeo).select('enable_rss_tracking_parameter')`? :)

2021-07-27 12:07 UTC, AWieczorreck commented on core/src/zeit/content/cp/browser/form.py
> +    form_fields = (
Ja, das mit dem `select` finde ich gut :)
aaaber, dann muss das ja in die `SEOView` und `SEOEdit` rein.
Ist das nicht netter, deinen Vorschlag in die `SEOCpForm` zu schreiben, also so:

```python
SEOCpForm(object):
    form_fields = (
        SEOBaseForm.form_fields + FormFields(ICPSeo).select('enable_rss_tracking_parameter')
    )

class SEOView(SEOCpForm, SEODisplay):
    pass

class SEOEdit(SEOCpForm, SEOEdit):
    pass
```

Finde ich schöner als:
```python
class SEOView(SEODisplay):
    form_fields = (
        SEOBaseForm.form_fields + FormFields(ICPSeo).select('enable_rss_tracking_parameter')
    )

class SEOEdit(SEOEdit):
    form_fields = (
        SEOBaseForm.form_fields + FormFields(ICPSeo).select('enable_rss_tracking_parameter')
    )
```

2021-07-27 12:15 UTC, wosc commented on core/src/zeit/content/cp/browser/form.py
> +    form_fields = (
Ja auf jeden Fall! Von einer Zwischen/Basisklasse bin ich sowieso ausgegangen :)

2021-07-27 14:56 UTC, AWieczorreck commented on core/src/zeit/content/cp/centerpage.py
> +@grok.adapter(zeit.content.cp.interfaces.ICenterPage)
https://github.com/ZeitOnline/vivi/pull/222/commits/194dbf4a7d768f17b9aaa094b3b7b2e24147b8d5 👀

2021-07-28 06:30 UTC, AWieczorreck commented
jenkins run

2021-07-28 06:31 UTC, AWieczorreck commented
run jenkins

2021-07-28 06:51 UTC, wosc approved these changes
![](https://i.giphy.com/media/G24ANbymhNc08/giphy.gif)

2021-07-29 11:57 UTC, merged