BUG-1430: gracefully handle locks during brightcove import
ZeitOnline/vivi pull request #224
Opened 2021-07-12 09:52 UTC by tomster

als konkrete diskussionsgrundlage

2021-07-13 08:21 UTC, wosc requested changes
Das ist glaube ich deutlich zu grobschlächtig. Nur weil zb ein Bild grade stolpert, soll ja nicht der ganze Rest übersprungen werden. (Bzw wenn man das so machen wollte, bräuchten wir ausgeklügelte Retry-Logik, die wir nicht haben).

Ich denke, man sollte die möglichen Fehler gezielt da fangen, wo sie entstehen, also in dem Fall im `download_teaser_image`.

2021-07-13 08:29 UTC, tomster commented
aber waere das dann nicht ebenfalls problematisch, weil wir dann ein video ohne bild haetten z.b.? meine denke war, dass das ganze idealerweise atomar passiert und entweder funktioniert oder nicht. und wenn nicht dann entweder nochmal probiert wird. aber dazu muesste man sich dann in der tat das retry verhalten anschauen. im prinzip kann man celery sehr explizit sagen, dass er es (nach eigenem gusto) nochmal probieren oder lieber ganz aufgeben soll.

2021-07-13 09:28 UTC, wosc commented
Hmm. Atomarität ist natürlich ein guter Punkt -- aber ich bin nicht ganz sicher, ob der tatsächlich zutrifft. Die inhaltliche Frage ist doch, ist das überhaupt vorgesehen, die aus BC importierten Bilder in vivi zu bearbeiten? Wenn ich den aktuellen Code richtig verstehe, wird das nämlich bei Änderungen in BC eiskalt wieder überschrieben.

Wenn das das gewünschte Verhalten ist, sollte man die vivi-Bilder vmtl irgendwie un-auscheckbar machen, oder, dann kanns auch nicht zu Locking-Problemen kommen. ;) Wenn das nicht das gewünschte Verhalten ist, müsste doch sowas gelten wie  "Locking-Fehler beim Bilder aktualisieren ignorieren wir halt, weil vivi-User die ja bearbeiten können _sollen_" (und eben genau _nicht_ "entweder aktualisieren wir das Video mit allem oder gar nicht"). Oder bin ich grade auf dem Holzweg?

2021-08-02 09:36 UTC, tomster commented
@wosc das ergibt sinn. da dann nichts von diesem ansatz uebrig bleibt, habe ich einen neuen PR gemacht #237 und schliesse diesen hier

2021-08-02 09:36 UTC, closed without merging