TOPIC-36: Add reach as automatic area source
ZeitOnline/vivi pull request #227
Opened 2021-07-13 12:10 UTC by Hennnnes

We want to use reach as a source for our automatic areas.
I had to move some zeit.web buzz CP-Extra code into the query. I think that should fit.

- [ ] Rebase once TOPIC-31 is on master

2021-07-14 06:53 UTC, Hennnnes commented on core/src/zeit/contentquery/query.py
> +            # XXX: This was a zeitweb setting once...
Die Stelle hier find ich noch spannend. Evtl. müsste ich das nochmal in zeit.web überschreiben oder so?

2021-07-14 12:20 UTC, wosc requested changes
Die Richtung stimmt total, es geht aber noch nicht weit genug. :)

2021-07-14 12:20 UTC, wosc commented on core/src/zeit/contentquery/interfaces.py
> +        default='views')
Das sind aktuell noch deutlich zu wenig Parameter für die reach Datenquelle. :) Das ist nämlich jetzt ja genau der Vorteil, dass es an der Fläche Parameter gibt, die man einstellen kann, und dass der Code nicht mehr, wie vorher beim parameterlosen cpextra, sich alles zusammenraten muss, was "vermutlich" gemeint/sinnvoll sein könnte. Ich denke, das müssten ungefähr folgende werden:
- reach_metric (views/comments/subscriptions/social/trend)
- reach_ressort
- reach_access
- reach_age (vmtl ist sinnvoll, das in Tagen einzustellen)

(Wie wir die genau benennen sei mal noch dahingestellt ;)

2021-07-14 12:20 UTC, wosc commented on core/src/zeit/contentquery/query.py
> +        results = reach.get_ranking(self.service, **self.ranking_params)
Hier muss dann auch noch self.rows als `limit` übergeben werden.

2021-07-14 12:20 UTC, wosc commented on core/src/zeit/contentquery/query.py
> +        return [zeit.cms.interfaces.ICMSContent(
Aus `get_ranking` kommen bereits Content-Objekte, das muss man hier nicht nochmal auflösen.

Aber was mir dabei auffällt, du hast völlig Recht: Für vivi ist `ICMSContent` als `_resolve` die richtige Geste. Nur in zeit.web ist es vmtl. sinnvoller, stattdessen ES+ITMSContent zu bemühen (wobei mir da grade auffällt, dass wir das mal mengenwertig aufschreiben sollten, anstatt jedes Dokument einzeln. Aber ich schweife ab). Wir haben allerdings aktuell letzteres nach zeit.reach reinkopiert, dh das müsste vmtl wieder raus und zurück nach zeit.web wandern.

2021-07-14 13:45 UTC, Hennnnes commented on core/src/zeit/contentquery/interfaces.py
> +        default='views')
aye aye

2021-07-15 13:12 UTC, Hennnnes commented
@wosc ich hoffe es sollte jetzt alles passen :)

2021-07-15 13:34 UTC, Hennnnes commented on core/src/zeit/contentquery/query.py
> +        return zeit.cms.interfaces.ICMSContent(content.uniqueId)
Ich bin mir noch nicht sicher, ob das hier so der richtige Weg ist, um es nachher in zeit.web richtig zu überschreiben...

2021-07-19 11:19 UTC, Hennnnes commented
@wosc Vielen Dank für's durchfeudeln und überhaupt erstmal gangbar machen ![](https://media.giphy.com/media/6RuhlzSdhIAqk/giphy.gif)

2021-07-19 12:06 UTC, merged