TOPIC-19: Random sort order for elasticsearch queries
ZeitOnline/vivi pull request #232
Opened 2021-07-21 14:25 UTC by louika

Fügt der Individuellen Abfrage `random` als Sortierungsoption hinzu. Diese ist im Drop-Down Menü unter "zufällig" verfügbar und liefert wirklich zufällige Ergebnisse.

Testen:

Eine Centerpage mit Area mit individueller Abfrage und Sortierungsoption "zufällig" erstellen, speichern und veröffentlichen. Anschließend die Sortierung der Teaser prüfen. Diesen Vorgang wiederholen um zu prüfen, ob die Auto-Area jedesmal anderen Content enthält.

https://zeit-online.atlassian.net/browse/TOPIC-19

2021-07-21 14:25 UTC, louika commented
seufz, dann mach ich die Übersetzung wohl nacher nochmal.

2021-07-22 10:57 UTC, louika commented
es sind keine Tests umgefallen? 🤔  _I am suspicious..._

2021-07-22 11:20 UTC, wosc requested changes
Prima! Ich hab eine Kleinigkeit, und dann die Frage, denkst du an einen zugehörigen zeit.web PR, der die dortigen Stellen anpasst, die bisher `sort_order` verwenden? (_Mindestens_ der /suche/index Support macht was mit Sortierung IIRC.)

2021-07-22 11:20 UTC, wosc commented on core/src/zeit/contentquery/query.py
> +        if 'random' not in field:
Hmm. Entweder wir supporten `random` bei raw queries auch (dann muss die Implementierung von `CustomQuery` auf diese Klasse hier hochwandern), oder wir supporten es nicht -- dann braucht man hier auch keine Sonderbehandlung. Mir isses im Prinzip egal, aber da es mir leicht erscheint es zu supporten, könnten wir das tun. (Schwieriger würde es, wenn wir bei raw queries auch beliebige `{"sort": ...}` Clauses erlauben wollten, weil sich das dann vmtl. mit dem Einschießen des hide_dupes Clause behakelt. Aber das ist jetzt ja auch in keinster Weise verlangt, insofern müssen wir darüber nicht nachdenken. :)

2021-07-22 12:01 UTC, louika commented on core/src/zeit/contentquery/query.py
> +        if 'random' not in field:
Dann schiebe ich das da hoch. 🧹

2021-07-22 13:38 UTC, merged