BUG-1437: Skip tests with non expected TechnicalErrors in VGWort
ZeitOnline/vivi pull request #233
Opened 2021-07-26 13:19 UTC by AWieczorreck

2021-07-26 13:37 UTC, tomster commented
Den "Kniff" mit dem Technical Error ist genau der richtige Ansatz. ich wuerde nur der vollstaendigkeithalber dann kein ``pass`` erzeugen, sondern ein xfail ala ``xfail("VGWort backend is known to be wonky")``.

2021-07-26 13:37 UTC, tomster requested changes

2021-07-26 13:37 UTC, tomster commented on core/CHANGES.txt
> +- BUG-1437: Skip tests with non expected TechnicalErrors
hier ruhig noch vg wort erwaehnen

2021-07-27 06:33 UTC, AWieczorreck commented on core/CHANGES.txt
> +- BUG-1437: Skip tests with non expected TechnicalErrors
Jau, alles klar.
Passe ich alles gerne an.

2021-07-27 06:33 UTC, wosc commented
Tom, der Haken ist, dass stdlib unittest (was in vivi noch überwiegend verwendet wird) nur strict xfail unterstützt AFAIK -- dh wenn das passed (was es ja _meistens_ tun sollte), dann zählt er _das_ als Failure. Insofern ist print oder pass oder so vmtl doch die geeignetere Geste hier.

2021-07-27 06:43 UTC, merged