ZO-539: Image_group_from_image belongs to image
ZeitOnline/vivi pull request #291
Opened 2022-02-04 11:24 UTC by louika

2022-02-07 13:17 UTC, wosc requested changes

2022-02-07 13:17 UTC, wosc commented on core/src/zeit/content/image/image.py
> +def image_group_from_image(where, name, image):
Wie der Funktionsname schon nahelegt, gehört diese Funktion nach z.c.image.imagegroup, und nicht .image. :)

Und ich würde vorschlagen, das als classmethod `ImageGroup.from_image()` aufzuschreiben statt als freistehende Funktion.

2022-02-07 14:53 UTC, louika commented on core/src/zeit/content/image/image.py
> +def image_group_from_image(where, name, image):
war das evtl. der Grund, warum es sich um eine Funktion und nicht um eine Methode gehandelt hat?
````
Traceback (most recent call last):
  File "/Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/content/image/tests/test_imagegroup.py", line 323, in test_image_group_from_none
    repository, 'group', None)
  File "/Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/content/image/imagegroup.py", line 183, in from_image
    where[name] = group
TypeError: 'method' object does not support item assignment
````

2022-02-07 15:12 UTC, wosc commented on core/src/zeit/brightcove/json/tests/test_update.py
>  class ImageGroupFromImage(zeit.content.image.testing.BrowserTestCase):
Der Test will vmtl auch mit nach z.c.image umziehen :)

2022-02-07 15:12 UTC, wosc commented on core/src/zeit/content/image/imagegroup.py
> +    def from_image(where, name, image):
Ich kann mir kaum vorstellen, dass das in der Form funktioniert :), ich denke das muss so heißen:

```suggestion
    @classmethod
    def from_image(cls, where, name, image):
```

2022-02-07 15:12 UTC, wosc commented on core/src/zeit/content/image/imagegroup.py
> +        group = ImageGroup()
```suggestion
        group = cls()
```

2022-02-10 08:32 UTC, wosc approved these changes
![](https://i.giphy.com/media/1lwSVzx1l1Ute2J3qc/giphy.gif)

2022-02-10 08:34 UTC, merged