ZO-815: GCP Storage
ZeitOnline/vivi pull request #292
Opened 2022-02-16 09:51 UTC by fschulze

Enthält die besprochenen Änderungen, sowie den GCP Storage Teil.

2022-02-16 12:16 UTC, fschulze commented
Ich musste master mergen, sollte dann am Besten nochmal rebased werden.

2022-02-21 14:41 UTC, wosc commented
run jenkins

2022-02-22 15:21 UTC, wosc requested changes
Besten Dank für die Detail-Nacharbeiten! Mir sind zwei Themen aufgefallen, der sqlalchemy-Cache funktioniert irgendwie nicht, und für GCS brauchts noch echte Authentifizierung (siehe Einzelkommentare).

2022-02-22 15:21 UTC, wosc commented on core/src/zeit/connector/tests/test_contract.py
> +            sorted(self.listCollection(collection_id)))
Das macht mit dem DAV noch irgendwie [Mechanik-Probleme](https://ci.zeit.de/job/vivi_PR/1128/testReport/junit/core.src.zeit.connector.tests.test_contract/ContractDAV/test_delitem_of_collection_removes_children/)

<details>

```
Traceback (most recent call last):
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/testing.py", line 378, in delegate
    return getattr(super(type(self), self), name)()
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/tests/test_contract.py", line 105, in test_delitem_of_collection_removes_children
    sorted(self.listCollection(collection_id)))
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/tests/test_contract.py", line 23, in listCollection
    return list(self.connector.listCollection(id))
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/connector.py", line 129, in listCollection
    for child_id in self._get_resource_child_ids(id):
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/connector.py", line 171, in _get_resource_child_ids
    davres.update()
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/dav/davresource.py", line 381, in update
    self._result = self._propfind(depth=depth)
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/dav/davresource.py", line 614, in _propfind
    self.url, body=PROPFIND_BODY, depth=depth, extra_hdrs=hdrs)
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/dav/davconnection.py", line 48, in propfind
    *args, **kwargs)
  File "/srv/jenkins/work/workspace/vivi_PR/core/src/zeit/connector/dav/davconnection.py", line 132, in get_result
    raise exception(response.status, response.reason, url, body, response)
zeit.connector.dav.interfaces.DAVRedirectError: (301, 'Moved Permanently', 'http://localhost:57083/cms/testing/folder', '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>301 Moved Permanently</title>\n</head><body>\n<h1>Moved Permanently</h1>\n<p>The document has moved <a href="[http://localhost:57083/cms/testing/folder/"](http://localhost:57083/cms/testing/folder/)>here</a>.</p>\n<hr>\n<address>Apache/2.4.29 (Ubuntu) Server at localhost Port 57083</address>\n</body></html>\n', <http.client.HTTPResponse object at 0x7fa50ed2dd90>)
```
</details>

2022-02-23 10:04 UTC, fschulze commented on core/src/zeit/connector/postgresql.py
> +        return client.bucket(self.storage_bucket)
Ich verwende an der Stelle ``client.bucket``, was nur eine Klasse instanziert und ``client.download_blob_to_file`` macht im Kern nichts anderes. Das von dir erwähnte ``client.get_bucket`` scheint tatsächlich mehr zu machen. Wenn ich es mit meinen Credentials verwende, dann macht ``get_bucket`` einen request und liefert direkt ein 404. Mit ``bucket`` bekomme ich nur die Klasse zurück und es failed dann erst beim Zugriff, da der Bucket nicht existiert.

2022-02-23 10:07 UTC, fschulze commented on core/src/zeit/connector/postgresql.py
> +        client = storage.Client.create_anonymous_client()
Wenn ich an der Stelle einfach direkt ``Client()`` aufrufe, dann funktioniert es beim Testruns und in Produktion würde ich ``GOOGLE_APPLICATION_CREDENTIALS`` im environment setzen. Können wir notfalls auch in der Klasse aus der Config heraus machen. Ist glaub ich die einfachste Lösung.

2022-02-23 10:11 UTC, fschulze commented on core/src/zeit/connector/postgresql.py
> +        return id.replace('-', '/')
Lokal werden dadurch Unterverzeichnisse erzeugt. Ist für die Tests wahrscheinlich irrelevant. Bei GCP vermutlich auch, da dort vermutlich ein Key/Value-Store dahinter steht, dem zig tausende Objekte im gleichen "Verzeichnis" egal sind. Könnte also raus.

2022-02-23 10:13 UTC, fschulze commented on core/src/zeit/connector/tests/test_contract.py
> +            sorted(self.listCollection(collection_id)))
Zur Info, bei dem Link bekomme ich 403.

2022-02-23 10:14 UTC, fschulze commented on core/src/zeit/connector/tests/test_contract.py
> +            sorted(self.listCollection(collection_id)))
Wie kann ich das Lokal testen? Mit ``./bin/test vivi/core/src/zeit/connector`` wird es nicht mit DAV laufen gelassen.

2022-02-23 12:00 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        client = storage.Client.create_anonymous_client()
Stimmt. Wir können uns deren Discovery-Mechanismus schlicht zu nutze machen. 👍

2022-02-23 12:09 UTC, wosc commented on core/src/zeit/connector/tests/test_contract.py
> +            sorted(self.listCollection(collection_id)))
Der Jenkins erfordert VPN.

Ah, die DAV-Tests sind [extra](https://github.com/ZeitOnline/vivi/blob/master/core/src/zeit/connector/testing.py#L133) markiert und laufen [per default nicht](https://github.com/ZeitOnline/vivi-deployment/blob/master/components/dev/pytest.ini#L2), musste `-m slow` oder `-m 1` sagen.

2022-02-23 12:24 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        return client.bucket(self.storage_bucket)
Ah, ja super, dann passt diese API ja, und meine Bedenken waren unbegründet.

2022-02-24 10:00 UTC, fschulze commented on core/src/zeit/connector/tests/test_contract.py
> +            sorted(self.listCollection(collection_id)))
Scheinbar werden beim WebDAV die Unterelement nicht gelöscht wenn eine Kollektion gelöscht wird. Ich passe das entsprechend mit Kommentaren an.

2022-02-24 10:59 UTC, wosc commented on core/src/zeit/connector/tests/test_contract.py
> +            sorted(self.listCollection(collection_id)))
Hmm das "kann nicht sein" eigentlich... wenn man `rmcol` sagt, werden die Kinder definitiv auch gelöscht.

2022-02-24 11:30 UTC, fschulze commented on core/src/zeit/connector/tests/test_contract.py
> +            sorted(self.listCollection(collection_id)))
Ich habe es debugged. Im regulären Connector in ``__delitem__`` liefert WebDAV ein 204 zurück und die Properties stehen nicht mehr zur Verfügung, aber die Kinder sind noch da.

2022-02-24 11:43 UTC, fschulze commented on core/src/zeit/connector/postgresql.py
> -    property_cache = TransactionBoundCache('_v_property_cache', dict)
Hatte was aus dem POC gefehlt, siehe ``_index_object``.

2022-02-24 11:48 UTC, fschulze commented
Sollte nun alles behoben sein.

Bei Friedbert mit ``work/web/web.ini``:
```
connector_type = sql-pass
vivi_zeit.connector_storage-project = vivi
vivi_zeit.connector_storage-bucket = zeit-test-bucket
```
und
```
./work/app/bin/gcp-storage-emulator start --host localhost --port 9023 --default-bucket zeit-test-bucket
```
sowie
```
STORAGE_EMULATOR_HOST="http://localhost:9023" ./bin/serve
```
Läuft es dann lokal mit dem GCP storage emulator (eventuell vorher ``dropdb vivi; createdb vivi``).

Mit den Test Daten haben wir allerdings UUID Konflikte auf z.B. ``/index``. Ich habe erstmal dagegen einen Guard eingebaut, damit man Testen kann. Das loggt ein ``Critical``, aber macht dann weiter mit ``KeyError`` statt abzubrechen.

2022-02-28 14:24 UTC, fschulze commented
Ich habe zum Vergleichen nun noch einen reinen "Not Found" cache für properties und einen vollständigen Cache eingebaut. Macht bei meinen Tests jeweils kaum einen Unterschied. Allerdings sind die Test-Daten mit Default-Einstellungen nicht sonderlich komplex. Was hast du zum Testen verwendet?

2022-03-03 10:10 UTC, wosc commented
Habs durch Cherry-Picks nach #289 applied.

2022-03-03 10:10 UTC, closed without merging