ZO-365: resize additional images in imagegroups while uploading
ZeitOnline/vivi pull request #296
Opened 2022-02-25 07:22 UTC by thomasbaumann

In the 'file list' view is another upload field. Uploaded too large images from
there were not resized to max image size.

2022-02-25 12:10 UTC, thomasbaumann commented
run jenkins

2022-03-02 15:01 UTC, wosc requested changes

2022-03-02 15:01 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +        image = zeit.content.image.browser.form.AddForm.resize(self, image)
Puh. Also ja, Python lässt einen das von der Mechanik her tun, `self` an eine fremde Klassen-Methode zu übergeben, obwohl die eigene Klasse und die andere nichts miteinander gemeinsam haben. Aber das ist schwer zu überblicken (und riskiert Probleme, wenn die andere Klasse sich "unkontrolliert" ändert).
Die bessere Formulierung ist, die "geteilte" Methode in eine eigene Klasse zu legen, von der beide Views dann erben.

2022-03-03 06:39 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/imagegroup.py
> +        image = zeit.content.image.browser.form.AddForm.resize(self, image)
ok, schau ich mir später an

2022-03-04 07:32 UTC, merged

2022-03-04 07:53 UTC, thomasbaumann commented
Mir war so, als würde (das explizit auch nicht geforderte) [send_message](https://github.com/ZeitOnline/vivi/pull/296/commits/3b741cafca336be05bd0817984b727f24f2c37d7#diff-3eb7c40cc88a5c533901a89d974b9cd06bb554dde9735d826888a2053f87e4f1R55) ohne `AddForm` nicht funktionieren.