ZO-1094: Validate JSON against specific schema
ZeitOnline/vivi pull request #325
Opened 2022-05-05 07:44 UTC by louika

Dieser PR liefert die Option eine JSON Datei gegen ein spezifisches Schema zu validieren.

WIP, da ich hier noch nicht fertig bin. Speziell, wie kann das ganze Dependencies Chaos gelöst werden? und ich finde es nicht optimal, dass bei Zappi die Zugangsdaten ins Feld geschrieben werden, sodass sie im DAV stehen. Ist das berechtigt?

JENKINS_BATOU_BRANCH=ZO-1094

2022-05-05 08:29 UTC, wosc commented
run jenkins

2022-05-05 09:50 UTC, wosc commented
run jenkins

2022-05-05 09:55 UTC, wosc commented
run jenkins

2022-05-05 11:31 UTC, wosc commented
run jenkins

2022-05-05 11:42 UTC, wosc commented
run jenkins

2022-05-05 12:38 UTC, wosc requested changes
Vom Ansatz prima, im Aufschrieb gibts noch Verbesserungspotenzial. :)

2022-05-05 12:38 UTC, wosc commented on core/src/zeit/content/text/json.py
> +    zeit.cms.checkout.interfaces.IAfterCheckinEvent)
Bitte [ValidateCheckinEvent](https://github.com/ZeitOnline/vivi/blob/master/core/src/zeit/content/article/edit/body.py#L186) benutzen, genau dafür ist der da. :)

2022-05-05 12:38 UTC, wosc commented on core/src/zeit/content/text/json.py
> +        validation = zeit.content.text.interfaces.IValidationSchema(self)
Es ist ja schon extra fein ein getrennter Adapter eingeführt für die Daten zur Validierung -- der Code gehört dann auch dort hin.

2022-05-05 12:38 UTC, wosc commented on core/src/zeit/content/text/json.py
> +        if schema:
Wenn da nen http-Fehler auftritt (und geschluckt wird), kommt `None` zurück, das bricht dann schon in `schema, resolver =`.

Und ich denke, wenn da ein http-Fehler auftritt, sollte die Validierung fehlschlagen, oder was meinst Du?

2022-05-05 12:38 UTC, wosc commented on core/src/zeit/content/text/json.py
> +            log.error('%s returned %s', schema_url, status, exc_info=True)
Da wir den Fehler schlucken und weiterarbeiten können, ist `warning` der passendere Level.

2022-05-05 12:38 UTC, wosc commented on core/src/zeit/content/text/json.py
> +                schema['components']['schemas'][validation.field_name],
Wenn man sich beim `field_name` vertippt haben sollte, bricht das mit KeyError. Stattdessen sollte die Validierung (mit lesbarem Fehler) fehlschlagen.

2022-05-05 12:38 UTC, wosc commented on core/src/zeit/content/text/browser/tests/test_json.py
> +        with mock.patch('zeit.content.text.json.JSON.get_schema') as schema:
Mit `file://`-URLs ([siehe auch](https://github.com/ZeitOnline/zeit.web/blob/master/src/zeit/web/core/requests.py#L51-L52)) plus `pkg_resources` schrieben sich die Tests glaube ich deutlich schöner auf, als mit mock.patch+requests_mock...

2022-05-10 13:29 UTC, louika commented on core/src/zeit/content/text/json.py
> +    zeit.cms.checkout.interfaces.IAfterCheckinEvent)
wir haben hier eine andere Lösung gewählt.

2022-05-12 07:00 UTC, louika commented
run jenkins

2022-05-20 09:38 UTC, wosc approved these changes
![](https://i.giphy.com/media/GYlAnXsFWk4U0/giphy.gif)

2022-05-20 09:38 UTC, merged