ZO-1211: simplify cp metadata form
ZeitOnline/vivi pull request #345
Opened 2022-05-25 08:56 UTC by thomasbaumann

2022-05-25 13:10 UTC, thomasbaumann commented
run jenkins

2022-05-27 07:02 UTC, wosc requested changes
Prima! Wenn mans "andersrum" aufschreibt, wirds glaub noch etwas eleganter.

2022-05-27 07:02 UTC, wosc commented on core/src/zeit/content/cp/browser/form.py
> +            'keywords', 'year', 'volume', 'page', 'lead_candidate',
Wenn man [wie bei Linkobjekten](https://github.com/ZeitOnline/vivi/blob/master/core/src/zeit/content/link/browser/form.py#L54) die _gewünschten_ Felder in `field_groups` aufschreibt (was eh erforderlich ist für die Gruppierung), und die dann in `form_fields` programmatisch in ein `select()` kippt, muss man die Felder nur _einmal_ nennen statt zweimal, das fände ich sauberer.

2022-06-02 10:11 UTC, wosc approved these changes
Danke fürs Umbauen. Der Build-Failure war der gemeine Python-Typo `('ohne-Komma-kein-Tuple')`. Ich war dann noch so frei, die Gruppen etwas umzusortieren, damit es besser nebeneinander passt. Von mir aus passt das, aber da sich das nicht gut togglen lässt, wär mein Vorschlag, es erst zu mergen, wenn Sonja auch [zufrieden ist](https://zeit-online.atlassian.net/browse/ZO-1211?focusedCommentId=80829) (ggf vivi.devel nutzen?), damit es uns kein Production-Deployment blockiert.

2022-06-07 07:37 UTC, thomasbaumann commented
Danke @wosc! Puh, das hab ich im Vorurlaubs-Stress nicht mehr gesehen mit dem `,`... Ich bespreche das gleich mit Sonja wegen Devel.

2022-06-07 07:39 UTC, thomasbaumann commented
> an XSLT-ism

😆

2022-06-15 06:44 UTC, Hennnnes commented
Ist der hier noch geblocked, oder kann das gemerged werden? :)

2022-06-15 08:50 UTC, thomasbaumann commented
Wie vorhin im Daily besprochen und siehe https://zeit-online.atlassian.net/browse/ZO-1211?focusedCommentId=81094: Ich bin mir sehr sicher, dass Sonja das für ok befunde hat.

2022-06-15 08:57 UTC, merged