ZO-1408 publisher 3rd party
ZeitOnline/vivi pull request #359
Opened 2022-07-05 08:10 UTC by fschulze

Die ersten drei 3rd Party Plugins für den neuen Publisher. Siehe [ZO-1408](https://zeit-online.atlassian.net/browse/ZO-1408), sowie [ZO-1410](https://zeit-online.atlassian.net/browse/ZO-1410), [ZO-1411](https://zeit-online.atlassian.net/browse/ZO-1411) und [ZO-1412](https://zeit-online.atlassian.net/browse/ZO-1412)

2022-07-12 13:05 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +    CONTENT_TYPES = frozenset([
Den Content-Typ nochmal extra zu prüfen, ist überflüssig, weil ja sowieso nur Adapter für die 3 gewünschten Content-Typen registriert sind.

2022-07-12 13:06 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +    grok.context(zeit.content.article.interfaces.IArticleMetadata)
Bitte `IArticle` und `IGallery` verwenden. Streng technisch gesehen ist `IArticleMetadata` zwar auch korrekt, aber das drückt nicht so schön/klar aus, was wir eigentlich sagen wollen.

2022-07-12 13:06 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +    CONTENT_TYPES = frozenset([
dito überflüssig

2022-07-12 13:07 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +    grok.context(zeit.content.article.interfaces.IArticleMetadata)
dito `IArticle`

2022-07-12 13:09 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +            'live_url': live_url}
Ich denke, das `live-prefix` gehört in die Konfiguration des Publisher, denn der Wert ist pro Environment fest, und kann/darf/soll sich ja nicht pro Request ändern.

2022-07-12 13:10 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +        if ressort == "Administratives":
So Policy-Geschichten wie Ressort oder Product Excludes bitte konfigurierbar machen. (Ggf macht das dann auch den Testaufbau einfacher, weil man die konkreten Werte nicht erst noch extra in die globale Fixture hinzufügen muss?)

2022-07-12 13:28 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
>              'uuid': uuid.shortened,
Hmm also mein Gefühl ist, der Publisher sollte nicht 1:1 eine Payload von vivi an die Drittsysteme durchreichen (also sprich zb `type: commentsection` würde in den Publisher und nicht ins vivi gehören), das scheint mir von der Kopplung und Wissensverteilung irgendwie ungünstig. Andererseits muss natürlich vivi genau die Daten, die die Drittsysteme sehen wollen, hier aufbereiten (bei Speechbert und Bigquery wird das vmtl am deutlichsten werden), dh eine "Publisher-API" Zwischenebene zu erfinden, wäre auch irgendwie künstlich/umständlich. Hmm. Lass uns evtl nochmal drüber reden, wenn Speechbert+Bigquery dran sind?

2022-07-12 13:31 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
>              'unique_id': self.context.uniqueId,
Ob vivi dann für ungefähr jeden 3rdparty Eintrag `uuid` und `unique_id` nochmal extra übertragen soll, oder ob man sich das sparen kann/will, sehen wir vmtl erst so richtig, wenn alles da ist?

2022-07-14 07:02 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +    CONTENT_TYPES = frozenset([
Das habe ich als Absicherung dringelassen. Mir fällt sonst kein Weg ein sicherzustellen, daß die Registrierung nicht aus versehen doch für einen anderen Contenttype gilt.

2022-07-14 07:07 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +    grok.context(zeit.content.article.interfaces.IArticleMetadata)
Komisch, zu dem Zeitpunkt hatte ich für mindestens einen der Drei nur die ``I*Metadata`` Variante gefunden. Jetzt habe ich alle drei Interfaces auf anhieb gefunden 🤷

2022-07-14 07:08 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +        if ressort == "Administratives":
In Code als Konstante, oder tatsächlich in Config?

2022-07-14 07:16 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
>              'uuid': uuid.shortened,
In https://hackmd.zeit.de/KtWjvq_cTniRao3dh_rJhA schien der Konsens zu sein, daß der Publisher dumm ist und vivi den payload komplett durchgibt, inklusive Dopplungen.

2022-07-14 07:48 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +            'live_url': live_url}
Änderung hier und im publisher gepushed.

2022-07-14 12:38 UTC, fschulze commented
BigQuery dazugekommen.

2022-07-29 06:57 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +        if ressort == "Administratives":
Ist nun konfigurierbar.

2022-08-03 09:15 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +    CONTENT_TYPES = frozenset([
Ähm, naja, aber dass eine Adapter-Registrierung genau für das gilt, was man angegeben hat, ist doch exakt der Job von zope.component. Das müssen wir in der Anwendung nicht nochmal händisch nachvollziehen. :)

2022-08-03 10:44 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +        payload['url'] = ''
Das sollte vmtl der Publisher anhand der uniqueId befüllen?

2022-08-05 06:55 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +            'path': path}
Da ist wieder die Frage der Zuständigkeit. Den Pfad auf der Publisherseite aus der uniqueId zu bauen geht gegen den Ansatz, daß der Publisher dumm sein soll und nur durchreichen soll. Ich denke wir sollten da konsistent sein.

2022-08-05 06:59 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +        payload['url'] = ''
Hier bin ich mir nicht sicher. Im alten Publisher kommt die URL aus der XSLT Transformation und wird in ``update_speechbert`` nicht weiter angefasst. Allerdings könnte es sein, daß die vorher an anderer Stelle im XML gesetzt wird. Da sollte am Besten in Staging oder Produktion mal geschaut werden, was da raus kommt. Eventuell müssen wir da im neuen Publisher noch was entsprechend anpassen.

2022-08-05 12:03 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +        # TODO with Python >= 3.9 we can use:
🎉

2022-08-05 12:05 UTC, fschulze commented on core/src/zeit/workflow/tests/fixtures/speechbert.xslt
> +<?xml version="1.0" encoding="UTF-8"?>
Habe explizite Tests für fast alle Fälle hinzugefügt. Es gibt ein paar die als TODO markiert sind, wo die vorhandenen Testdaten nicht reichen, die ich aber nicht für kritisch halte und daher weggelassen habe.

2022-08-05 12:06 UTC, fschulze commented on core/src/zeit/workflow/tests/fixtures/speechbert.xslt
> +<?xml version="1.0" encoding="UTF-8"?>
Es gibt in ``test_speechbert_is_published`` ein TODO was wohl mit der Testumgebung zu tun hat. Das ``audio_speechbert`` Attribut verhält sich im Test nicht richtig.

2022-08-05 12:06 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +        if self.context.supertitle:
Habe ich vereinfacht.

2022-08-05 12:07 UTC, fschulze commented
Änderungen gepushed, es sind noch ein paar Fragen aufgetaucht, siehe individuelle Kommentare.

2022-08-10 07:44 UTC, louika commented on core/src/zeit/workflow/publish_3rdparty.py
> +            'path': path}
Evtl. sollten wir unsere Idee, dass der Publisher von nichts wissen soll nochmal überdenken. Auf der einen Seite halte ich das für eine gute Modellierung, auf der anderen Seite wollen wir evtl. auch nicht mehrmals den Body übertragen (ist das irgendwo der Fall?). Solange es sich um so kleine Dinge wie Pfad oder uniqueID handelt, finde ich Doppelungen eigentlich erstmal nicht so schlimm.

2022-08-10 08:42 UTC, louika commented on core/src/zeit/workflow/publish_3rdparty.py
> +        # TODO there is a "not(role)" check in the original XSLT
ist das Todo noch aktuell?

2022-08-10 08:44 UTC, louika commented on core/src/zeit/workflow/publish_3rdparty.py
> +                'https://img.zeit.de/').rstrip('/') + '/wide__820x461__desktop'
das ist ziemlich spezifisch. ich glaube, wir haben nicht nur die eine Bildauflösung, spannende Frage, warum die? wirklich nur die eine? ich geh mal suchen, was hier der Hintergrund ist.

2022-08-10 08:47 UTC, louika commented on core/src/zeit/workflow/publish_3rdparty.py
> +            "(//division/* | //division/ul/*)")
ich spreche nochmal mit Rose, ob in Speechbert wirklich nur die unstrukturierten Listen in dieser Form hinzugefügt werden. Es gibt nämlich definitiv auch strukturierte Listen 🤔

2022-08-10 09:03 UTC, fschulze commented on core/src/zeit/workflow/publish_3rdparty.py
> +        # TODO there is a "not(role)" check in the original XSLT
Ja, allerdings gibt es diesen Fall beim Test-Content nicht. Müsste mal auf Staging oder Production geschaut werden

2022-08-10 09:33 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +    def test_speechbert_payload_no_publish_date(self):
ab hier folgen, soweit ich es verstanden habe, unittests für `publish_3rdparty.py`. Weiter oben sind auch noch ein paar. Wollen wir diese in ihr eigenes Skript isolieren? E.g. `test_publish_3rdparty.py`? Damit vermeiden wir, dass `test_publish.py` sehr lang wird und verdeutlichen, wofür die Tests zuständig sind.

2022-08-10 09:35 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +    def test_speechbert_payload_no_genre(self):
`test_publish_3rdparty.py`? Anfrage weiter unten

2022-08-10 09:36 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +        assert 'image' not in payload
`test_publish_3rdparty.py`? Anfrage weiter unten

2022-08-10 09:36 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +        assert 'lastModified' not in payload
`test_publish_3rdparty.py`? Anfrage weiter unten

2022-08-10 09:50 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +    def test_speechbert_ignore_genres(self):
ab hier folgen, soweit ich es verstanden habe, unittests für `publish_3rdparty.py`. Weiter oben sind auch noch ein paar. Wollen wir diese in ihr eigenes Skript isolieren? E.g. `test_publish_3rdparty.py`? Damit vermeiden wir, dass `test_publish.py` sehr lang wird und verdeutlichen, wofür die Tests zuständig sind. Evtl. lassen sich auch ein paar Tests vereinfachen. Das wird wird glaube ich fast überall gesetzt:
```
self.monkeypatch.setattr(
  zeit.workflow.publish_3rdparty.Speechbert,
  'ignore',
  lambda s, d: False)
```

wenn ich mir das genau überlege gilt das eigentlich für alle Tests in denen nur die payload geprüft wird,  also kein `IPublish.published = True`

2022-08-10 10:19 UTC, fschulze commented on core/src/zeit/workflow/tests/test_publish.py
> +    def test_speechbert_ignore_genres(self):
Durch die Verwendung von TestCase Klassen kann man leider schlecht pytest.mark.parametrize verwenden, sonst wäre es deutlich weniger Code für die Tests. Man könnte das in eine eigene Datei auslagern, aber so viel ist es auch nicht. Kann man auch immer noch machen und git macht das dann trotzdem leicht nachverfolgbar.

2022-08-10 12:45 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +        data_factory = zeit.workflow.publish_3rdparty.Speechbert(article)
das lässt sich eigentlich schön über Adapter ausdrücken:
```
speechbert = zope.component.getAdapter(
    article,
    zeit.workflow.interfaces.IPublisherData,
    name='speechbert')
speechbert.json()
config['speechbert-ignore-genres'] = ''
speechbert = zope.component.getAdapter(
    article,
    zeit.workflow.interfaces.IPublisherData,
    name='speechbert')
speechbert.json() is not None
True
```
so würde man sich die `XYZ_adapters_are_registered` Tests sparen.

2022-08-10 12:47 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +    def test_speechbert_ignore_genres(self):
durch die neuen Tests hat sich die Länge von `test_publish.py` schon verdoppelt. Ich finde das rechtfertigt eine neue Datei.

2022-08-10 14:24 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +        assert 'uuid' not in payload
bei den Tests lässt sich noch einiges vereinfachen. ich denke aber, dass können wir im Anschluss machen, wenn dieser PR ganz durch ist.

2022-08-10 14:28 UTC, louika reviewed
Ich lauf nochmal los und erkundige mich bzgl. Bilder und Speechbert und melde mich dann. 
Ich denke Refactoring der Tests kann man im Nachgang machen. Sodass alles ein bischen kürzer und kompakter wird. Ansonsten denke ich, kann das raus :)

2022-08-10 14:45 UTC, louika commented
Bzgl. Speechbert bekomme ich von Rose nochmal ein Paar real life Beispiele, dann können wir das Problem mit dem Autoren lösen und diesen Teil https://github.com/ZeitOnline/vivi/pull/359#discussion_r938747332

2022-08-10 15:06 UTC, louika commented on core/src/zeit/workflow/publish_3rdparty.py
> +                'https://img.zeit.de/').rstrip('/') + '/wide__820x461__desktop'
joa, also das soll wohl so 🤔 habe mich bei Rose erkundigt

2022-08-10 15:32 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +            assert result_sb['payload']['hasAudio'] is True
ok? wollen wir uns das nochmal ansehen? ich bin nicht sicher, ob ich das richtig verstanden habe.

2022-08-11 13:52 UTC, fschulze commented
Habe die Tests in eine eigene Datei geschoben. Ausserdem habe ich jetzt doch die Duplizierung von uniqueId und UUID entfernt.

2022-08-12 12:39 UTC, louika commented on core/src/zeit/cms/repository/cache.txt
> + '2022': 'http://xml.zeit.de/online/2022/'}
diese beiden Anpassungen fehlen auch in Zeile 22 und 27.

2022-08-12 12:41 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +import zeit.workflow.publish_3rdparty
wenn es hier keine neuen Tests gibt, brauchen wir vermutlich auch die neuen Imports nicht 🤞

2022-08-12 13:20 UTC, louika requested changes

2022-08-12 13:20 UTC, louika commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +            # assert 'hasAudio' not in result_sb['payload']
ich denke, das ist zu erwarten, da der Artikel ja in Zeile 227 veröffentlicht wurde. Während des Veröffentlichens wird nun der neue Publisher genutzt und entsprechend ist danach `audio_speechbert == True`.
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/workflow/tests/test_publish_3rdparty.py(226)test_speechbert_is_published()
-> response = rmock.post(
(Pdb) l
221  	        IPublishInfo(article).urgent = True
222  	        self.assertFalse(IPublishInfo(article).published)
223  	        assert article.audio_speechbert is None
224  	        with requests_mock.Mocker() as rmock:
225  	            breakpoint()
226  ->	            response = rmock.post(
227  	                'http://localhost:8060/test/publish', status_code=200)
228  	            IPublish(article).publish(background=False)
229  	            (result,) = response.last_request.json()
230  	            result_sb = result['speechbert']
231  	            self.assertEqual(
(Pdb) ICMSContent('http://xml.zeit.de/online/2007/01/Somalia').audio_speechbert
(Pdb) ICMSContent('http://xml.zeit.de/online/2007/01/Somalia').has_audio
False
(Pdb) n
> /Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/workflow/tests/test_publish_3rdparty.py(227)test_speechbert_is_published()
-> 'http://localhost:8060/test/publish', status_code=200)
(Pdb) n
> /Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/workflow/tests/test_publish_3rdparty.py(226)test_speechbert_is_published()
-> response = rmock.post(
(Pdb) n
> /Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/workflow/tests/test_publish_3rdparty.py(228)test_speechbert_is_published()
-> IPublish(article).publish(background=False)
(Pdb) n
> /Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/workflow/tests/test_publish_3rdparty.py(229)test_speechbert_is_published()
-> (result,) = response.last_request.json()
(Pdb) ICMSContent('http://xml.zeit.de/online/2007/01/Somalia').audio_speechbert
True
(Pdb) ICMSContent('http://xml.zeit.de/online/2007/01/Somalia').has_audio
False
```

2022-08-12 13:20 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +import zeit.workflow.interfaces
noch einer 🙈

2022-08-12 13:29 UTC, fschulze commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +            # assert 'hasAudio' not in result_sb['payload']
Der Test prüft aber den Payload der an Speechbert geschickt wird, da sollte das noch nicht gesetzt sein, da es ja erst gepublished werden soll.

2022-08-12 13:32 UTC, fschulze commented on core/src/zeit/workflow/tests/test_publish.py
> +import zeit.workflow.interfaces
Noch einer was? Wird doch verwendet.

2022-08-12 13:33 UTC, louika commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +            # assert 'hasAudio' not in result_sb['payload']
dann muss der Aufruf `IPublish(article).publish(background=False)` entfernt werden, denn das ist ja genau der Publish-Vorgang

2022-08-12 13:36 UTC, fschulze commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +            # assert 'hasAudio' not in result_sb['payload']
Wie gesagt, ich teste das was während des Publishens an den Speechbert geschickt wird, sprich da hat der Speechbert bis dahin noch nichts bekommen. Ausserdem läuft während der Tests der neue Publisher ja nicht, sprich es wird nichts an Speechbert geschickt. Es muss also irgendwo ein Mock sein der das macht.

2022-08-12 14:08 UTC, louika commented on core/src/zeit/workflow/tests/test_publish.py
> +import zeit.workflow.interfaces
Tatsache, dann wurde nur ein fehlender Import nachgeholt. Hatte mich gewundert, weil sich an der Datei sonst nichts geändert hat.

2022-08-12 14:13 UTC, fschulze commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +            # assert 'hasAudio' not in result_sb['payload']
Es kommt über ``apply_default_values`` von hier:
https://github.com/ZeitOnline/vivi/blob/master/core/src/zeit/content/article/interfaces.py#L56

Ich glaube ich habe das Feld missverstanden. Ich vermute jetzt, daß es dazu da ist bei bestimmten Artikeln falls gewünscht den Speechbert abzuschalten. Nicht ob der Speechbert schon gelaufen ist.

2022-08-12 14:19 UTC, louika commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +            # assert 'hasAudio' not in result_sb['payload']
das kann gut sein, aber das würde nicht erklären, warum es vor dem Veröffentlichen `None` ist und hinterher `True` denn im Quelltext vom Testartikel ist das Attribut nicht gesetzt.

2022-08-12 14:22 UTC, louika commented on core/src/zeit/workflow/publish_3rdparty.py
> +        # TODO there is a "not(role)" check in the original XSLT
ist erledigt

2022-08-15 07:44 UTC, merged