ZO-1583: ARD Tagesschau Video Module
ZeitOnline/vivi pull request #391
Opened 2022-10-13 16:02 UTC by thomasbaumann

2022-10-14 09:50 UTC, louika commented
das sieht auf den ersten Blick erstmal gut aus, ich würde die ARD Box  gern lokal testen, dafür fehlt mir ein Eintrag in der Product-Config:
```
  File "/Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/content/article/edit/videotagesschau.py", line 182, in from_product_config
    config['tagesschau-api-url-post'],
KeyError: 'tagesschau-api-url-post'
```

2022-10-14 09:56 UTC, thomasbaumann commented
Ja, https://github.com/ZeitOnline/vivi-deployment/pull/365 muss erst gemerged werden (gab's nur als Commit, nicht als PR, wie ich fälschlicherweise annahm)

Die Indents... ich hatte neulich irgendwo gehört, dass wir hanging indents lieber mögen, deshalb habe ich die Warnung, die bei mir auch angezeigt wurde, ignoriert.

2022-10-18 10:01 UTC, louika commented
beim click auf video-recommendations siehts aus, als würde ein Fallback fehlen? 

```
2022-10-18 11:58:51,809 ERROR SiteError http://localhost:8080/workingcopy/zope.manager/test-ard-empfehlung-2/editable-body/id-844c47d8-5f2f-4349-8467-b933a92e7291/@@edit-videotagesschau
Traceback (most recent call last):
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 146, in publish
    result = publication.callObject(request, obj)
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/app/publication/zopepublication.py", line 202, in callObject
    return mapply(ob, request.getPositionalArguments(), request)
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 119, in mapply
    return debug_call(obj, args)
   - __traceback_info__: <security proxied zope.browserpage.metaconfigure.VideoTagesschau instance at 0x10f49c460>
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 126, in debug_call
    return obj(*args)
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 896, in __call__
    self.update()
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 877, in update
    result = action.success(data)
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 661, in success
    return self.success_handler(self.form, self, data)
  File "/Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/content/article/edit/browser/edit.py", line 325, in handle_update
    for recom in api.request_videos(article)['recommendations']:
TypeError: 'NoneType' object is not subscriptable
```

2022-10-18 11:47 UTC, louika commented
also, wenn ich einen Body habe, dann passiert einfach nichts, es wird ein Rad angezeigt und das verschwindet nach ner Weile.

2022-10-18 11:52 UTC, louika commented on core/src/zeit/content/article/edit/browser/tests/test_videotagesschau.py
> +class Form(zeit.content.article.edit.browser.testing.BrowserTestCase):
prima Browsertests 👍 gibt es auch Unittests? Oder gibt es einen triftigen Grund dagegen? Absprache mit Wolfgang, oder so?

2022-10-18 12:40 UTC, louika commented
`changelog` Eintrag?

2022-10-18 12:44 UTC, thomasbaumann commented on core/src/zeit/content/article/edit/browser/tests/test_videotagesschau.py
> +class Form(zeit.content.article.edit.browser.testing.BrowserTestCase):
Die Tests, die mir erstmal noch fehlten, sind jetzt gepushed

2022-10-18 13:40 UTC, louika commented
```
2022-10-18 15:40:15,245 ERROR zeit.content.article.edit.videotagesschau GET Tagesschau video ard empfehlungen [{urn:uuid:4476fea8-4c98-4a56-80ee-c6e622b2f4e7}]: Expecting value: line 1 column 1 (char 0)
2022-10-18 15:40:15,249 ERROR SiteError http://localhost:8080/workingcopy/zope.manager/test-ard-empfehlung-2/editable-body/id-70694cdc-fd12-467e-be5a-f3d2820a0918/@@edit-videotagesschau
Traceback (most recent call last):
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 146, in publish
    result = publication.callObject(request, obj)
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/app/publication/zopepublication.py", line 202, in callObject
    return mapply(ob, request.getPositionalArguments(), request)
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 119, in mapply
    return debug_call(obj, args)
   - __traceback_info__: <security proxied zope.browserpage.metaconfigure.VideoTagesschau instance at 0x112862830>
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 126, in debug_call
    return obj(*args)
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 896, in __call__
    self.update()
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 877, in update
    result = action.success(data)
  File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 661, in success
    return self.success_handler(self.form, self, data)
  File "/Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/content/article/edit/browser/edit.py", line 325, in handle_update
    for recom in api.request_videos(article)['recommendations']:
TypeError: 'NoneType' object is not subscriptable
```

habe grade nochmal gepullt und deployed. Leider besteht das Problem noch. @thomasbaumann ?

2022-10-18 13:56 UTC, louika commented on core/src/zeit/content/article/edit/videotagesschau.py
> +                      f'[{payload["article_custom_id"]}]: {e}')
ist das hier Zeilen 78-85 eine komplette Kopie von Zeilen 50-61? Wenn ja, bitte in eine Funktion auslagern und nur einmal aufrufen. Finde grade keinen Unterschied, bin evtl. etwas betriebsblind. Andernfalls, was ist der Unterschied?

2022-10-18 13:58 UTC, thomasbaumann commented on core/src/zeit/content/article/edit/videotagesschau.py
> +                      f'[{payload["article_custom_id"]}]: {e}')
> ```
> 2022-10-18 15:40:15,245 ERROR zeit.content.article.edit.videotagesschau GET Tagesschau video ard empfehlungen [{urn:uuid:4476fea8-4c98-4a56-80ee-c6e622b2f4e7}]: Expecting value: line 1 column 1 (char 0)
> 2022-10-18 15:40:15,249 ERROR SiteError http://localhost:8080/workingcopy/zope.manager/test-ard-empfehlung-2/editable-body/id-70694cdc-fd12-467e-be5a-f3d2820a0918/@@edit-videotagesschau
> Traceback (most recent call last):
>   File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 146, in publish
>     result = publication.callObject(request, obj)
>   File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/app/publication/zopepublication.py", line 202, in callObject
>     return mapply(ob, request.getPositionalArguments(), request)
>   File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 119, in mapply
>     return debug_call(obj, args)
>    - __traceback_info__: <security proxied zope.browserpage.metaconfigure.VideoTagesschau instance at 0x112862830>
>   File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/publisher/publish.py", line 126, in debug_call
>     return obj(*args)
>   File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 896, in __call__
>     self.update()
>   File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 877, in update
>     result = action.success(data)
>   File "/Users/huelsen/Projects/vivi-deployment/work/app/lib/python3.10/site-packages/zope/formlib/form.py", line 661, in success
>     return self.success_handler(self.form, self, data)
>   File "/Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/content/article/edit/browser/edit.py", line 325, in handle_update
>     for recom in api.request_videos(article)['recommendations']:
> TypeError: 'NoneType' object is not subscriptable
> ```
> 
> habe grade nochmal gepullt und deployed. Leider besteht das Problem noch. @thomasbaumann ?

sry, ich hab das oben nicht gesehen. Passiert bei mir ebenfalls. 👀

2022-10-18 14:03 UTC, thomasbaumann commented on core/src/zeit/content/article/edit/videotagesschau.py
> +                      f'[{payload["article_custom_id"]}]: {e}')
> ist das hier Zeilen 78-85 eine komplette Kopie von Zeilen 50-61? Wenn ja, bitte in eine Funktion auslagern und nur einmal aufrufen. Finde grade keinen Unterschied, bin evtl. etwas betriebsblind. Andernfalls, was ist der Unterschied?

Das ist nicht fürchterlich elegant, aber: Es soll erst kurz angefragt werden, ob es für den Hash schon Empfehlungen gibt. Falls ja, dann returnen und das darunter nicht mehr ausführen.

```
            if rget.status_code == 200:
                log.info(f'Found tagesschauvideo for {article.title} '
                         f'[{payload["article_custom_id"]}]')
                return rget.json()
```

2022-10-18 14:24 UTC, louika commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            self.xml.remove(node)
Verständnisfrage: warum gibt es Videoeintrag, die erst entfernt werden müssen? Und was wenn ein weiteres Video in dem Artikel vorhanden ist? Das wird doch augenscheinlich auch entfernt, oder verstehe ich das falsch?

2022-10-18 14:25 UTC, thomasbaumann commented on core/src/zeit/content/article/edit/videotagesschau.py
> +                      f'[{payload["article_custom_id"]}]: {e}')
Ja. Zumal das mit dem letzten Commit noch ähnlicher geworden ist.

2022-10-18 14:40 UTC, louika commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            return {"recommendations": []}
passt 👍 [Fehler](https://github.com/ZeitOnline/vivi/pull/391#issuecomment-1282405862) ist weg

2022-10-18 14:49 UTC, louika commented on core/src/zeit/content/article/edit/interfaces.py
> +            (value.title, value.type, value.video_url_hd, _('open video')))
Comment: funktioniert, sieht für mich aber nach einer tollen Möglichkeit fürs Nutzen von f-Strings aus. Bin nur nicht sicher, ob f-Strings für die Übersetzung auch funktioniert

2022-10-18 15:50 UTC, louika commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            return {"recommendations": []}
ah oki, na denn

2022-10-18 16:00 UTC, louika commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            self.xml.remove(node)
oki, sieht aus, als wärs nur das xml vom eigenen Block 
```
(Pdb) self
    <zeit.content.article.edit.videotagesschau.VideoTagesschau b'http://block.vivi.zeit.de/http://xml.zeit.de/politik/2022-10/test-ard-error#editable-body/id-c61b80e0-4789-4a39-bf30-91abc27cda6e'>
```

2022-10-18 16:02 UTC, louika approved these changes
Heute übern Tag sind schon einige Verbesserungen eingeflossen. Ich denke, dass passt jetzt. Tests müssen noch durchlaufen. Morgen kann ich dann hoffentlich mergen 😄

2022-10-19 06:18 UTC, wosc commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            self.xml.remove(node)
* `self.xml` ist der XML-Knoten, der zu dem Modul gehört
* Die Methode ist "set" für das Feld "videos" (Plural/mengenwertig), dh "was auch immer da vorher war, ersetze es durch den übergebenen Wert"

2022-10-19 07:28 UTC, louika commented
@thomasbaumann schaust du mal nach den Tests, bitte?

2022-10-19 07:55 UTC, thomasbaumann commented
Ja, schon gesehen...

2022-10-19 07:58 UTC, louika requested changes
was ist denn jetzt mit den Tests los?

2022-10-19 08:00 UTC, thomasbaumann commented
Also ich kriege sehr viele Fehler wie vivi/core/src/zeit/content/cp/tests/test_rule.py::RuleTest::test_feature_is_a_region ERROR.

2022-10-20 08:53 UTC, louika commented
Ok, ich habs jetzt einmal lokal funktionieren gesehen 👍 und zwar mit https://vivi.staging.zeit.de/repository/sinn/2022-10/das-ist-mein-dateiname/@@view.html 
bitte nochmal die Log-Message ändern, sodass er nur `found` sagt, wenn er auch wirklich ein video gefunden hat. Für den initialen 404 evtl. noch schreiben, dass der erwartet wird, weil der Text der ARD-KI neu ist.

2022-10-20 11:48 UTC, louika commented
Stand jetzt: uns fehlt der Mock weiterhin

2022-10-20 13:58 UTC, louika commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            self.xml.remove(node)
danke fürs Erklären :)

2022-10-20 14:52 UTC, thomasbaumann commented
Poah... sry [wegen](https://github.com/ZeitOnline/vivi/pull/391/commits/6080b8c8176f68f2d5897031d3d58bd51af3f161)

2022-10-20 15:00 UTC, thomasbaumann commented
> Ok, ich habs jetzt einmal lokal funktionieren gesehen 👍 und zwar mit https://vivi.staging.zeit.de/repository/sinn/2022-10/das-ist-mein-dateiname/@@view.html bitte nochmal die Log-Message ändern, sodass er nur `found` sagt, wenn er auch wirklich ein video gefunden hat. Für den initialen 404 evtl. noch schreiben, dass der erwartet wird, weil der Text der ARD-KI neu ist.

Fall wer mitliest: Ich habe im Ticket (ich weiß nicht, ob das Doku-würdig ist) zu [beschreiben versucht, dass es nicht so ganz selbstverstädnlich ist, (eine) echte Empfehlung(en) zu bekommen [(https://zeit-online.atlassian.net/browse/ZO-1583?focusedCommentId=83017), die mehr ist als eine 200er-Antwort.

2022-10-20 15:59 UTC, thomasbaumann commented
> [ZO-1583: Reuse code instead of copying it](https://github.com/ZeitOnline/vivi/pull/391/commits/6aee61155562979a0e2ae48f9ca52ec355615e60)
Wollte mir ursprünglich offenhalten, für dieses Modul mehr als nur `<p>`s rauzuholen, was ich dann aber zugegebnermaßen nicht mehr gemacht habe. Könnte man `getSearchableText` nicht eigentlich um ein `'xpath'`-Argument erweitern?
> [ZO-1583: Remove CORS, probably copy&paste from JS](https://github.com/ZeitOnline/vivi/pull/391/commits/f258f90d1a8692d5142343432fa8d19b59599f36)
genau... c&p
> [MAINT: Remove unused parameter](https://github.com/ZeitOnline/vivi/pull/391/commits/523781e70d8fccb6e2aa73b499d05f88de6d5729)
Hatte ich vorsorglich drin, falls wer sagt, `sleep` sollte besser durch Retries ersetzt werden...

2022-10-21 06:42 UTC, merged