ZO-2552: Das wichtigste in Kuerze
ZeitOnline/vivi pull request #416
Opened 2023-02-27 16:26 UTC by louika

Dieser PR fügt den neuen Contenttyp Markup hinzu. Hierbei handelt es sich um ein Modul, dessen Textfeld Inhalt in Markdown konvertiert wird. Es gibt die Möglichkeit einen oder mehrere Autoren zu verlinken und einen Titel. 

 - [ ] Übersetzung aktualisieren
 - [ ] von Sonja ein eigenes Markup Icon einfügen, das jetzige ist ein Platzhalter
 - [ ] sinnvolle `assert` statements im Browsertest

![miau](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWFjZTdmMTJiYWE2YmE0NmZlYTg3NTQ2ZjkzZGIxZWY0ZDZkNWJiZSZjdD1n/rho9L4MsYXaec/giphy.gif)

2023-02-28 09:29 UTC, louika commented
die `flake8` Fehler sind beseitigt, ich noch den Browser Test an.

2023-02-28 12:37 UTC, louika commented
Sonja sagt, das Icon kommt heute im Laufe des Tages 🧊

2023-02-28 13:25 UTC, wosc requested changes
Jo prima. Allerdings ist fürchte ich vor lauter Boilerplate untergegangen, dass das Objekt _Markup_ enthalten soll. 😁

2023-02-28 13:25 UTC, wosc commented on core/src/zeit/content/markup/browser/form.py
> +    form_fields = zope.formlib.form.FormFields(
Das steht schon genau so in der `Base` drin, muss man nicht wiederholen.

2023-02-28 13:25 UTC, wosc commented on core/src/zeit/content/markup/browser/form.py
> +        self.widgets['text'].height = 50
Das ist aktuell ein noop, weil irgendwo im CSS `textarea { height: 4em }` vergraben ist, seufz. Vmtl muss man sich [an diesen Hack dranhängen](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/cms/browser/resources/forms.css#L561)? (Da kann das `height` dann aber genauso entfallen AFAIU ;)

2023-02-28 13:25 UTC, wosc commented on core/src/zeit/content/markup/browser/form.py
> +class Display(Base, zeit.cms.browser.form.DisplayForm):
Es fehlt uns noch ein `MarkdownDisplayWidget`; aktuell wird das rohe HTML (inkl Tags und alles) rausgegeben. (Beim CP-Modul mogeln wir uns drum rum, weil die Lese-Ansicht dort [eigene Views](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/content/cp/browser/blocks/layout.markup.content.pt#L1) sind und keine Forms.)

Kann man sich dann noch überlegen, ob man dafür das Markdown (mit Syntax-Highlighting, wir haben eh schon [pygments am Start](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/cms/content/browser/widget.py#L54)) oder das HTML in gerendert(!) anzeigen will. (Auch dafür ist der Test bisher zu naiv, weil er keinerlei Markup beinhaltet...)

2023-02-28 13:25 UTC, wosc commented on core/src/zeit/content/markup/browser/form.py
> +    form_fields['text'].custom_widget = zeit.cms.browser.widget.MarkdownWidget
Allmählich lohnt es sich dann glaub ich, ein eigenes zope.schema-Feld zu beerben, damit man das Widget automagisch [per Adapter](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/cms/browser/widget.zcml#L264-L278) dafür registrieren kann, und nicht immer manuell im Form dran rumpunken muss. (Zumal wenn gleich noch die Display-Variante dazukommt)

Und (dass uns das noch nie aufgefallen ist??!) man sollte dem Ding dringend mal [heading_style='ATX'](https://pypi.org/project/markdownify/#options) beibringen, damit er das als `# my heading` und nicht mit `====` unterstrichen darstellt (*schauder).

2023-02-28 13:40 UTC, louika commented
ja aber, ja aber, da war doch mal markdown drin O.o siehe [slack](https://zeitonline.slack.com/archives/C02V10ZR38T/p1677252375952499) und das hat ganz automatisch formatiert O.o

2023-02-28 16:00 UTC, louika commented on core/src/zeit/content/markup/browser/form.py
> +        self.widgets['text'].height = 50
habs rausgeschmissen

2023-03-01 09:56 UTC, louika commented
und das ist auch soweit noch alles gut, siehe unten, das ist der eingecheckte Quelltext. man siehts nur im Display nicht, gute Idee da einen Syntax Highlighter einzubauen, und/oder das html in gerendet
```
  <body>
    <title>foo</title>
    <text>
      <h1>Hello I am a heading</h1>
      <p>me is a paragrpah
with more content in it</p>
      <ul>
        <li>entry one</li>
        <li>entry two</li>
      </ul>
      <p>cheese is very tasty, good bye</p>
    </text>
  </body>
  ```

2023-03-02 11:00 UTC, louika commented on core/src/zeit/content/markup/browser/form.py
> +class Display(Base, zeit.cms.browser.form.DisplayForm):
wir haben uns für WYSIWYG entschieden, ensprechend wird das html gerendered und nicht mehr escaped.

2023-03-03 09:19 UTC, merged