Zo 2555 zo 2649 report images metainfos
ZeitOnline/vivi pull request #418
Opened 2023-03-03 17:56 UTC by thomasbaumann

2023-03-06 08:41 UTC, thomasbaumann commented
run jenkins

2023-03-07 06:23 UTC, thomasbaumann commented
on hold: Übersetzungen noch nicht gemacht!

2023-03-14 13:58 UTC, wosc requested changes

2023-03-14 13:58 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +                    {"match": {"doc_type": "image-group"}},
Das kan beides auch unter `filter` als `"term"`, das ist effizienter.

2023-03-14 13:58 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +                    {"match": {"payload.image.single_purchase": "yes"}}],
Das wird Richtung TMS eigentlich(tm) nach bool konvertiert, und müsste hier daher `True` heißen, würde ich denken.

2023-03-14 13:58 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +                writer.writerow([val for val in row])
Die Comprehension ist überflüssig :)

2023-03-14 13:58 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +        finally:
Falls eine Exception auftreten sollte, ist es auch vollends egal, ob man den StringIO noch sauber schließt oder nicht. Ich denke das ganze `try` kann schlicht entfallen.

2023-03-14 13:58 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +            datetime.timedelta(days=days_ago)).strftime(
Elastic kann auch selber [Date-Math](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math), dh man kann ihm direkt sowas wie `"gte": "now-40d/d"` sagen.

2023-03-14 13:58 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +                master_image = imgr_metadata.context.master_image
`imgr_metadata.context == imgr_content` ;)

2023-03-14 13:58 UTC, wosc commented on core/src/zeit/content/image/browser/tests/test_purchase_report.py
> +class SinglePurchaseProperty(zeit.content.image.testing.FunctionalTestCase):
Den Test find ich zu low-level, als dass er interessant/relevant wäre. _Bestenfalls_ könnte man einem bestehenden Browser-Test eine Assertion hinzufügen, dass das Feld existiert.

2023-03-14 13:58 UTC, wosc commented on core/src/zeit/content/image/browser/tests/test_purchase_report.py
> + "payload": {"document": {"copyrights": "<pickle>
Das ist ziemlich zerbrechlich, das json hier manuell reinzutackern. Ich würde eher entweder sowas vorschlagen

```python
group = create_image_group_with_master_image()
elastic.search.return_value = zeit.cms.interfaces.Result([zeit.retresco.interfaces.ITMSRepresentation(group)])
```

Oder den View-Code aufteilen in eine "suche" und eine "mach csv draus" Methode, und für die Tests die "suche" patchen, und direkt Liste von ICMSContent zurückgeben -- dass ITMSContent sich gleich verhält, könnte/dürfte man hier als gegeben hinnehmen. (So würde _ich_ es vmtl machen, und in Kauf nehmen, dass falls ich einen katastrophalen Syntaxfehler in die Such-Methode reinbaue, ich den in den Tests nicht merke, sondern nur beim lokal einmal ausprobieren. Aber such dir aus, was dir mehr einleuchtet.)

2023-03-14 14:53 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/imagegroup.py
> +                writer.writerow([val for val in row])
Haha... so ist das mit Copy&Paste...

2023-03-14 14:54 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/imagegroup.py
> +            datetime.timedelta(days=days_ago)).strftime(
👍

2023-03-14 14:55 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/tests/test_purchase_report.py
> +class SinglePurchaseProperty(zeit.content.image.testing.FunctionalTestCase):
ok, ich hatte irgendwie vernommen, Browsertests eher zweite Wahl weil langsamer...

2023-03-15 08:41 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/imagegroup.py
> +                    {"match": {"payload.image.single_purchase": "yes"}}],
Also `{"match": {"payload.image.single_purchase": True}}`? Damit kriege ich zwar keinen Fehler, aber auch nicht die erwarteten Hits...

2023-03-15 09:03 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +                    {"match": {"payload.image.single_purchase": "yes"}}],
Da diese Property erst in diesem PR eingeführt wird, wäre meine Frage, woher es im TMS überhaupt Daten dazu geben könnte? Hattest du von lokal extra welche indiziert?

2023-03-15 12:58 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/imagegroup.py
> +                    {"match": {"payload.image.single_purchase": "yes"}}],
vlt verstehe ich die Frage falsch(?), aber ich hatte testweise Inhalte auf Staging mit dem Merkmal versehen.

2023-03-15 13:01 UTC, wosc commented on core/src/zeit/content/image/browser/imagegroup.py
> +                    {"match": {"payload.image.single_purchase": "yes"}}],
Jo, die Frage ist, wie genau das vonstatten gegangen ist. Die von mir angesprochene Typkonvertierung kann (natürlich) nur dann passieren, wenn das TMS-Indizieren von einem vivi-Codestand durchgeführt wird, der die Property kennt. (Denn woher soll er sonst wissen, dass das ein Bool ist)

2023-03-15 13:06 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/tests/test_purchase_report.py
> + "payload": {"document": {"copyrights": "<pickle>
Ah, den `create_image_group_with_master_image()`-Ansatz hatte ich auch (von einem anderen Test übernommen) ausprobiert; weil das irgendwie nicht klappte, hatte ich dann diese Methode. Ich versuch's nochmal :)

2023-03-15 13:20 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/imagegroup.py
> +                    {"match": {"payload.image.single_purchase": "yes"}}],
🤦‍♂️ stimmt...

2023-03-17 06:24 UTC, thomasbaumann commented on core/src/zeit/content/image/browser/tests/test_purchase_report.py
> + "payload": {"document": {"copyrights": "<pickle>
> Oder den View-Code aufteilen in eine "suche" und eine "mach csv draus" Methode, und für die Tests die "suche" patchen, und direkt Liste von ICMSContent zurückgeben (...) (So würde ich es vmtl machen

Ich hab mich mal an dieser Variante versucht (leider hat es etwas gedauert bis ich rausgefunden habe, dass man PublishInfos wie date_first_released wohl nicht einfach setzen kann sondern den Inhalt wirklich publishen muss) und hoffe, dass ich das richtig verstanden habe.

2023-03-22 17:52 UTC, thomasbaumann commented
run jenkins

2023-04-14 11:20 UTC, merged