ZO-2757: uri parameter with www.zeit.de instead of path only
ZeitOnline/vivi pull request #420
Opened 2023-03-10 06:36 UTC by thomasbaumann

2023-03-14 13:31 UTC, wosc requested changes

2023-03-14 13:31 UTC, wosc commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            'article_uri': f'www.zeit.de{article_uri}'}
Hüstel. ;) Es gibt ein Setting namens `live-prefix` für diesen Zweck. (Da ist das Protkoll mit dran `https://`, falls sie das hier nicht wollen, muss mans halt `urlparse`'n)

2023-03-14 14:45 UTC, thomasbaumann commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            'article_uri': f'www.zeit.de{article_uri}'}
Ja... ich hab das sogar im Hinterkopf für die Fälle, in denen es nötig ist. Und mich dann gefragt, _ob_ es in diesem Fall nötig ist. Meines Wissens wird daraus nirgendwo ein Link gebastelt sondern es ist lediglich ein Parameter für diese KI. Und deshalb dachte ich, ich kann mich einfach streng an die Ticketvorgabe halten.

2023-03-14 14:47 UTC, wosc commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            'article_uri': f'www.zeit.de{article_uri}'}
Ahh, ach so. Jo das ergibt sinn.

2023-03-14 14:47 UTC, thomasbaumann commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            'article_uri': f'www.zeit.de{article_uri}'}
Ich lasse Rose nochmal klären, ob die mit etwas anderem als www.zeit.de mehr anfangen können oder ob das sogar eher schlechter ist.

2023-03-14 14:48 UTC, thomasbaumann commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            'article_uri': f'www.zeit.de{article_uri}'}
ok, Kommentar ergibt Sinn tatsächlich 👍

2023-03-14 15:09 UTC, thomasbaumann commented on core/src/zeit/content/article/edit/videotagesschau.py
> +            'article_uri': f'www.zeit.de{article_uri}'}
Hmm... wer (Halbsätze im Ticket) lesen kann, ist klar im Vorteil und braucht nicht zu denken:

> Also www.zeit.de einfach als Konstante davor setzen, falls die Ziel-Domain im CMS noch nicht klar ist.

Die Ziel-Domain ja mit live-prefix im bekannt. Dann nehm ich die nun _doch_.

2023-03-15 07:26 UTC, wosc approved these changes
![](https://i.giphy.com/media/jlrrZm31qblTZlGl3D/giphy.gif)

2023-03-15 07:27 UTC, merged