Z0-1992: TMS von vivi steuerbar machen
ZeitOnline/vivi pull request #434
Opened 2023-05-16 15:03 UTC by stefanholek

2023-05-22 14:52 UTC, stefanholek commented
run jenkins

2023-05-26 12:06 UTC, wosc requested changes

2023-05-26 12:06 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +            return True
Wäre vmtl hilfreich, einen Kommentar dran zu machen, wofür das gut ist. (Weil der Artikel-Body ausm TMS ausgeliefert wird wg Intextlinks soll Publish in vivi erst Vollzug melden, wenn die Änderung draußen auch sichtbar ist, _deshalb_ muss der Publisher auf Elastic warten.)

2023-05-26 12:06 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +        # on retraction
Der Kommentar ergibt sich doch direkt aus dem Funktionsnamen, oder?

2023-05-26 12:06 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +        # no payload. uuid and uniqueId are passed in automatically
Der Kommentar hat sich jetzt überholt, oder?

2023-05-26 12:06 UTC, wosc commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +    def test_tms_wait_for_index_centerpage(self):
Ein sprechender Testname wäre "alles außer Artikel wartet _nicht_"

2023-05-26 12:06 UTC, wosc commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +        cp = create_centerpage()
Und wenn man dann schon dort ist, muss man auch nicht extra eine CP anlegen, sondern kann den `/testcontent` (oder eine UnknownResource oder _sonstwas_) für diesen Test verwenden.

2023-05-26 12:06 UTC, wosc commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +        image_group = create_image_group()
Wenn wir doch schon absichtlich ein Interface einführen bzw. nutzen ("wenn aus ITMSRepresentation nichts rauskommt, ..."), können wir es uns auch sparen, ein "möglichst realistisches" Testsetup zu machen. Diese ImageGroup wird nirgends angeschaut werden, weil wir ITMSRepresentation ja (mit voller Absicht) gemockt haben.

Man muss natürlich aber kucken, ob es in zeit.retresco einen Test gibt mit so einem realistischen Setup, um zu prüfen "da kommt dann beim echten ITMSRepresentation nichts raus, dh es landet nicht im TMS"

2023-05-26 13:46 UTC, louika commented
ah juhu, es ist nicht mein PR, also bekomme ich auch keine Benachrichtigung, wenns Kommentare gibt 🪦

2023-05-30 09:15 UTC, louika commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +        image_group = create_image_group()
in `zeit.retresco` gibt es den [Test](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/retresco/tests/test_convert.py#L357-L364) der mit einem realistischen Testsetup prüft, dass News Bildergruppen kein `ITMSRepresentation` mitbringen. Ich nehme hier dann entsprechend wieder `testcontent`.

2023-05-30 09:47 UTC, louika commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +    def setUp(self):
ich habe die TMSTests so vereinfacht, dass sie auf dem `zeit.workflow.testing.FunctionalTestCase` basieren und das neue `TMSMockLayer` nutzen. So gibt es keine direkte Abhängigkeit nach `zeit.content.article` mehr.

2023-05-30 11:26 UTC, stollero approved these changes
Tests sind grün, dann stimmt es wohl 🤞 .

Dokumentation ist natürlich ein offener Punkt 😉 und man könnte statt `if` auch direkt ein `return` machen, aber das ist wohl Geschmackssache.

2023-05-30 11:45 UTC, merged