ZO-2483: option ignore 3rd party publishing
ZeitOnline/vivi pull request #437
Opened 2023-06-05 14:47 UTC by thomasbaumann

Erstmal schauen, ob der richtige Ansatz.

Einen Aufruf stelle ich mir so vor: https://github.com/ZeitOnline/vivi-deployment/commit/a9d438f36eb97e3a141265689056e10a37ff7f35

2023-06-07 08:06 UTC, louika requested changes
Grundsätzlich denke ich, dass dies der richtige Weg ist um bei unseren "manuellen" Massenveröffentlichungen bestimmte Komponenten auszuschließen. 

Allgemein, hier fehlt die Retract-Variante, da `_execute_task` für beides genutzt wird. Gestern waren die Tests grün, ich bin nicht sicher, was jetzt hier der Stand ist.

2023-06-08 15:41 UTC, thomasbaumann commented
run jenkins

2023-06-13 12:21 UTC, louika requested changes
Ich habe mir den PR angesehen, bitte entschuldige die späte Rückmeldung, und habe einige Anmerkungen:

- mir ist nicht klar, ob dieser PR vollständig ist. Aus dem Ticket geht hervor, dass die Funktionalität sowohl für Devs, als auch für POs/PMs zur Verfügung stehen soll. Letzteres fehlt hier vollständig. Eine Diskussion diesbezüglich konnte ich nicht finden. Bleibt es bei nur Devs, wäre ein Adapter evtl. overkill.
- eine leere Liste zu initialisieren ist ein Anti-Pattern, dass ggf. unerwünschte Nebeneffekte haben kann, siehe beispielsweise hier: https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html, bitte anpassen
- die Funktionalität ist eventuell in den `IPublisherData` Adaptern besser aufgehoben, da es sich um eine Ausnahme von der Regel handelt
- muss es sich beim ignore überhaupt um eine Liste handeln, oder wollen wir eigentlich immer das selbe Set an 3rdParty Systemen ausschließen? Wie werden die Einträge dann validiert, nicht dass jemand spaßeshalber `bigquery` reinschreibt und Team-Data dann Daten fehlen.
- in `zeit.cms.workflow.interfaces.IPublish` ist beschrieben, dass die Keywordarguments für die Celerytasks genutzt werden. Das sind der `PUBLISH_TASK` und der `RETRACT_TASK`. Dort befindet sich momentan die Logik für die `ignore_3rd_party` Funktionalität. Daher denke ich, dass man sie nutzen kann und das Argument nicht komplett durch den gesamten Publish-Vorgang durchreichen muss. So vermeidet man auch die Anpassung von Tests, die damit nichts am Hut haben, siehe `brightcove` und `timebased`
- möglicherweise ließe sich das über einen Adapter realisieren, der die 3rd Party Systeme kennt und die man während einer Massenveröffentlichung belegen kann. `IThirdParty.speechbert, IThirdParty.facebooknewstab` und so weiter. Dann ist das für alle Fälle None, es sei denn, jemand hat sie vorher belegt und gespeichert. Das ließe sich ggf. auch einfacher ins UI übernehmen. Diese Logik gehört dann allerdings in den jeweiligen Adapter und nicht in den `PublishRetractTask`
- eine andere Variante wäre dem `PublishRetractTask` beim Initialisieren ein `ignore` mitzugeben, dann greift man später nurnoch auf das `self.ignore_3rd_party` zu und muss eigentlich garnichts durchreichen

2023-06-13 12:33 UTC, thomasbaumann commented
Die/den Punkte/n, die ich nicht erwähne, schaue ich mir an / stimme ich zu.

> muss es sich beim ignore überhaupt um eine Liste handeln, oder wollen wir eigentlich immer das selbe Set an 3rdParty Systemen ausschließen? Wie werden die Einträge dann validiert, nicht dass jemand spaßeshalber bigquery reinschreibt und Team-Data dann Daten fehlen.

Ich spreche aus meiner Praxis heraus: Ich wollte schon manchmal gerne Speechbert oder Facebook oder beide ausschließen. Aber wenn das allgemein nicht so gesehen wird, dann gerne auch ein festes Set.

> in zeit.cms.workflow.interfaces.IPublish ist beschrieben, dass die Keywordarguments für die Celerytasks (...)

Ah schade, über diese Sache (Durchschleifen verhindern, andere Ansätze) wollte ich ja mal vorher geredet haben...

2023-06-13 12:35 UTC, louika commented
vorher drüber reden, wäre super gewesen, leider ist uns der Publisher mit den TMS Problemen dazwischen gekommen.

2023-06-13 15:03 UTC, louika commented
Ein Beispiel für einen Adapter, den man entsprechend setzten kann, wäre `ICachingTime`

2023-06-20 11:51 UTC, wosc reviewed
Wenn man es ganz streng nimmt, wäre es wohl an sich korrekt, den ignore-Parameter der `publish/retract`-Methode hinzuzufügen, so wie hier skizziert. Von mir aus _könnten_ wir das so tun, aber ich finde, wir könnten uns das Leben auch etwas einfacher machen. :)

(Wenn ich es richtig verstehe, ist der hauptsächliche Usecase ja, dass im [publish_content.py](https://github.com/ZeitOnline/vivi-deployment/blob/main/components/zope/tools/publish_content.py)-Skript gewisse Tasks nicht aufgerufen werden. Dafür müssten wir die Ignore-Liste nicht _unbedingt_ pro einzelnem publish-Aufruf einstellbar machen, sondern könnten sie ggf auch etwas globaler einstellen. Oder entgeht mir grade was?)

Mein erster Gedanke war insofern, im `publish_content.py` schlicht die Adapter zu deregistrieren (so machen wirs [für Pushnachrichten etc](https://github.com/ZeitOnline/vivi-deployment/blob/main/components/zope/tools/publish_content.py#L35) ja zb auch). Das fände ich grundsätzlich akzeptabel, ist aber natürlich etwas häkelig (und schlecht zu testen).

Die nächst-einfachste Variante wäre vmtl so was in dieser Richtung:

```diff
--- a/core/src/zeit/workflow/publish.py
+++ b/core/src/zeit/workflow/publish.py
-        json = [cls._format_json(obj, method) for obj in to_process_list]
+        json = [zeit.workflow.interfaces.IPublisherData(obj)(method)
+                for obj in to_process_list]
         response = requests.post(
             url=url, json=json, headers=headers)
         timer.mark('Called Publisher HTTP API: %s' % method)
diff --git a/core/src/zeit/workflow/publish_3rdparty.py b/core/src/zeit/workflow/publish_3rdparty.py
index a1b7f8b2d..4638986b7 100644
--- a/core/src/zeit/workflow/publish_3rdparty.py
+++ b/core/src/zeit/workflow/publish_3rdparty.py
@@ -17,6 +17,27 @@ import zeit.workflow.interfaces
+@grok.implementer(zeit.workflow.interfaces.IPublisherData)
+class PublisherData(grok.Adapter):
+    grok.context(zeit.cms.interfaces.ICMSContent)
+
+    ignore = ()  # extension point e.g. for bulk publish scripts
+
+    def __call__(self, action):
+        uuid = zeit.cms.content.interfaces.IUUID(self.context)
+        result = {'uuid': uuid.shortened, 'uniqueId': self.context.uniqueId}
+        for name, adapter in zope.component.getAdapters(
+                (self.context,), zeit.workflow.interfaces.IPublisherData):
+            if not name:  # ourselves
+                continue
+            if name in self.ignore:
+                continue
+            data = getattr(adapter, f'{action}_json')()
+            if data is not None:
+                result[name] = data
+        return result
```

Das wäre dann eine "globale Variable", die man in `publish_content.py` halt entsprechend setzen könnte:

```python
zeit.workflow.publish_3rdparty.PublisherData.ignore = ['speechbert', 'facebooknewstab']
```

Also, ich hab tatsächlich keine _starke_ Meinung an der Stelle. Ich persönlich würd es mir/uns nicht antun, den Parameter überall durchzuschleifen, sondern eher ne globale Variable in Kauf nehmen. Aber macht wie Ihr denkt. :)

2023-06-23 11:37 UTC, thomasbaumann commented
> den Parameter überall durchzuschleifen, sondern eher ne globale Variable in Kauf nehmen. Aber macht wie Ihr denkt. :)

Ja, ich hatte vor dem PR schon (in Dailys) angedeutet, dass ich mit dem Durchschleifen nicht sehr glücklich bin. Das ist zwar ebenfalls keine starke Meinung, aber gerade deshalb bin ich ja offen für anderen Meinungen, die zu einer Vereinfachung führen :) Danke :)

Bei "globale Variable" hatte ich ebenfalls ein paar Bedenken, aber s.o. - und das ist ja eine Vereinfachung.

Bleibt noch Louisas Einwand, ob
> Als PO/PM/Dev möchte ich steuern können
bedeutet, dass es auch aus Vivi heraus gesteuert werden können soll... 

Ich bau das mal so ein :)

2023-06-28 09:08 UTC, thomasbaumann commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +@grok.implementer(zeit.workflow.interfaces.IPublisherData)
ähm... woher kommt das denn jetzt? Ja, ich hatte das erst falsch, aber lokal ist es längst raus 🙄

2023-06-28 09:13 UTC, thomasbaumann commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +@grok.implementer(zeit.workflow.interfaces.IPublisherData)
Ah, _hier_ steht "Outdated". Alles klar.

2023-06-28 11:18 UTC, thomasbaumann commented
> * mir ist nicht klar, ob dieser PR vollständig ist. Aus dem Ticket geht hervor, dass die Funktionalität sowohl für Devs, als auch für POs/PMs zur Verfügung stehen soll.

[geklärt, dass es kein Vivi-UI geben muss](https://zeit-online.atlassian.net/browse/ZO-2483?focusedCommentId=90323)

2023-06-28 12:16 UTC, louika commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +@grok.implementer(zeit.workflow.interfaces.IPublisherData)
wie meinen? ich kann dir grade nicht folgen.

2023-06-30 08:17 UTC, wosc approved these changes
![](https://i.giphy.com/media/mTRpdks4k5sgo/giphy.gif)

2023-06-30 08:17 UTC, merged