ZO-2808: preview for markup in vivi
ZeitOnline/vivi pull request #447
Opened 2023-06-16 08:27 UTC by stollero

2023-06-21 10:35 UTC, wosc requested changes

2023-06-21 10:35 UTC, wosc commented on core/src/zeit/content/markup/browser/markup_metadata.pt
> +      tal:content="context/title">
Also ja, könnte man so machen, mit separatem `metadata_preview` View für das Markup-Objekt, machen wir für andere Contentobjekte ja auch. Aber es wär glaub ich allgemeingültiger, im View für `ICommonMetadata` auch die Fallbacks teaserTitle/title etc. mit reinzunehmen.

2023-06-21 10:35 UTC, wosc commented on core/src/zeit/content/cp/browser/blocks/teaser.py
> +    def make_text_entry(metadata, css_class, name=None, fallback=None):
👍

2023-06-21 10:52 UTC, stollero commented on core/src/zeit/content/markup/browser/markup_metadata.pt
> +      tal:content="context/title">
Schau ich gleich nochmal nach. Danke 👍

2023-06-22 11:40 UTC, wosc approved these changes
![](https://i.giphy.com/media/pldlTsJkifRYY/giphy.gif)

2023-06-22 11:41 UTC, merged