ZO-3701: Simplecast tab
ZeitOnline/vivi pull request #480
Opened 2023-08-22 12:41 UTC by louika

Nach Rebase nun wieder auf dem aktuellen Stand, aber mit dem selben Problem wie vorher:
- lokal kann ich den Button in dem neuen Tab klicken, aber der Browser Tests findet ihn nicht
- gehört der Connector nach `zeit.
<img width="1429" alt="Screenshot 2023-09-06 at 17 09 54" src="https://github.com/ZeitOnline/vivi/assets/20401272/4e44c741-2396-4744-85c7-1b2b6c90505a">
content.audio.browser` oder nach `zeit.simplecast`

2023-09-06 15:47 UTC, louika commented
ne also irgendwas ist hier noch absolut verdreht 😞 ich mach mal Feierabend für heute

2023-09-07 09:01 UTC, wosc requested changes

2023-09-07 09:01 UTC, wosc commented on core/src/zeit/content/audio/browser/simplecast.pt
> +<form method="GET" action="@@simplecast-request">
* GET sollte nichts modifizieren, das passende Verb ist POST
* Es hat sich (mind in vivi) eingebürgert, dieselbe URL für GET und POST zu verwenden
* Der View müsste sich glaub ich viel einfacher als formlib-Form aufschreiben lassen, statt mit nem Custom Template und Krams.

2023-09-07 09:42 UTC, louika commented on core/src/zeit/simplecast/connection.py
> +class Connector(grok.Adapter):
🖖 auf los gehts los 🏃‍♀️

2023-09-07 12:08 UTC, louika commented on core/src/zeit/simplecast/connection.py
> +class Connector(grok.Adapter):
warum gibt es das Objekt? Weil es vor dem Webhook existiert hat.

2023-11-22 08:48 UTC, louika commented
abgelöst durch [Eintrag im Rädchenmenü](https://zeit-online.atlassian.net/browse/ZO-3830)

2023-11-22 08:48 UTC, closed without merging