ZO-3708
ZeitOnline/vivi pull request #487
Opened 2023-08-28 14:20 UTC by stollero

- [ ] 📰  Review Slides
- [ ] 📝  Tests
- [ ] 🧹  Cleanup commits
- [ ] 📖 Documentation

2023-08-29 09:48 UTC, stollero commented on core/src/zeit/push/interfaces.py
> +class ToggleDependentText(zope.schema.Text):
Ist das der richtige Ort ?

2023-08-30 07:40 UTC, wosc requested changes
Erst nachdem ich alles zuende gelesen und bekommentiert habe, ist mir aufgefallen, dass wir das vmtl leider anders bauen sollten/müssen, mit einer Invariante statt DependentField...

2023-08-30 07:40 UTC, wosc commented on core/src/zeit/content/article/edit/body.py
> +        zeit.push.interfaces.IAccountData,
Jau prima, ich denke auch, das ist genau die richtige Stelle, um diese Prüfung reinzuhängen.

2023-08-30 07:40 UTC, wosc commented on core/src/zeit/push/facebook.py
> -        if not text:  # BBB
Fair enough, das ist definitiv jahrealt genug, um nicht mehr relevant zu sein.

2023-08-30 07:40 UTC, wosc commented on core/src/zeit/push/interfaces.py
> +class ToggleDependentText(zope.schema.Text):
Fürs erste würde ich sagen: jau! Erst wenn es zukünftig noch mehr Stellen gibt, wo wir diese Mechanik brauchen, würde ich es dann nach `zeit.cms` rausziehen zur Wiederverwendung.

2023-08-30 07:40 UTC, wosc commented on core/src/zeit/push/interfaces.py
> +    dependent_field = None
Ein `ToggleDependentField` _ohne_ Dependent-Field Angabe ist nicht sinnvoll, oder? Insofern sollten wir den Parameter im init als required behandeln.

2023-08-30 07:40 UTC, wosc commented on core/src/zeit/push/interfaces.py
> +        super(ToggleDependentText, self).__init__(**kw)
In py3 kann+soll man kürzer nur `super().__init__(...)` schreiben

2023-08-30 07:40 UTC, wosc commented on core/src/zeit/push/interfaces.py
> +        self.dependent_field = dependent_field
Das ist ein bisschen eine Stilfrage, aber ich find es einleuchtender, dass man immer _zuerst_ super-init aufruft, und erst danach seine eigenen Sachen macht (es sei denn natürlich, es geht genau drum, vor dem super-init noch was anzupassen ;)

2023-08-30 07:40 UTC, wosc commented on core/src/zeit/push/interfaces.py
> +        title=_('Enable Facebook'), required=False)
Ich glaub nicht, dass bei `Bool` der Wert von `required` überhaupt irgendwo einen Unterschied im Verhalten bewirkt (oder steh ich grad auf dem Schlauch?). Insofern würd ich mir den Stress nicht geben, sondern schlicht den Default stehenlassen. ;)

2023-08-30 07:40 UTC, wosc commented on core/src/zeit/push/interfaces.py
> +            raise zope.schema.interfaces.RequiredMissing(self.__name__)
Der Kernhaken an der ganzen Geschichte ist fürchte ich, dass `zeit.push.browser.form.SocialBase.setUpWidgets()` das gleiche Verhalten ("wenn Haken, dann required") bereits umsetzt, aber halt auf der View-Ebene, was uns für die Domain-Ebene nicht hilft -- und aber umgekehrt, so wie das `ToggleDependent` grade gebaut ist, hilft es uns für die View-Ebene nicht.

Bzw anders gesagt, das Design von zope.schema erlaubt fürchte ich Constraints über Felder hinweg nur so, indem man sie auf dem Interface [global deklariert](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/content/cp/interfaces.py#L409-L410) (denn auf einem Feld kann man im allgemeinen eigtl immer nur über den Wert dieses Feldes reden, und über sonst nichts)

2023-08-30 17:08 UTC, stollero commented on core/src/zeit/push/interfaces.py
> +        self.dependent_field = dependent_field
Vollkommen richtig, da passiert nichts was es rechtfertigen würde.

2023-08-31 07:37 UTC, wosc approved these changes
![](https://i.giphy.com/media/kBNacfEgENH2Hon6hc/giphy.gif)

2023-08-31 07:37 UTC, merged