ZO-3775: Correct podcasts folder
ZeitOnline/vivi pull request #494
Opened 2023-09-01 13:17 UTC by louika

Use correct folder to save podcast episodes to storage, via simplecast webhook. 

[x] Tests
[x] Doku
[x] Test instructions

Ich habe angefangen [Doku](https://docs.zeit.de/vivi/implementation/simplecast.html) zu schreiben, aber da ist bestimmt noch viel Luft nach oben.

Testen
-------

Tests laufen lassen 
```
$ bin/test vivi/core/src/zeit/simplecast
$ bin/test vivi/core/src/zeit/content/audio
```

oder manuell den Webhook triggern, wie das geht, steht gleich in der Doku. Anschließend prüfen, ob die Episode im richtigen Ordner gelandet ist.

2023-09-01 13:53 UTC, louika commented
hab gegen flake8 verloren, E501, irgendwie hatte ich im Kopf wir hätten `tests_*` und `testing.py` davon ausgenommen, aber scheinbar lieg ich da falsch.

2023-09-04 07:12 UTC, wosc requested changes

2023-09-04 07:12 UTC, wosc commented on core/src/zeit/simplecast/interfaces.py
> +    def folder(self, episode_create_at):
Ist das Public API, also sollte jemand, der `getUtility(ISimplecast)` sagt, das aufrufen wollen? Ich glaub ja nein --> dann hats auch im Interface nichts zu suchen. (Mal abgesehen davon, dass die konkrete Funktion eh durch `IAddLocation` zu ersetzen ist ;)

2023-09-04 07:12 UTC, wosc commented on core/src/zeit/simplecast/testing.py
> +        self.connector = zope.component.getUtility(
Also die zeit.cms TestCases haben schon `self.repository`, insofern wärs evtl einfacher, hier `self.repository.connector` zu verwenden?

2023-09-04 12:29 UTC, louika commented on core/src/zeit/simplecast/connection.py
> +    def folder(self, episode_create_at):
In Simplecast ist es grade so aufgeschrieben, dass man die Folder hat und dann das Audio Objekt hinzufügt, in `IAddLocation` und in Brightcove ist es anders herum. Dann dreh ich mal alles auf Links.

2023-09-04 13:59 UTC, louika commented on core/src/zeit/simplecast/connection.py
> +    def folder(self, episode_create_at):
soo jetzt hab ich einmal alles umgedreht 😵

2023-09-05 11:20 UTC, louika commented
habe mit @wosc gesprochen und entschieden, dass der Umbau auf `IAddLocation` zu einem späteren Zeitpunkt durchgeführt wird.

2023-09-05 11:45 UTC, louika commented
ich habe zwei fehlgeschlagene Tests mit Facebook
```
=========================== short test summary info ============================
FAILED vivi/core/src/zeit/push/tests/test_facebook.py::FacebookTest::test_errors_should_raise
FAILED vivi/core/src/zeit/push/tests/test_facebook.py::FacebookTest::test_send_posts_status
```
das hat mit bereits fehlender Config für Facebook zu tun? Damit haben wir hier nix zu tun. @wosc ? ich merge das mal.

2023-09-05 11:46 UTC, merged