ZO-3438: ensure id for opentelemetry has type str
ZeitOnline/vivi pull request #498
Opened 2023-09-05 13:37 UTC by thomasbaumann

It is a UUID but I think it's enough. Opentelemetry expects a str (or other simple types)

2023-09-05 13:58 UTC, stollero requested changes
Danke Hippo 🙏 Nur 2 Kleinigkeiten

2023-09-05 13:58 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +                        'db.operation': 'upload', 'id': props.id,
`__delitem__` hat das gleiche Problem :) Da müssten wir auch sehr wahrscheinlich auf `props.id` setzen

2023-09-05 13:58 UTC, stollero commented on core/src/zeit/connector/tests/test_postgresql.py
> +            self.assertEqual(b'mybody', blob.download_as_bytes())
Ein Test für ein Traceeintrag ist glaube nicht notwendig. Die Funktionalität der Anwendung ist durch den Fehler ja nicht beeinträchtigt.

Passt auch nicht wirklich dann in diese Testfunktion. :)

2023-09-05 15:10 UTC, thomasbaumann commented on core/src/zeit/connector/tests/test_postgresql.py
> +            self.assertEqual(b'mybody', blob.download_as_bytes())
ok, mach ich wieder raus

2023-09-05 15:15 UTC, thomasbaumann commented on core/src/zeit/connector/postgresql.py
> +                        'db.operation': 'upload', 'id': props.id,
done

2023-09-05 15:16 UTC, thomasbaumann commented on core/src/zeit/connector/tests/test_postgresql.py
> +            self.assertEqual(b'mybody', blob.download_as_bytes())
done

2023-09-06 05:14 UTC, stollero approved these changes
👍

2023-09-06 06:25 UTC, merged