Zo-3744: Simplecast to celery
ZeitOnline/vivi pull request #499
Opened 2023-09-05 15:41 UTC by louika

Habe mich in einem Rebase verwickelt und daher einen neue Branch erstellt. Erstmal als Draft.

2023-09-05 15:45 UTC, louika commented
run jenkins

2023-09-06 08:17 UTC, wosc requested changes

2023-09-06 08:17 UTC, wosc commented on core/src/zeit/simplecast/json/webhook.py
> +def SIMPLECAST_WEBHOOK_TASK(body):
Wenn ich das richtig sehe, sind die Parameter, die benötigt werden, die `episode_id` und der `event` -- dann sollte man auch nur genau diese übergeben, und nicht ein ganzes dict inkl message und whatnot, das aber alles eh niemanden interessiert (aber trotzdem von celery serialisiert und in redis geschrieben etc.pp. werden muss).

2023-09-06 08:17 UTC, wosc commented on core/src/zeit/simplecast/json/webhook.py
> +    if body.get('event') == 'episode_created':
Ein nachgelagertes Thema (also soll/muss nicht in diesen PR rein) ist: a) das sollten vmtl 3 einzelne Funktionen sein für die Lesbarkeit und b) wir sollten einmal überlegen, ob wir das nicht auch wie bei Brightcove aufbauen wollen, und gar nicht den übermittelten `event` anschauen, sondern
* wenn es im CMS kein Audioobjekt mit der ID gibt, ist es wohl ein add
* wenn die Simplecast-API für die ID nix mehr rausgibt, ist es wohl ein delete (wobei man hier argumentieren kann, den API-Call kann man sich sparen, wenn man doch den Event anschaut... nunja)
* ansonsten update

2023-09-06 08:17 UTC, wosc commented on core/src/zeit/simplecast/json/webhook.py
> +            celery.result.EagerResult('eager', result, celery.states.SUCCESS)
Interessiert das Result irgendjemanden? Aus dem Task kommt noch gar nichts raus, und das execute_task gibt auch nix zurück -- will sagen, ich glaub das kann man sich schlicht sparen. In den Tests ist per Default [eager mode](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/cms/testing.py#L77) eingestellt, dh die Celery-Tasks werden automatisch direkt synchron ausgeführt, dafür muss der Code nichts extra tun.

2023-09-06 08:19 UTC, louika commented on core/src/zeit/simplecast/json/webhook.py
>              log.info('No episode processed.')
kann gut sein, ich prüfe das

2023-09-06 08:20 UTC, louika commented on core/src/zeit/simplecast/json/webhook.py
> +def SIMPLECAST_WEBHOOK_TASK(body):
bereinige ich

2023-09-06 08:38 UTC, louika commented on core/src/zeit/simplecast/json/webhook.py
> +            body, queue='simplecast', background=self.background)
done

2023-09-06 08:45 UTC, louika commented on core/src/zeit/simplecast/json/webhook.py
> +            celery.result.EagerResult('eager', result, celery.states.SUCCESS)
habe einmal alles entschlackt

2023-09-06 09:10 UTC, louika commented
ich habe die gewünschen Anpassungen umgesetzt, mit Ausnahme der Umstrukturierung des Celery Tasks. Bin lokal aber grade noch am testen.

2023-09-06 09:28 UTC, louika commented
@wosc lokal habe ich jetzt die Events `episode_created` und `episode_updated` im celery task funktionieren sehen. ich habe den webhook manuell mit den jeweiligen Events getriggert und in simplecast einmal den Titel der Episode angepasst, um das Update verifizieren zu können

2023-09-06 09:29 UTC, louika commented on core/src/zeit/simplecast/json/webhook.py
> +    if body.get('event') == 'episode_created':
da hast du vollkommen recht, würde ich aber gern nachgelagert behandeln. Erstmal endlich auf staging funktionieren sehen 🤞

2023-09-06 10:31 UTC, merged