ZO-3771: Improve Audio to Podcast relationship
ZeitOnline/vivi pull request #509
Opened 2023-09-18 12:40 UTC by stollero

2023-09-20 09:58 UTC, wosc reviewed
Die grundsätzlichen Ideen find ich hervorragend und einleuchtend. Ich habe eine Menge unsortierte Detailanmerkungen; die inhaltlich wichtigste ist "summary+notes gehören nicht in die Properties sondern ins XML".

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/cms/content/podcasts.xml
> +<?xml version="1.0"?>
Die Datei gehört nach sowas wie zeit/content/audio/tests/fixtures, jedenfalls aber nicht zeit.cms

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/audio.py
> +        return f"<Audio {self.external_id}> {self.title}"
Das sollte überflüssig sein, denn die external_id steht ja in der uniqueId drin (die im [Standard-Repr](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/cms/repository/repository.py#L50) bereits mit rauskommt).

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/interfaces.py
> +            for channel in channels:
Das geht kürzer als dict comprehension: `channels = {x.get('id'): x.get('href') for x in node.iterchildren('distribution_channel')}`

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/interfaces.py
> +    default_filename = 'podcasts.xml'
Das sagst du genau richtig, diese Datei muss in vivi angelegt werden (production+staging).

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/interfaces.py
> +        required=True,
Wir brauchen wohl mal nen Styleguide, wa? `required=True` ist der Default, das schreiben wir sonst _meistens_ meine ich daher nicht explizit dazu.

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/audio.py
> +            'summary',
summary und notes können vmtl "eine gewisse Menge" Text enthalten, das sollten wir daher nicht in den Properties speichern, sondern im XML. (Dazu muss man im init vmtl sowas machen wie `self.xml = xml`, damit man auf dem Adapter dann die XML-basierten Descriptors wie `ObjectPathProperty` verwenden kann.)

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/tests/test_audio.py
> +  <podcasts>
Das ist überflüssig, denn es dupliziert nur die `podcasts.xml`, oder? Stattdessen kann man in z.c.audio.testing einen Product-Config-Layer reinmachen, der diese Fixture-Datei anzieht (vgl zb https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/content/author/testing.py#L12), dann funktioniert die Source "einfach so von selber"

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/simplecast/connection.py
> +        # XXX should we prefer zeit.podcast?
Product-Config Abschnitte heißen nach dem Python-Paket, zu dem sie gehören. Und das Paket hier heißt zeit.simplecast, weil es die Anbindung Simplecast darstellt. Ich denke das ist richtig so.

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/audio.py
> -def add_audio(container, info):
Das leuchtet mir wie gesagt sehr ein, diese wenigen "generischen" Zeilen in den zeit.simplecast Import-Code zu verschieben. 👍

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/simplecast/connection.py
> +    def _update_properties(self, episode_data, audio):
Wenn du Lust hast, könnte man das sogar noch einen Schritt weiter generalisieren (aber also, kein bisschen zwingend):

```python
_properties = {
    IAudio: {
        'url': 'audio_file_url',
        # ...
    },
    IPodcastEpisodeInfo: {
        # ...
    }
}

for iface, properties in self._properties.items():
    obj = iface(audio)
    for vivi, simplecast in properties.items():
        setattr(obj, vivi, data[simplecast])
```

(Wenn wir nicht absichtlich den Simplecast-Kram aus z.c.audio raushalten würden, könnte man die Simplecast-Namen sogar auf die Interface-Felder als taggedValue draufschreiben ;)

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/simplecast/json/webhook.py
> +        if not FEATURE_TOGGLES.find('simplecast_webhook'):
Sehr richtig. Genau für sowas sind die Toggles ja da.

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/simplecast/json/webhook.py
> +    match event:
Schick.

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/simplecast/connection.py
> +        'notes': 'long_description',
Dass die Zuordnung von `podcast` hier noch fehlt, ist klar, gell? Ich schreibs sicherheitshalber trotzdem einmal hin. (Die XML-Source braucht dafür vmtl ein `find_by_external_id` o.ä., diese Source-APIs sind leider so bisschen [gruschtelig](https://docs.zeit.de/vivi/zope/sources.html#methoden-hinzufugen))

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/interfaces.py
> +    values = collections.OrderedDict([
OrderedDict ist seit der... 3.6 oder sowas überflüssig, weil schon normale dicts die Insertion-Order garantieren.

2023-09-20 09:58 UTC, wosc commented on core/src/zeit/content/audio/interfaces.py
> +    name = "audio"
Puh. Also gefühlt würde ich sagen, ist der vivi-Code bisher >90% single quotes. Wir werden vmtl irgendwann auch hier mal Black bekommen (der double quotes enforced), aber bis dahin...

2023-09-20 10:10 UTC, stollero commented on core/src/zeit/content/audio/interfaces.py
> +            for channel in channels:
Auch immer so eine Sache des Leseflusses. So eine Comprehension bricht immer so ein wenig das Prinzip von Links nach Rechts und Oben nach Unten.

Aber in diesem Fall voll in Ordnung. Vielleicht könnten wir auch mal 100 Zeichen erlauben 🤔, dann passt es wirklich mal in eine Zeile 😁.

2023-09-20 10:54 UTC, stollero commented on core/src/zeit/content/audio/interfaces.py
> +        required=True,
So ein flake8 Plugin für uns wäre doch perfekt :)

2023-09-20 10:57 UTC, stollero commented on core/src/zeit/content/audio/interfaces.py
> +    name = "audio"
Das passiert mir ständig, früher war alles mit `"`. War dann eh autoformatiert und dann achtet man da kaum noch drauf.

Genau wie du sagst, später mit black haben wir das Problem nicht mehr.

2023-09-20 13:56 UTC, stollero commented on core/src/zeit/simplecast/connection.py
> +        'notes': 'long_description',
Implementiert, gewundert das es seltsam funktioniert und dann gesehen das ja `ObjectSource` bereits die Funktionalität beinhaltet 🤦 . Aber dafür habe ich es mal gesehen und weiß das `ObjectSource` das schon kann.

2023-09-20 14:20 UTC, wosc commented on core/src/zeit/content/audio/tests/test_audio.py
> -    def test_audio_has_properties(self):
Haben wir jetzt irgendwo einen Happy-Path Test, dass man alle Properties reinschreiben kann, und wenn man das CMS-Objekt neu lädt, sie dann noch da sind? Das muss nicht unbedingt isoliert hier in z.c.audio sein, von mir aus kann man das auch gut in zeit.simplecast mit durchchecken, aber wenn wir nirgends anschauen, dass zb notes/summary gespeichert wird, hab ich die Befürchtung, dass uns da was durch die Lappen geht früher oder später.

2023-09-20 14:20 UTC, wosc commented on core/src/zeit/simplecast/connection.py
> +                episode_data['podcast']['id'])
Hierfür fehlt auch ein Test glaube ich, jedenfalls ist das hier inkorrekt: `find()` schlägt nämlich die vivi-seitige ID nach, nicht die simplecast-seitige, dh das würde aktuell nie etwas finden. (_Und_ die canned response simplecast Antwort in EPISODE_200 lügt gerade, da steht grade ne `1` drin, und tut so als seis ne vivi-id. Nebenbei, ein vivi-realistischerer Wert für die vivi-IDs wäre vmtl eher sowas wie `was-jetzt`, oder?)

2023-09-22 06:42 UTC, wosc requested changes

2023-09-22 06:42 UTC, wosc commented on core/src/zeit/content/audio/interfaces.py
> +    @zope.interface.implementer(zeit.cms.content.sources.IObjectSource)
Das implements ist hier überflüssig, denn das erben wir mit.

2023-09-22 06:42 UTC, wosc commented on core/src/zeit/simplecast/testing.py
> +        "id": "1",
Das passt nicht mit der podcasts.xml Fixture zusammen, müsste  `external_id=1234` sein -- was auch heißt, hier fehlt ein Test, dass der Import den Podcast korrekt nachschlägt.

2023-09-22 06:42 UTC, wosc commented on core/src/zeit/content/audio/tests/fixtures/podcasts.xml
> +    <podcast id="1" title="Cat Jokes Pawdcast" external_id="1234" subtitle="A podcast of cat jokes">
Was denken wir denn, wie wir in echt die `id` vergeben? Ich tendiere eher zu was sprechendem (`was-jetzt`, `cat-jokes`) als was synthetischem. Dann wärs glaub ich hilfreich, auch die Fixture in dem Stil zu gestalten.

2023-09-22 07:29 UTC, wosc approved these changes
![](https://i.giphy.com/media/jVSKt4k9rZft4AovAl/giphy.gif)

2023-09-22 08:17 UTC, merged