ZO-3822: publish audio objects with new workflog
ZeitOnline/vivi pull request #514
Opened 2023-09-22 12:58 UTC by stollero

- [ ] Tests
- [ ] Review Slides
- [ ] Translations
- [ ] Docs
- [ ] Changelog
- [ ] Feature Toggles
- [ ] Cleanup Commits
- [ ] Resolve XXX Comments

2023-09-22 12:59 UTC, stollero commented on .vscode/settings.json
Datei löschen 😵‍💫

2023-09-22 12:59 UTC, stollero commented on core/src/zeit/content/audio/interfaces.py
> +    is_published = zope.schema.Bool(
Alternative ist nach Status zu schauen, was Sinn macht wenn es mehr als 2 Status gibt. 🤔

2023-09-22 13:01 UTC, stollero commented on core/src/zeit/workflow/configure.zcml
> +  <adapter factory=".asset.PodcastAssetWorkflow"
Wäre so eine grundsätzliche Idee, je nach Audio Typ dann einen eigenen Workflow.

Wäre aber auch einfach denkbar im AudioWorkflow so in der Art

```if audio.type == 'podcast':
         if not IPodcastEpisodeInfo(audio).is_published:
             return No Publish for YOU!!!!
```

2023-09-25 07:02 UTC, wosc requested changes

2023-09-25 07:05 UTC, stollero commented on core/src/zeit/simplecast/testing.py
> +    "is_published": True,
Existiert tatsächlich, habe es nochmal überprüft.

2023-09-26 07:43 UTC, stollero commented on core/src/zeit/simplecast/connection.py
> +            'is_published': 'is_published',
Simplecast `is_published` existiert 👍

2023-09-26 12:56 UTC, wosc approved these changes
Passt grundsätzlich!

2023-09-26 12:56 UTC, wosc commented on core/src/zeit/content/audio/workflow.py
> +@zope.interface.implementer(zeit.workflow.interfaces.IAssetWorkflow)
_Ganz_ genau genommen stimmt das so nicht, denn das ist ja eben nicht "der" AssetWorkflow, sondern ein eigener. Damit es im UI wieder passt, ist der aktuelle Weg wohl, das nochmal [extra dazuzusagen](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/content/dynamicfolder/browser/configure.zcml#L40).

(Auf den ersten Blick würde ich ja sagen, das müsste doch auch einfacher gehen, indem man die Forms auf das jeweilige Workflow-Interface registriert, anstatt auf ein _zusätzliches_ `IWorkflowForm`. Aber das führt glaube ich fürs aktuelle Thema etwas zu weit ab vom eigentlichen Pfad.)

2023-09-27 06:40 UTC, stollero commented on core/src/zeit/content/audio/workflow.py
> +@zope.interface.implementer(zeit.workflow.interfaces.IAssetWorkflow)
Ah natürlich. Ich schreibe es auf und ändere es im retract PR 👍

2023-09-27 07:44 UTC, merged