ZO-3846: show details about the audio element inside the article
ZeitOnline/vivi pull request #519
Opened 2023-10-02 12:10 UTC by stollero

- [ ] Tests
- [ ] Review Slides
- [ ] Translations
- [ ] Docs
- [ ] Changelog
- [ ] Feature Toggles
- [ ] Cleanup Commits
- [ ] Resolve XXX Comments

2023-10-05 06:47 UTC, wosc approved these changes

2023-10-05 06:47 UTC, wosc commented on core/src/zeit/content/audio/browser/details.py
> +            # XXX how do I access the translation?
Der dafür "offiziell" vorgesehene Weg ist `<div tal:content="context/audio_type" i18n:translate="">`. (Das funktioniert nämlich nicht nur für statische Werte, sondern auch für dynamisch berechnete. Ist aber, wie so manches in TAL, leider ziemlich unintuitiv.)

Der Vollständigkeit halber: man könnte grundsätzlich auch `zope.i18n.translate()` direkt aufrufen (und `self.request` übergeben, um die Zielsprache zu bestimmen), aber wenn man eh ein Template hat, wäre das unnötig umständlich.

2023-10-05 06:47 UTC, wosc commented on core/src/zeit/content/audio/browser/object-details-body.pt
> +            <div class="listing-item-key">Duration:</div>
"semantic HTML" wäre [dl/dd/dt](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl) statt divs. (Müsste man ggf. `<tal:block>` einziehen, um die Condition dranzuhängen)

2023-10-05 06:47 UTC, wosc commented on core/src/zeit/content/audio/browser/tests/test_form.py
> +    def test_audio_details_should_contain_infos(self):
Ist das nicht der gleiche Test wie `test_displays_details` weiter oben?

2023-10-05 12:28 UTC, stollero commented on core/src/zeit/content/audio/browser/tests/test_form.py
> +    def test_audio_details_should_contain_infos(self):
Ja, ist komplett identisch. Da lass ich mal den in `AudioObjectDetails`. Sind ja weniger "klicks" :)

2023-10-06 06:37 UTC, stollero commented on core/src/zeit/content/audio/browser/details.py
> +            # XXX how do I access the translation?
Funktioniert 😄 und sieht gut aus.

2023-10-06 06:38 UTC, stollero commented on core/src/zeit/content/audio/browser/object-details-body.pt
> +            <div class="listing-item-key">Duration:</div>
Danke für den Hinweis 👍

2023-10-06 07:54 UTC, wosc requested changes

2023-10-06 07:54 UTC, wosc commented on core/src/zeit/content/audio/browser/details.py
> +    def audio_type(self):
Äh na das kann doch jetzt weg, die Übersetzung findet im Template statt, da will man ja genau kein capitalize...

2023-10-06 09:51 UTC, stollero commented on core/src/zeit/content/audio/browser/details.py
> +    def audio_type(self):
🤦 natürlich

2023-10-06 10:00 UTC, merged