Minor layout fixes
ZeitOnline/vivi pull request #521
Opened 2023-10-04 10:46 UTC by stollero

---
### Remove Button

**Before**
![grafik](https://github.com/ZeitOnline/vivi/assets/121817095/0cde6996-616a-42d1-9a6b-39ebee4eda12)

**After**
![grafik](https://github.com/ZeitOnline/vivi/assets/121817095/e644eb5b-ae65-4d6e-9b60-2120c63c57af)

---
### Publish state alignment

**Before** 
![grafik](https://github.com/ZeitOnline/vivi/assets/121817095/03a6424d-b4c2-403f-a377-6304e50efa7d)
![grafik](https://github.com/ZeitOnline/vivi/assets/121817095/d26cd806-ba00-4df5-bf7a-2c44b6ee3daa)

**After** 
![grafik](https://github.com/ZeitOnline/vivi/assets/121817095/35f34ecb-82c5-4bd8-9461-6c713bcc0595)
![grafik](https://github.com/ZeitOnline/vivi/assets/121817095/496a0e71-bffe-46ed-925a-9934f1850beb)

---
### drop size increase
**Before**
![grafik](https://github.com/ZeitOnline/vivi/assets/121817095/63c6bc06-0dcf-4292-a9c4-21b0a0b6d14c)

**After**
![vivi-drop](https://github.com/ZeitOnline/vivi/assets/121817095/550fcfeb-ca45-47aa-9be3-7486f91abc61)

2023-10-04 13:32 UTC, wosc requested changes

2023-10-04 13:32 UTC, wosc commented on core/src/zeit/cms/browser/resources/cms.css
> -    background: url("./icons/icons_sprites.png") no-repeat 15px -1581px;
Das ist fürchte ich ein Vorzeichenfehler. Die Variante mit "Sprite" (nur 1 Bild einmal laden statt viele kleine immer einzeln) ist die modernere/aktuelle, wenn ich es richtig weiß. Ob das heutzutage immernoch die Best Practise ist, oder ob zb http2 das wieder umkippen würde (was wir derzeit aber noch gar nicht haben, denn der nginx auf der Ubuntu-18 VM ist zu alt und kann es nicht), weiß ich nicht, aber ehrlicherweise würd ichs daher lieber nicht anfassen.

Ich würde aber denken/hoffen, dass das was du eigentlich wolltest, nämlich horiz/vert Alignment, davon unabhängig sein müsste.

2023-10-04 13:32 UTC, wosc commented on core/src/zeit/content/article/edit/browser/resources/editor.css
> +  background: url("/fanstatic/zeit.cms/icons/icons_sprites.png") no-repeat scroll 20px -896px transparent;
Oh yeah. 🙈  Es ist allerdings noch gemeiner: diese "Asset Badges" gibts seit 599d5b1 überhaupt nicht mehr, dh diese ganzen CSS-Regeln hätte ich damals mit rauslöschen sollen.

2023-10-04 13:32 UTC, wosc commented on core/src/zeit/content/article/edit/browser/resources/editor.css
> +  transition: height 0.3s ease-in-out;
Wenn man das im Artikel ändert, sollte man das vmtl im CP-Editor analog einstellen, sonst ist das gleiche Ding an unterschiedlichen Stellen anders, und Konsistentz ist doch so eine _der_ UI/UX-Maximen, wenn ichs richtig weiß.

2023-10-04 13:32 UTC, wosc commented on core/src/zeit/cms/browser/resources/cms_widgets.css
> +  top: 5%;
Wie ich leider [neulich](https://github.com/ZeitOnline/vivi/pull/511#issuecomment-1727038155) schon feststellen musste, gibt es hier leider (mindestens) zwei konkurrierende Usecases, nämlich Bilder vs Module mit Referenzen. Und die scheinen mir allein schon rein platzmäßig leider exakt entgegengesetzt. :( Ich hatte nicht den Nerv, das auseinanderzupuzzeln; wenn es dich sehr stört bei der Audioreferenz, wirst du das leider tun müssen.

vorher
![Screenshot 2023-10-04 at 15 27 59](https://github.com/ZeitOnline/vivi/assets/577891/6c72df2a-f9bf-446a-9e9c-37964620493c)
![Screenshot 2023-10-04 at 15 28 06](https://github.com/ZeitOnline/vivi/assets/577891/5801f6aa-f988-4f8a-a680-8c867bc3f671)

nachher
![Screenshot 2023-10-04 at 15 28 14](https://github.com/ZeitOnline/vivi/assets/577891/b6b2793c-69b0-4f66-a3e9-2a77f36695f5)
![Screenshot 2023-10-04 at 15 28 20](https://github.com/ZeitOnline/vivi/assets/577891/85c18736-f3fc-4d1b-8db8-afee67ada991)

2023-10-05 12:11 UTC, stollero commented on core/src/zeit/cms/browser/resources/cms.css
> -    background: url("./icons/icons_sprites.png") no-repeat 15px -1581px;
Ach, die schönes Sprites :D ja geht auch mit Sprite. Bisschen Pixel schieben bis es passt, was es hoffentlich nun tut. 🤞

2023-10-05 12:12 UTC, stollero commented on core/src/zeit/content/article/edit/browser/resources/editor.css
> +  background: url("/fanstatic/zeit.cms/icons/icons_sprites.png") no-repeat scroll 20px -896px transparent;
Oh no, ich habe mal ein wenig mehr gelöscht. Hoffentlich nicht zu viel, wahrscheinlich immer noch zu wenig 😆

2023-10-05 12:13 UTC, stollero commented on core/src/zeit/content/article/edit/browser/resources/editor.css
> +  transition: height 0.3s ease-in-out;
Oh da war ja noch was. Centerpages immer sträflichst vernachlässigt.

2023-10-05 12:14 UTC, stollero commented on core/src/zeit/cms/browser/resources/cms_widgets.css
> +  top: 5%;
Wo sich der Button aber auch überall versteckt 😄 . Ich habe es mal überspezifiziert, das die Änderung übernommen wird, wo es vorher nicht passte.

2023-10-05 14:28 UTC, wosc approved these changes
![](https://i.giphy.com/media/Gjnpx6nps0yS4/giphy.gif)

2023-10-05 14:29 UTC, merged