ZO-3998: Check if publish dependencies can be published before publishing them
ZeitOnline/vivi pull request #531
Opened 2023-10-19 07:02 UTC by stollero

2023-10-19 07:16 UTC, wosc requested changes

2023-10-19 07:16 UTC, wosc commented on core/src/zeit/workflow/publish.py
> +        # at least check if the object can be published before
Das Problem es hierhin zu schieben, ist dass vorher schon `lock` lief, und im Fehlerfall dann kein `unlock` passiert. Ich glaube, wir sollten einen expliziten `recurse(can_publish)` Schritt einführen, _bevor_ `lock` aufgerufen wird.

2023-10-19 07:16 UTC, wosc commented on core/src/zeit/content/article/article.py
> +        return ()
Der Adapter ist immer trueish, insofern:

```suggestion
        return audios.items
```

2023-10-20 09:58 UTC, wosc requested changes

2023-10-20 09:58 UTC, wosc commented on core/src/zeit/workflow/publish.py
> +            self.log(
Da wir jetzt einen Fehler werfen (was ich durchaus korrekt finde), wird der sowieso schon ins Objectlog geschrieben, das muss man also hier nicht nochmal separat tun. Und äh blöde Frage, hast du das mal lokal ausprobiert, wie das Log dann tatsächlich aussieht? Ggf muss man an der Message, die man in die Exception steckt, noch was drehen, damit es halbwegs lesbar wird (das überblick ich grade nicht, kann auch sein, dass es schon passt).

2023-10-20 10:01 UTC, stollero commented on core/src/zeit/workflow/publish.py
> +            self.log(
Guter Punkt, ich schau mir das nochmal an.

2023-10-23 11:14 UTC, wosc approved these changes
![](https://i.giphy.com/media/2bUoq4fWe7gkUueRGG/giphy.gif)

2023-10-23 11:15 UTC, merged