ZO-1810: Remove `urn:uuid:` prefix before passing UUIDs to PostgreSQL
ZeitOnline/vivi pull request #534
Opened 2023-10-20 13:16 UTC by witsch

PostgreSQL doesn't like it, although the braces are fine. This is needed in order for https://github.com/ZeitOnline/zeit.web/pull/7089 to work.

2023-10-23 11:20 UTC, wosc requested changes
TIL wie [postgres uuid formatiert](https://www.postgresql.org/docs/16/datatype-uuid.html) 💡 

Die Testfailures gehen auf meine Kappe, musste mal main rebasen, dann sollten die sich auflösen.

Bitte in [ContractSearch](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/connector/tests/test_contract.py#L290) noch einen Test ergänzen, dass search mit `{urn:uuid:` funktioniert.

2023-10-24 11:47 UTC, witsch commented
> Bitte in [ContractSearch](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/connector/tests/test_contract.py#L290) noch einen Test ergänzen, dass search mit `{urn:uuid:` funktioniert.

On it… ⏳ Ich hatte tatsächlich als letzte Aktion, bevor ich Freitag los musste, noch ein `breakpoint()` an die Stelle gesetzt, um zu gucken, welche Tests ich denn anfassen sollte… (also nachdem sie erstmal problemlos durchliefen 🤓)
<img width="1131" alt="image" src="https://github.com/ZeitOnline/vivi/assets/62399/70cb4ea8-8483-474b-8ff1-34ddcaf8fc47">
Offline laufen lassen geht btw wohl auch nicht ganz…

2023-10-24 13:11 UTC, witsch commented
> On it… ⏳ […]

Wie quasi schon richtig vermutet hat das ein bisschen gedauert… 🤪 Aber mit db36f59458491211d24ed25780f9a828cb566b6c gibt's jetzt einen Test dazu.

2023-10-25 06:17 UTC, wosc approved these changes
![](https://i.giphy.com/media/HiyCpSO2wE6sw/giphy.gif)

2023-10-25 06:17 UTC, merged