ZO-3904: article is podcast
ZeitOnline/vivi pull request #535
Opened 2023-10-23 14:43 UTC by louika

ich muss noch rausfinden, wie ich den Reload des entsprechenden Seitenteils triggern kann.

2023-10-24 06:35 UTC, wosc requested changes

2023-10-24 06:35 UTC, wosc commented on core/src/zeit/content/article/tests/test_article.py
> +                    zeit.content.article.interfaces.IArticle,
Vorzeichenfehler ;) Es geht doch um den Event, wenn ein Audio referenziert wird (nicht um wenn jemand den Header einstellt).

2023-10-24 06:35 UTC, wosc commented on core/src/zeit/content/article/article.py
> +    header_layout = header_source.factory.getTitle(context, 'podcast')
Auf dem Objekt gespeichert wird die ID, nicht der Titel. Am einfachsten also `context.header_layout = 'podcast'`, wobei man vmtl sicherheitshalber auch noch `context.layout = 'zon-article'` dazusagen muss (denn mögliche Header hängen vom gewählten Layout ab). Und dann nen Kommentar dran "das funktioniert natürlich nur, wenn in der Konfigdatei diese Layout/Header-Kombination auch eingetragen ist".

2023-10-24 06:35 UTC, wosc commented on core/src/zeit/content/article/article.py
> +    except TypeError:
Ich behaupte mal kühn, das kann nicht fehlschlagen.

2023-10-24 06:35 UTC, wosc commented on core/src/zeit/content/article/article.py
> +    if not audio or not audio.items:
Der Adapter ist immer true-ish.

2023-10-24 07:20 UTC, louika commented on core/src/zeit/content/article/article.py
> +    except TypeError:
doch schon 😬 https://ci.zeit.de/job/vivi_PR/1972/testReport/junit/vivi.core.src.zeit.content.volume.browser.tests.test_toc/TocFunctionalTest/test_empty_page_node_in_xml_results_in_max_int_page_in_toc_entry/

2023-10-24 07:44 UTC, stollero requested changes
Bei mir hat es leider nicht funktioniert. Nach dem Drop ändert sich nicht der Header :(

2023-10-24 07:44 UTC, stollero commented on core/src/zeit/content/article/article.py
> +def set_podcast_header_when_article_has_podcast_audio(context, event):
Vorschlag: Da ich es in den anderen Events gesehen habe. Macht es vielleicht Sinn auch hier zu filtern und die Aktion nur durchzuführen, falls in der ``event.descriptions`` auch das Interface ``zeit.content.audio.interfaces.IAudios`` auftaucht

2023-10-30 07:07 UTC, thomasbaumann commented
Oh sry, bei den Commits von Louisa ist jetzt auch mein Kopf dran. Es gab irgendeinen Häckmäck beim Rebasen (und ich glaube zunächst: Mergen), so dass erst viele olle Commits dranhoingen. Den habe ich irgendwie wieder weggekriegt, aber mein Kopf ist drangeblieben. Ist das schlimm? Kriegt man das wieder weg?

2023-10-30 09:48 UTC, stollero commented on core/src/zeit/content/article/article.py
> +def set_podcast_header_when_article_has_podcast_audio(context, event):
``zeit.content.audio.reference.Audios``

```python
@zope.interface.implementer(zeit.content.audio.interfaces.IAudios)
class Audios(zeit.cms.related.related.RelatedBase):
    items = zeit.cms.content.reference.MultiResource(
        '.head.audio', 'related'
    )

    def __setattr__(self, name, value):
        if name == 'items':
            zope.lifecycleevent.modified(self, value)
        super().__setattr__(name, value)
```

``zeit.content.article.article``

```python
@grok.subscribe(
    zeit.content.audio.interfaces.IAudios,
    zope.lifecycleevent.IObjectModifiedEvent)
def set_podcast_header_when_article_has_podcast_audio(audioreference, event):
    if not audioreference.items:
        return
    header_source = zeit.content.article.source.ArticleHeaderSource()
    header_layout = header_source.factory.getTitle(audioreference.context, 'podcast')
    audioreference.context.header_layout = 'podcast' if header_layout else None
```

2023-11-01 13:26 UTC, louika commented on core/src/zeit/content/article/tests/test_article.py
> +                    zeit.content.article.interfaces.IArticle,
nun kein event im Test mehr notwendig

2023-11-01 13:32 UTC, louika commented on core/src/zeit/content/article/article.py
> +    header_layout = header_source.factory.getTitle(context, 'podcast')
wie meinen @thomasbaumann ? ich kann dir grade nicht folgen. die template.xml ist `article-templates.xml` das sieht man in `zeit.content.source.py`

2023-11-01 14:49 UTC, louika commented on core/src/zeit/content/article/article.py
> +    header_layout = header_source.factory.getTitle(context, 'podcast')
> Auf dem Objekt gespeichert wird die ID, nicht der Titel. Am einfachsten also `context.header_layout = 'podcast'`, wobei man vmtl sicherheitshalber auch noch `context.layout = 'zon-article'` dazusagen muss (denn mögliche Header hängen vom gewählten Layout ab). Und dann nen Kommentar dran "das funktioniert natürlich nur, wenn in der Konfigdatei diese Layout/Header-Kombination auch eingetragen ist".

dann nehme ich die ID `podcast` statt des Titels

2023-11-01 14:49 UTC, louika commented on core/src/zeit/content/article/article.py
> +    except TypeError:
der ganze Teil ist rausgefallen

2023-11-01 15:36 UTC, louika commented on core/src/zeit/content/article/article.py
> +    header_layout = header_source.factory.getTitle(context, 'podcast')
ich habe Schwierigkeiten den Anspruch `template==zon-article` umzusetzten. Der default im lokalen server, bzw auf staging ist `zon-article`, die Testdaten bringen hingegen alle `article` mit.
eigentlich dachte ich, dass man einfach Prüfen kann, ob der Context (der Artikel) das richtige Template mitbringt, bevor man den Podcastheader setzt. ich denke, dass man das template nicht einfach während des Referenzierens des Audios setzen sollte, das passt von der Modellierung nicht.

2023-11-01 16:02 UTC, louika commented on core/src/zeit/content/article/article.py
> +    header_layout = header_source.factory.getTitle(context, 'podcast')
boah, es gibt eine extra `template.xml` in `zeit.content.article.edit.tests` in der das Template für Artikel einfach `article` heißt 🪦 fies!

2023-11-01 16:03 UTC, louika commented on core/src/zeit/content/article/article.py
> +    header_layout = header_source.factory.getTitle(context, 'podcast')
dort gibt es auch keinen Podcast Header

2023-11-01 16:15 UTC, louika commented
mal sehen, wie viele Tests durch die Anpassung des Namens des Artikeltemplates umkippen 🙈

2023-11-01 16:36 UTC, louika commented
hm, 8 hält sich in Grenzen, aber die Frage ist, ob das wirklich das richtige Vorgehen ist. Ich diskutier das morgen mal im Daily

2023-11-02 11:56 UTC, stollero approved these changes
- Wenn in ein Visual Article ein Audio gezogen wird, steht die Auswahl auf "Keine Auswahl"
- Seltsamerweise muss ich danach das Audio erst löschen um dann wieder auf Artikel zu wechseln

Im Kern funktioniert es jedoch und alles andere vielleicht später, wenn es jemanden stört ;)

2023-11-02 15:04 UTC, merged