ZO-3997: Audio object form without publish or retract actions
ZeitOnline/vivi pull request #538
Opened 2023-10-25 08:20 UTC by stollero

2023-10-25 12:18 UTC, wosc requested changes

2023-10-25 12:18 UTC, wosc commented on core/src/zeit/content/audio/browser/form.py
> +    therefore implement the Workflow without the actions
Ha, das ist natürlich auch ne Idee, das gar nicht über Permissions abzubilden (wie wirs zb in zeit.content.cp tun), sondern die Actions insgesamt rauszunehmen. Fair enough.

Das könnte man dann aber noch einfacher aufschreiben, indem man eine Limitierung von zope.formlib ausnutzt: Sobald man _eine_ `@action` in einer Subklasse aufführt, werden keine Actions von der Basisklasse geerbt. (Aus irgendwelchen mechanischen Gründen, nicht als Designprinzip, glaube ich jedenfalls.) Dh man könnte hier vom `AssetWorkflow` Form erben, aber die "save state" Action explizit nochmal hinschreiben, und ist damit publish+retract los.

Wobei man dann als nächstes vmtl dazu kommt, dass `AssetWorkflow` eigentlich gar nicht der richtige Workflow für Audio-Objekte ist, weil der `ITimebasedPublishing` beinhaltet, was wohl nicht gewünscht ist? Insofern wird man vmtl doch ein eigenes Workflow-Form brauchen, aber halt _auch noch_ einen eigenen Workflow. Leider enthält `NoWorkflow` die published/last_published Felder nicht... dh _genau_ die Schnittmenge, die wir hier wollen, gibts bisher fürchte ich einfach nicht, sondern wird man erfinden müssen. Aber immerhin kann man sich dann hoffentlich das ganze extra `omit_fields` und bla sparen, sondern irgendwoher erben...

2023-10-25 14:50 UTC, stollero commented on core/src/zeit/content/audio/browser/form.py
> +    therefore implement the Workflow without the actions
Sehr gute Limitierung 💡 (zu mindestens für unseren Fall). In Rücksprache mit Rose und Sonja fahren wir erst einmal den Ansatz der fehlenden Actions.

2023-10-25 14:54 UTC, stollero commented on core/src/zeit/content/audio/browser/form.py
> +    therefore implement the Workflow without the actions
Ah und natürlich Danke für den Hinweis mit `zeit.content.cp`. Die `conditions` sind auch sehr sinnvoll.

2023-10-26 07:22 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdW1mc2pzenl3ZzZseDV6YWVscGw4dmc2MGVpZ3E4YmdibXd6amwwZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l3vR9U5hjEF6B18xq/giphy.gif)

2023-10-26 07:23 UTC, merged