ZO-3764: article title, teasertext and body automatically edited if audio is added
ZeitOnline/vivi pull request #553
Opened 2023-11-10 11:26 UTC by stollero

2023-11-10 15:12 UTC, louika requested changes
Funktioniert, aber ich habe eine Detailfrage zu den Teasertexten. Wenn die geklärt ist, gern mergen 😸

2023-11-10 15:12 UTC, louika commented on core/src/zeit/content/article/article.py
> +        if not reference.context.teaserText:
Der Teasertext ist auf 170 Zeichen begrenzt. Soll trotzdem die komplette Summary eingetragen werden? Ich habe das mit dem [Audioobjekt](http://localhost:8080/repository/podcasts/2023-10/245d1008-1704-4eb7-8b6e-45fade884758/@@view.html) ausprobiert. Der Text ist zu lang. So lässt sich grade ohne Korrektur kein Draft einchecken. Vllt. Rücksprache mit Rose halten

2023-11-10 15:12 UTC, louika commented on core/src/zeit/content/article/article.py
> +            reference.context.body.create_item('p').text = episode.notes
cool, so werden gleich Links usw. übernommen 👏

2023-11-10 15:12 UTC, louika commented on core/src/zeit/content/article/article.py
> +    reference.context.header_layout = "podcast"
nitpicking, erst aus einfachen doppelte Anführungszeichen machen, aber dann in Zeile 381 wieder einfache nehmen 😉

2023-11-10 15:12 UTC, louika commented on core/src/zeit/content/article/edit/browser/form.py
> +            self.context.body, "contents"))
works as intended 👍

2023-11-13 06:59 UTC, stollero commented on core/src/zeit/content/article/article.py
> +        if not reference.context.teaserText:
Guter Punkt, werde es im Daily ansprechen

2023-11-13 15:04 UTC, wosc commented
run jenkins

2023-11-14 11:53 UTC, louika approved these changes
![hi](https://media.giphy.com/media/ypqHf6pQ5kQEg/giphy.gif)

2023-11-15 06:39 UTC, stollero commented on core/src/zeit/content/article/article.py
> +        if len(context.body.keys()) <= 1:
Ich bin offen für Vorschläge wie es aussehen könnte

2023-11-15 14:22 UTC, louika commented on core/src/zeit/content/article/article.py
> +        if not body or (len(body.keys()) == 1 and context.main_image_block):
der adapter `zeit.content.article.edit.interfaces.IEditableBody` ist immer trueish, das kann wieder raus

2023-11-15 14:37 UTC, louika commented on core/src/zeit/content/article/article.py
> +        if not body or (len(body.keys()) == 1 and context.main_image_block):
oki, meinetwegen, die Bedingung existiert nur für Testfälle

2023-11-15 15:15 UTC, merged