MAINT: add hook that replaces double quoted strings with single quote
ZeitOnline/vivi pull request #554
Opened 2023-11-13 06:57 UTC by stollero

2023-11-13 07:43 UTC, wosc requested changes
Ich denke, _wenn_ wir nen Formatter einrichten, dann bitte einen ingesamten, also Kategorie black/yapf/ruff o.ä.

2023-11-13 08:25 UTC, stollero commented
> Ich denke, _wenn_ wir nen Formatter einrichten, dann bitte einen ingesamten, also Kategorie black/yapf/ruff o.ä. -- was natürlich gleich die Diskussion aufmacht, welchen/wie/etc. 🤪

Eine vollständige Autoformatierung begrüße ich natürlich, ich schau mal was da für ein Wand an Änderungen kommt. Ruff ist natürlich der Kandidat, da es wirklich flott ist

2023-11-13 08:28 UTC, stollero commented on .pre-commit-config.yaml
> +  - id: double-quote-string-fixer
Das kann ich noch raus schmeißen und die .flake8 Konfiguration

2023-11-13 09:27 UTC, louika commented
ich bin bei Wolfgang, was das angeht, aber es wird bestimmt ein Klotz :)

2023-11-13 09:27 UTC, louika reviewed
ich bin bei Wolfgang, was das angeht, aber es wird bestimmt ein Klotz :)

2023-11-16 07:20 UTC, wosc approved these changes
Let's do this! :)

Leider hat ein anderer PR es überholt, sodass du es fürchte ich nochmal neu laufen lassen musst, sorry about that.

2023-11-16 07:46 UTC, merged