ZO-4254: index audio objects
ZeitOnline/vivi pull request #561
Opened 2023-11-24 14:15 UTC by stollero

2023-11-24 14:16 UTC, stollero commented on core/src/zeit/retresco/tests/test_content.py
> +        data = zeit.retresco.interfaces.ITMSRepresentation(article)()
Na, den Testaufbau der 2 Tests kriegen wir noch etwas kompakter. Ist ja auch doppelt ...

2023-11-27 09:27 UTC, stollero commented on core/src/zeit/retresco/content.py
> +        # XXX nur im article context
Bitte entfernen !

2023-11-27 13:19 UTC, louika requested changes

2023-11-27 13:30 UTC, louika commented on core/src/zeit/content/audio/testing.py
> +for key in AudioBuilder().__dict__['attributes']:
das erscheint mir etwas umständlich, wenn man stattdessen dem `FunctionalTestCase` eine einfach `create_audio` Methode verpassen könnte. Aber funktioniert und ist sauber.

2023-11-28 07:39 UTC, stollero commented on core/src/zeit/content/audio/testing.py
> +for key in AudioBuilder().__dict__['attributes']:
Wollte es etwas flexibler gestalten und ich mag `builder`.

2023-11-28 11:47 UTC, louika approved these changes
Can confirm, article has `audio_reference` in TMS Representation. 
Possibly missing? schema update in tms deployment.
```
$ bin/serve shell

Environment:
  root         ZODB application root folder (already set as ZCA site)
Modules that were pre-imported for convenience: zope, zeit, transaction

>>> article = zeit.cms.interfaces.ICMSContent('http://xml.zeit.de/test/test-louisa/audio-article')
>>> article
<zeit.content.article.article.Article http://xml.zeit.de/test/test-louisa/audio-article>
>>> import zeit.retresco.interfaces
>>> tms_article = zeit.retresco.interfaces.ITMSRepresentation(article)
>>> tms_article
<zeit.retresco.convert.TMSRepresentation object at 0x118bdeb30>
>>> tms_article()
> /Users/huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/retresco/convert.py(504)__call__()
-> result['payload']['head'] = self._convert_audio_references()
(Pdb) c
{   'body': '<body><title>audio test </title><subtitle>Heute kein echter '
            'Vogel, sondern ein Schmetterling.</subtitle><division '
            'type="page"><image is_empty="True" variant_name="wide"/><p>Der '
            '<strong>Sturmvogel</strong> (<i>Melanthia procellata</i>), auch '
            'als <strong>Waldreben-Blattspanner</strong> bezeichnet, ist ein '
            '<a '
            'href="https://de.wikipedia.org/wiki/Schmetterlinge">Schmetterling</a> '
            '(<a '
            'href="https://de.wikipedia.org/wiki/Nachtfalter">Nachtfalter</a>) '
            'aus der <a '
            'href="https://de.wikipedia.org/wiki/Familie_(Biologie)">Familie</a> '
            'der <a '
            'href="https://de.wikipedia.org/wiki/Spanner_(Schmetterling)">Spanner</a> '
            '(Geometridae). Das <a '
            'href="https://de.wikipedia.org/wiki/Epitheton">Artepitheton</a> '
            'basiert auf dem <a '
            'href="https://de.wikipedia.org/wiki/Lateinische_Sprache">lateinischen</a> '
            'Wort <i>procella</i> mit der Bedeutung »Sturm« und bezieht sich '
            'auf den stürmischen Flug der Männchen.<a '
            'href="https://de.wikipedia.org/wiki/Sturmvogel_(Schmetterling)#cite_note-Spuler-1">[1]</a></p></division></body>',
    'date': '2023-11-28T11:39:29Z',
    'doc_id': '{urn:uuid:ce0153e8-7605-4d6f-a079-a31b49b63521}',
    'doc_type': 'article',
    'payload': {   'body': {   'subtitle': 'Heute kein echter Vogel, sondern '
                                           'ein Schmetterling.',
                               'title': 'audio test '},
                   'document': {   'artbox_thema': False,
                                   'audio_speechbert': True,
                                   'author': [],
                                   'banner': True,
                                   'banner_content': True,
                                   'channels': ['Kultur Literatur'],
                                   'comments': True,
                                   'comments_premoderate': False,
                                   'date-last-modified': '2023-11-28T11:39:29.573999+00:00',
                                   'date_first_released': '2023-11-28T11:39:29.104568+00:00',
                                   'date_last_checkout': '2023-11-28T11:39:29.531329+00:00',
                                   'has_recensions': False,
                                   'header_layout': 'podcast',
                                   'hide_adblocker_notification': False,
                                   'hide_ligatus_recommendations': False,
                                   'last-semantic-change': '2023-11-28T11:38:07.036797+00:00',
                                   'last_modified_by': 'louisa.huelsen@zeit.de',
                                   'overscrolling': True,
                                   'prevent_ligatus_indexing': False,
                                   'previous_uniqueIds': [   'http://xml.zeit.de/test/test-louisa/2352172e-0805-4c5f-b63c-a8ca4b7caab3.tmp'],
                                   'ressort': 'Kultur',
                                   'show_commentthread': True,
                                   'sub_ressort': 'Literatur',
                                   'template': 'zon-article',
                                   'text-length': 368,
                                   'uuid': '{urn:uuid:ce0153e8-7605-4d6f-a079-a31b49b63521}',
                                   'volume': 26,
                                   'year': 2008},
                   'head': {   'agencies': [],
                               'audio_references': [   'http://xml.zeit.de/podcasts/2023-11/5d276869-1f2f-4979-8b41-b4676422ad9b'],
                               'authors': []},
                   'meta': {   'provides': '<pickle>\n'
                                           '  <initialized_object>\n'
                                           '    <klass>\n'
                                           '      <global name="Provides" '
                                           'module="zope.interface.declarations"/>\n'
                                           '    </klass>\n'
                                           '    <arguments>\n'
                                           '      <tuple>\n'
                                           '        <global name="Article" '
                                           'module="zeit.content.article.article"/>\n'
                                           '        <global name="IZONArticle" '
                                           'module="zeit.content.article.interfaces"/>\n'
                                           '        <global name="IZONContent" '
                                           'module="zeit.cms.section.interfaces"/>\n'
                                           '      </tuple>\n'
                                           '    </arguments>\n'
                                           '  </initialized_object>\n'
                                           '</pickle>',
                               'tms_last_indexed': '2023-11-28T11:43:39.662719+00:00',
                               'type': 'article'},
                   'speech': {'checksum': '93b00029d205647aea93c6adbe20318b'},
                   'tagging': {   'keywords': '<ns0:rankedTags '
                                              'xmlns:py="http://codespeak.net/lxml/objectify/pytype" '
                                              'xmlns:xsd="http://www.w3.org/2001/XMLSchema" '
                                              'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
                                              'xmlns:ns0="http://namespaces.zeit.de/CMS/tagging"><ns0:rankedTags><tag '
                                              'type="keyword" '
                                              'py:pytype="str">Schmetterling</tag></ns0:rankedTags></ns0:rankedTags>'},
                   'teaser': {   'text': 'Heute kein echter Vogel, sondern ein '
                                         'Schmetterling.',
                                 'title': 'Sturmvogel (Schmetterling)'},
                   'vgwort': {   'private_token': 'private-151098',
                                 'public_token': 'public-151098'},
                   'vivi': {   'cms_icon': '/@@/zeit-content-article-interfaces-IArticle-zmi_icon.png',
                               'publish_status': 'published'},
                   'workflow': {   'corrected': 'yes',
                                   'date_last_published': '2023-11-28T11:39:29.104568+00:00',
                                   'date_last_published_semantic': '2023-11-28T11:39:29.104568+00:00',
                                   'edited': 'yes',
                                   'product-id': 'ZEDE',
                                   'published': True,
                                   'seo_optimized': 'no',
                                   'urgent': False}},
    'rtr_events': [],
    'rtr_keywords': ['Schmetterling'],
    'rtr_locations': [],
    'r [...]

2023-11-28 11:49 UTC, merged