Zo 4214
ZeitOnline/vivi pull request #571
Opened 2023-12-08 14:19 UTC by stollero

### Checklist

- [ ] Documentation
- [x] Changelog
- [ ] Tests
- [ ] Translations

### gif
![](https://media.giphy.com/media/fxz4o3wIT3FYxMdWlg/giphy.gif)

2023-12-12 07:27 UTC, stollero commented
run jenkins

2023-12-13 07:46 UTC, wosc requested changes
Audiofilter: 🚀 , UI-Verbesserung: leider 😬

2023-12-13 07:46 UTC, wosc commented on core/src/zeit/find/browser/resources/find.js
> +        MochiKit.Signal.connect('audio_type_select', 'onchange', function(event) {
Also, ich sags nur ungern, und das ist sicherlich ein eher unbefriedigender Punkt, aber: wir haben das sonst nirgends, dass wir die erweiterten Filterfelder in Abhängigkeit der gewählten Conten-Typen verfügbar machen. Darüber könnte man grundsätzlich sicherlich nachdenken, denn man kann da aktuell in der Tat eine Menge Unsinn einstellen (nur um ein (1) allererstes Beispiel zu nennen, was mir sofort einfällt: Bilder/gruppen haben kein Ressort).

Aber: _wenn_ wir sowas tun wollen, sollten wir die ganzen Zusammenhänge (welche Typen welche Felder verstehen) bitte nicht alle in JS dupliziert nachprogrammieren, sondern uns auf die Interfaces und Schemafelder stützen. Und ehrlicherweise, da die "schlimmste" Auswirkung doch ist, dass man halt keine Ergebnisse bekommt, und ggf. einmal auf das "X" klicken muss, wenn man noch zu viele "alte" Filter drinstehen hat, sehe ich derzeit nicht, dass sich der Entwicklungsaufwand dafür lohnt.

Insofern würde ich dich bitten, die Sonderbehandlung hier zu entfernen, sorry.

2023-12-13 08:24 UTC, stollero commented on core/src/zeit/find/browser/resources/find.js
> +        MochiKit.Signal.connect('audio_type_select', 'onchange', function(event) {
Ach Schade, aber das verstehe ich. Die Filter wieder zu entfernen werden die Leute schon meistern. 👍

2023-12-13 09:10 UTC, wosc approved these changes
![](https://i.giphy.com/media/ef61oIGVyckY8/giphy.gif)

2023-12-13 09:10 UTC, merged