ZO-4369: Format audio episode notes to correct html in article body
ZeitOnline/vivi pull request #577
Opened 2023-12-19 17:08 UTC by louika

We want all the paragraphs of the audio episode notes! Including but not limited to the very weird ones, without html tags.

### Checklist

- [ ] Documentation
- [x] Changelog
- [x] Tests
- [ ] Translations no

### gif
![audiocity](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExb293Z3hmZHpweXNwdGQyZmw1c25sN3ZjNjUybGZ3YmtxOTZ0N3dmcSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/26n5ZZfTd3cBLoj2E/giphy.gif)

2023-12-20 13:03 UTC, stollero requested changes
Vielen Dank Louisa, das sieht doch schon sehr gut aus.

Beim Ausprobieren in Simplecast sind mir noch 2 Dinge aufgefallen.

Simplecast HTML erlaubt blockquotes (würde ich aber erst einmal komplett ignorieren) und verschachtelte Listen. Das unterstützen wir nicht aber wie hoch ist schon die Wahrscheinlichkeit das die KollegInnen mit so etwas ankommen oder?

Sonst noch paar Anmerkungen zum Code. Du packst das 🦾

2023-12-21 09:53 UTC, louika commented on core/src/zeit/content/article/article.py
> +                self.context.create_item('intertitle').text = str(item)
😸

2023-12-21 09:56 UTC, louika commented on core/src/zeit/content/article/article.py
> +        for item in notes.contents:
ich bin kein so großer Fan von Mappings. Aber nehm ich so :)

2023-12-21 10:45 UTC, louika commented on core/src/zeit/content/audio/testing.py
> +                'notes': '<p>dolor <b>sit</b> amet</p>',
wenn in Simplecast eine neue Podcastepisode angelegt wird, dann enthalten die Episode Notes, selbst bei einem Oneliner, html `<p>` Tags. Ich habs im Dummy überprüft. Trotzdem gibt es den Fall bei den migrierten, bereits archivierten Podcasts, dass der erste Absatz der Notes keine Paragraph Tags hat. Es gibt aber weitere Toplevel html Tags, siehe Ticket. Hierfür gibt es den Default, dass automatisch ein Paragraph erstellt wird.
<img width="378" alt="Screenshot 2023-12-21 at 11 39 55" src="https://github.com/ZeitOnline/vivi/assets/20401272/ef5b3324-65ec-4de6-af89-e038723bfe85">
<img width="1115" alt="Screenshot 2023-12-21 at 11 39 47" src="https://github.com/ZeitOnline/vivi/assets/20401272/be32b63f-1aeb-4e4a-9c42-3b7e92c2c122">

2023-12-27 09:37 UTC, thomaspuppe commented
![](https://media.giphy.com/media/L1FuQ8NSeilXixNolP/giphy-downsized.gif)

2023-12-27 09:37 UTC, merged