ZO-4460: Add tts to article
ZeitOnline/vivi pull request #593
Opened 2024-01-22 12:50 UTC by louika

Reference the tts audio object in its corresponding article during creation via webhook by speechbert.

### Checklist

- [x] Documentation
- [x] Changelog
- [x] Tests
- [ ] Translations 👎 no translations for backend changes

### gif
![huii](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM3g5Ynd6c3czNmtvZno0NjlrZnB4NTl4eTc0bXAwam01dmF5azZueSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ZaX7ccF2bDBy7S9v7P/giphy.gif)

2024-01-24 08:16 UTC, wosc requested changes

2024-01-24 08:16 UTC, wosc commented on core/src/zeit/speech/connection.py
> +        return int(milliseconds / 1000)
Auch das hier verdient eigentlich seinen eigenen Commit, dann kann man nämlich auch in die Message schreiben, warum das einen Fehler werfen darf/soll, was es bisher ja extra nicht getan hat.

2024-01-25 10:49 UTC, wosc approved these changes
![](https://i.giphy.com/media/cCbfB1iDFYAEuiVIzW/giphy.gif)

2024-01-25 10:49 UTC, wosc commented on core/src/zeit/content/article/article.py
> +    def validate(self, checksum: str) -> bool:
Für ggf. später mal: für den besonders schönen Aufschrieb könnte man hier ein `other: IChecksum` nehmen (oooder noch bequemer sogar, innendrin auf `IChecksum` adaptieren?), und/oder ein `__eq__` draus machen.

2024-01-25 10:49 UTC, wosc commented on core/src/zeit/content/audio/audio.py
> +@grok.adapter(IAudio)
Wir sortieren ansonsten andersrum, erst adapter, dann implementer, mit der Idee dass man es linear "von -> nach" lesen kann.

2024-01-25 10:53 UTC, stollero commented on core/src/zeit/content/article/article.py
> +    def validate(self, checksum: str) -> bool:
Oh guter Hinweis. Ein `__eq__` wäre natürlich auch nett.

2024-01-25 10:55 UTC, stollero commented on core/src/zeit/content/audio/audio.py
> +@grok.adapter(IAudio)
Das ändere ich mal noch fix. 👍

2024-01-25 12:14 UTC, merged