ZO-4460: No enrich for audios, and check reference during tts update
ZeitOnline/vivi pull request #598
Opened 2024-01-26 15:52 UTC by louika

### Checklist

- [ ] Documentation
- [x] Changelog
- [x] Tests
- [x] Translations, no new translation found after `bin/i18nextract`

### gif
![weekend approaching](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMW4zazVvMjJnaG9qMnUwcGh1azlsM3g3cjZtbXlpeTQ5OHkzeG93eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9lyuDkgZJ4OBO/giphy.gif)

2024-01-26 16:04 UTC, louika commented
hm, der war eben lokal grün 🤔

2024-01-26 16:09 UTC, louika commented
wer seine Änderungen stashed, ist selbst schuld. In `zeit.speech` ist ein Durcheinander, was `mock.patch` und `connector.search_result` angeht, das ist nicht feierlich

2024-01-29 09:19 UTC, wosc requested changes
Passt an sich, mir ist noch eine Vereinfachungsmöglichkeit aufgefallen.

2024-01-29 09:19 UTC, wosc commented on core/src/zeit/speech/connection.py
> +    def _ensure_reference(self, speech):
Ich glaube, das kann man einfacher aufschreiben, nämlich indem man die Prüfung aus `_ensure_reference` in `add_audio_reference` mit einbaut, und dann in beiden if-Branches (create und update) eben das aufruft.

2024-01-29 14:18 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExaWJodWxmZTM3NzVhbWp6dXltNXZiNTJscmNhNjNpN2d1MXo4ZHE4ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/wsJHi6a1JwoXC/giphy.gif)

2024-01-29 14:18 UTC, merged