ZO-4612: Create publisher payload per content object and catch errors
ZeitOnline/vivi pull request #604
Opened 2024-02-05 09:37 UTC by wosc

### Checklist

- [x] Documentation: Ich würde das zum Anlass nehmen ("Pfadfinder-Regel"), mal zumindest grob den Aufbau von IPublish, IPublishInfo, zeit.cms.workflow vs zeit.workflow zu beschreiben
- [x] Changelog
- [x] Tests
- [x] ~Translations~

2024-02-05 14:38 UTC, stollero requested changes
Hat einen Moment gedauert bevor ich den Unterschied erkannt habe. Dadurch das du die `IPublisherData` in die `serialize` gezogen hast, wird im Falle des Fehlers nur das jeweilige Objekt in `ERRORS` gezogen 💡

Sehr cool das du weiter aufgeräumt hast im Test Setup 👍

2024-02-05 14:38 UTC, stollero commented on core/src/zeit/workflow/tests/test_publish.py
> +        with self.assertRaises(Exception):
Exception wird geworfen aber leider aus dem falschen Grund :(

```TypeError: 'PersistentUnknownResource```

2024-02-06 07:36 UTC, wosc commented on core/src/zeit/workflow/tests/test_publish.py
> +        with self.assertRaises(Exception):
Das kann ich nicht bestätigen, bei mir sieht es exakt korrekt aus:

```
zeit.workflow.publish.MultiPublishError: [(<zeit.cms.repository.unknown.PersistentUnknownResource http://xml.zeit.de/online/2007/01/Flugsicherheit>, RuntimeError('provoked'))]
```

Aber ich füge sicherheitshalber eine Assertion über die Fehlermeldung hinzu.

2024-02-06 08:13 UTC, stollero commented on core/src/zeit/workflow/tests/test_publish.py
> +        with self.assertRaises(Exception):
Nevermind, du hast Recht

2024-02-06 08:14 UTC, stollero approved these changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM25tdzk1b3A4YW9ueWU3NHpzNGE4dnRjd2JhczlvM2J6OTM1Y3l6ZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5UH2PJ8VIEuMqN8V6R/giphy-downsized.gif)

2024-02-06 08:14 UTC, merged