ZO-4649: calculate checksum of article body and compare against tts audio before adding audio reference
ZeitOnline/vivi pull request #607
Opened 2024-02-07 15:33 UTC by stollero

### Checklist

- [ ] Documentation
- [ ] Changelog
- [ ] Tests
- [ ] Translations

### gif
![]()

2024-02-08 08:13 UTC, wosc requested changes

2024-02-08 11:25 UTC, stollero commented on core/src/zeit/speech/tests/test_connection.py
>          assert IAudioReferences(ICMSContent(self.article_uid)).items == (audio,)
Gut entdeckt 👍

2024-02-08 11:25 UTC, stollero commented on core/src/zeit/speech/connection.py
> +        article_checksum = calculate_checksum(article, None)
Auf jeden Fall!

2024-02-09 07:45 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbGxma28zbjcwOHNoYWJzbTF6NndmbWRwOXNhdmZmeG44MmplNHZ3YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l378nD4M8UsMV5Xb2/giphy.gif)

2024-02-09 07:45 UTC, merged