ZO-4267: postgresql connector copy move lock
ZeitOnline/vivi pull request #632
Opened 2024-02-26 07:44 UTC by stollero

### Checklist

- [x] [Documentation](https://github.com/ZeitOnline/vivi-deployment/pull/879) Teil 1, Teil 2 erfolgt im [Content Storage](https://github.com/ZeitOnline/content-storage-api/pull/135)
- [x] Changelog
- [x] Tests
- [ ] Translations

### gif
![]()

2024-03-01 11:03 UTC, wosc requested changes

2024-03-01 12:42 UTC, louika commented on core/src/zeit/connector/connector.py
> +            raise exception(old_id, f'Can not copy or move non-existant resource {old_id}') from err
`KeyError` for nonexisting resource wieder eingebaut 👍

2024-03-01 12:43 UTC, louika commented on core/src/zeit/connector/connector.py
> -                resolve_conflicts
schon passiert 👍

2024-03-01 12:43 UTC, louika commented on core/src/zeit/connector/filesystem.py
> -                # XXX mimic the real behaviour -- real *should* probably raise
Yay 🥳

2024-03-01 13:02 UTC, stollero commented on core/src/zeit/connector/testing.py
> +        for _name, uid in connector.listCollection(uid_in):
Das Problem ist das `UNLOCK` in diesem Fall. Das `DELETE` ist aus reiner bequemlichkeit dabei :)

2024-03-01 13:19 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +        self.unlock(new_id)
Das aktuelle Verhalten von Vivi ist, wenn du ein Move machst wird der eigene Lock entfernt, aber ein Move setzt kein Lock.

Unlock kann auch angewendet werden, wenn kein Lock auf der Resource ist und dann passiert halt nichts.

2024-03-01 13:20 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +        self.unlock(new_id)
Wir trennen die Commits nochmal, das die Locking Thematik getrennt von copy und move ist

2024-03-01 14:09 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +            ondelete='CASCADE',
Ist richtig und es fehlt auch tatsächlich noch ein einfacher Test, welcher prüft das ich kein Objekt entfernen kann, sofern ich nicht das Lock halte.

Bei Collections müssen wir dann auch nochmal das Gleiche machen und dann explizit den Lock entfernen.

2024-03-01 14:16 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +class Property(DBObject):
Klassenname ist ja glücklicherweise unabhängig vom Namen der Tabelle in der Datenbank. `Content` finde ich gut für die Klasse. Den Namen der Tabelle zu ändern sollten wir auch noch irgendwann mal tun, damit es einmal richtig ist.

2024-03-01 14:31 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +    id = Column(Uuid(as_uuid=False), primary_key=True)
Na klar, wesentlich besser als der kombinierte Key :) 👍

2024-03-04 10:27 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +        token = secrets.token_hex()
Für unseren Einsatz hätte es sicherlich auch ein Hash getan, aber ein großer Vorteil ergibt sich dadurch nun nicht. Mir fällt spontan nichts ein, vielleicht ein wenig bessere Performance.

```
❯ python3 -m timeit "import hashlib;m=hashlib.sha1();m.update(b'http://xml.zeit.de/path/to/article+zope.user');m.hexdigest()"
1000000 loops, best of 5: 311 nsec per loop
```

```
❯ python3 -m timeit "import hashlib;hashlib.sha1(b'http://xml.zeit.de/path/to/my/article+zope.user').hexdigest()"
1000000 loops, best of 5: 301 nsec per loop
```

2024-03-04 10:28 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +    def unlock(self, id, locktoken=None):
Das mach ich gleich noch

2024-03-04 10:30 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +            ondelete='CASCADE',
Ich habe noch offene Punkte, mir fällt auf das ich blobs als solche nicht rekursiv entferne. Ich würde da nochmal ein Issue erstellen damit sich dieser PR nicht unendlich zieht

2024-03-04 12:13 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        elif lock_principal == requesting_principal:
Es stellt sich raus, dieses Verhalten wird tatsächlich verwendet, und zwar für das [steal lock](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/cms/locking/browser/lock.py#L52) Feature: vivi-Benutzer mit entsprechenden Rechten dürfen die Locks von anderen vivi-Benutzern entsperren. (Aber keine Locks von externen Benutzern.)

Ich frage mich jetzt allerdings, ob man diese Einschränkung wirklich im Connector-Layer implementieren will/soll, oder ob das nicht im UI-Layer besser aufgehoben wäre. Und umgekehrt frage ich mich eben, ob wir aktuell nicht zu lax damit sind, Connector-Operationen zu erlauben, wenn das Lock _irgendeinem_ vivi-Benutzer gehört, und nicht zu prüfen, dass es bitte sehr dem _anfordernden_ Benutzer gehören muss. Aber diese Punkte würde ich glaube aus dem aktuellen Ticket auch ausklammern wollen, und sagen, wir machens jetzt halt erstmal in sql "genau wie in dav".

2024-03-04 13:24 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +class Property(DBObject):
Right, das ist natürlich auch eine Möglichkeit, die Tabelle erstmal noch auf dem alten Namen zu belassen. :) Habe ZO-4873 dafür geschrieben.

2024-03-04 13:25 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        token = secrets.token_hex()
Aus meiner Sicht wäre der Haupt-Vorteil, dass man ein Stück Daten nicht speichern muss, was man eh nicht braucht. :)

2024-03-04 14:09 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +        token = secrets.token_hex()
Nach rebase entsprechend `_unlock` hinzugefügt und `token` aus der Tabelle gefeuert. :)

2024-03-05 08:16 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +            ondelete='CASCADE',
habe ZO-4882, ZO-4883 angelegt

2024-03-05 15:47 UTC, wosc requested changes

2024-03-05 15:47 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +    def _is_current_principal(self, principal):
Der Methodenname stimt so erst, wenn ZO-4872 kommt. Womöglich können wir das am einfachsten umschiffen, indem wir das Vorzeichen umdrehen? Und es `_is_foreign[_principial|_lock|nix|...]` nennen.

2024-03-05 15:47 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        self.session.execute(stmt)
Das geht eleganter als `self.session.add(Lock.create(...))`, also indem das `create` einfach die Instanz zurückgibt. Man könnte sogar drüber diskutieren, ob man `Lock.__init__` überschreiben will, statt ne separate Methode einzuführen (wobei das dann halt etwas durcheinandergeht mit dem von sqlalchemy bereitgestellten abstrakten `init(**kw)`).

2024-03-05 15:47 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        stmt = Lock.create(path=path, principal=principal, until=until)
Da wir hier doch extra eine Methode einführen für genau den Usecase, braucht man dann auch keine kw-Parameter verwenden, sondern kann direkt `(path, principal, until)` reinstecken.

2024-03-05 15:47 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +            return (None, None, False)
Das Interface sagt hier auch, "raises KeyError if resource does not exist". Das würde mir auch mehr einleuchten -- und außerdem die zusätzliche `_add_lock` Methode unnötig machen, weil man das dann denke ich einkürzen kann auf

```python
def lock(...):
    case NO_LOCK:
        lock = Lock.create(self.session.get(Path, self._pathkey(id)), principal, until)
        self.session.add(lock)
        return lock.token
```

2024-03-05 15:47 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +    OTHERS_LOCK = 1
Vmtl auch eher "foreign"?

2024-03-05 15:47 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        new_resource = Resource(
Würde uns hier evtl eine Methode "unterhalb" von `add()` guttun, der man direkt das `Content` Objekt geben kann? Oder sonstwie nen relevanten Teil davon raustrennen? Denn die ganzen Daten erst aus nem `Content` in ein `Resource` und dann im setitem/add wieder zurück in `Content` zu schieben, fühlt sich irgendwie überflüssig an, wenn man _im Prinzip_ hier doch nur `session.add(new_content)` sagen will (aber modulo GCS, natürlich).

2024-03-05 15:47 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        self.unlock(new_id)
Sorry, ich steh hier immernoch auf dem Schlauch. Wo ist das vorhergehende `lock`? Warum macht der DAV-Connector nach move _kein_ unlock? Oder auch, gehört das ganze Thema nicht eigtl nach ZO-4886, wenn wirs eh schon raustrennen?

2024-03-05 15:47 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +            authentication = None
Ich persönlich würde ja überall early `return False`, statt if und try/else zu verketten, aber das ist vmtl Geschmackssache. :)

2024-03-05 16:27 UTC, louika commented on core/src/zeit/connector/connector.py
> +        self._invalidate_cache(id)
genau, ist ein rebase-Artefakt.

2024-03-05 16:51 UTC, louika commented on core/src/zeit/connector/connector.py
> +        self._invalidate_cache(id)
prima, zwei rote Tests :/

2024-03-06 09:25 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +    OTHERS_LOCK = 1
mein persönlicher Favorit wäre der zweite, `LockStatus.NONE|OWN|FOREIGN` :)

2024-03-06 10:31 UTC, louika commented on core/src/zeit/connector/connector.py
> +        self._invalidate_cache(id)
der Grund für die roten Tests ist, dass in `48a63e0d5 ZO-4267: implement lock, unlocked and locked for postgresql connector` das [invalidate](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/connector/tests/test_contract.py#L290) aus dem Test fliegt.

2024-03-07 09:31 UTC, louika commented on core/src/zeit/connector/connector.py
> +        self._invalidate_cache(id)
done ✅

2024-03-07 12:27 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +        self.unlock(new_id)
das unlock spiegelt das aktuelle Verhalten vom DAV. Ich verstehe nicht wo es genau passiert, aber ein move entfernt beim DAV das Lock.

2024-03-07 14:59 UTC, louika commented on core/src/zeit/connector/postgresql.py
> +        self.session.execute(stmt)
ist im followUp Ticket [ZO-4881](https://zeit-online.atlassian.net/browse/ZO-4881) enthalten

2024-03-07 15:11 UTC, louika commented on core/src/zeit/connector/postgresql.py
> +            return (None, None, False)
der DAV erlaubt es nicht-existierende Objekte zu locken, deshalb wird der `KeyError` auch [hier](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/connector/connector.py#L421-L424) explizit gefangen und ist valide, das ist seit Implementierung so. Entsprechend haben wir das umgesetzt und das Interface entsprechend geändert. Was wäre dein Vorschlag, neues Ticket anlegen und Verhalten nach Ablöse des DAVConnectors anpassen?

2024-03-07 15:13 UTC, louika commented on core/src/zeit/connector/postgresql.py
> +        new_resource = Resource(
wir haben hier das `add` in content abhängige `_add` Funktionen aufgespalten, sodass das entsprechend funktioniert. hat uns aber nicht wirklich glücklich gemacht. Was hälst du davon?

2024-03-08 08:12 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +            return (None, None, False)
Richtig. Völlig richtig. Was dann heißt, wir haben hier in Wirklichkeit ein ganz anderes Thema, nämlich nicht "kann man das nicht noch etwas einfacher aufschreiben", sondern "wie behandeln wir Locking von gerade-neu-anzulegenden Objekten". Das kommt dann wohl auch nach ZO-4886.

2024-03-08 08:12 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        self.session.execute(stmt)
Dieser Punkt hat mit "wie gestalten wir die foreign keys" (4881) eigentlich nichts zu tun, sondern mit "wie benutzen wir sqlalchemy orm so, dass es uns am meisten hilft". (Die aktuelle Formulierung macht zb völlig unnötig eine zweite DB-Query.) Aber dieser PR enthält eh schon so viele Baustellen, die wir meiner Meinung nach in ihrer aktuellen Form eigentlich überhaupt nicht auf main committen sollten, da macht dann eine weitere auch keinen Unterschied mehr.

2024-03-08 08:12 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        self.unlock(new_id)
Interessant, was DAV so tut. Danke für die Erläuterung. (Ich finde immernoch, das würde eigtl nicht hierher gehören, sondern nach 4886, aber sei's drum).

2024-03-08 08:13 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        new_resource = Resource(
jo, ne, das machts nicht besser, seh ich genauso. außerdem fehlt noch mehr. Ich habe ZO-4915 und ZO-4916 dafür angelegt.

2024-03-08 08:55 UTC, merged