ZO-4886: check locking
ZeitOnline/vivi pull request #656
Opened 2024-03-12 15:58 UTC by louika

### Checklist

- [ ] Documentation
- [x] Changelog
- [x] Tests
- [ ] ~~Translations~~

### gif
![aaaaaaah](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcmRuczRvOHcwcDdqZGxqYjd3cDFzcTc5ZDF3ZjA0MjY1c2QzanAyeiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/h8zDn6oE4TLfq/giphy.gif)

2024-03-14 14:57 UTC, stollero reviewed
Merci 🙇 Da ist noch eine wichtige Frage dabei, aber vielleicht übersehe ich auch was, ist schon spät

2024-03-14 14:57 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +    id = Column(Uuid(as_uuid=False), ForeignKey('properties.id'), primary_key=True)
🤦 da schreibt man schon im DB Schema das es eine 1:1 Beziehung ist und dann fehlt es einfach im Code. Man ey ... aber gut das du den Fehler beseitigt hast 👍 nice

2024-03-14 14:57 UTC, stollero commented on core/src/zeit/connector/postgresql.py
>          self.add(resource)
Mir fällt auf das `add` als öffentliche Methode ja auch von außen aufgerufen werden kann und da wir in `add` nicht meckern, falls die ID bereits existiert könnten wir am Lock vorbei eine Objekt aktualisieren. 😨 

Gilt dann wohl auch für `changeProperties`.

Was denkst du?

2024-03-15 08:36 UTC, wosc requested changes

2024-03-15 08:36 UTC, wosc commented on core/src/zeit/connector/mock.py
> +        if id in self._locked and self._locked[id][0] != 'zope.user':
Man müsste doch jeweils `self.locked()` aufrufen und `mylock` prüfen können, statt die Implementierung davon zu kopieren, oder?

2024-03-15 08:36 UTC, wosc commented on core/src/zeit/connector/postgresql.py
>          self.add(resource)
Der Lock-Check muss definitiv nach `add` und nicht (nur) `setitem`. Und genau, `changeProperties` muss ebenfalls das Lock prüfen.

2024-03-15 08:36 UTC, wosc commented on core/src/zeit/connector/tests/test_contract.py
> +    def test_setitem_must_not_write_on_locked_object(self):
Was wir hier doch haben ist, "für folgende Methoden (add, set, del, move, changeprop): wenn ich selber das Lock habe gehts, ansonsten raise LockedByOther". Bzw evtl noch nen dritten Fall "wenn kein Lock existiert gehts natürlich auch"? (Und dann noch "copy geht immer", der Vollständigkeit halber.)

Ob man daraus gleich ein full-blown "parametrize" machen kann/will, weiß ich nicht, aber zumindest die Test-Namen könnte man doch einheitlich strukturieren.

2024-03-15 08:36 UTC, wosc commented on core/src/zeit/connector/postgresql.py
>          self.add(resource)
Und es fehlt noch ein Kontrakt/Test, nämlich: "zwei Leute können nicht gleichzeitig unter demselben Pfad ein Objekt anlegen". Der DAV-Connector implementiert das, indem er sich [temporär ein Lock holt](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/connector/connector.py#L534); im SQL-Connector könnte es gut sein, dass die Datenbank-Keys das jedenfalls schonmal _verhindern_ beim Commit (ob eine hilfreiche Exception dabei rauskommt, ist allerdings eine andere Frage).

2024-03-15 10:47 UTC, louika commented on core/src/zeit/connector/postgresql.py
>          self.add(resource)
erfüllt dieser [Test](https://github.com/ZeitOnline/vivi/blob/4117e21be996cdefb7cc03fcd9867633bab7d79b/core/src/zeit/connector/tests/test_contract.py#L353) die Anforderungen?

2024-03-15 15:51 UTC, louika commented on core/src/zeit/connector/tests/test_contract.py
> +    def test_setitem_must_not_write_on_locked_object(self):
ich habe das parametrize nicht sinnvoll mit den funtions und dann der ganze TestContracXYZ Logik verheiratet bekommen, und daher nur etwas vereinfacht und unbenannt.

2024-03-18 13:18 UTC, wosc commented on core/src/zeit/connector/postgresql.py
>          self.add(resource)
Nein, das deckt den Fall nicht ab, den ich meine. Der wird vmtl auch "lustig" als Test aufzuschreiben, weil man zwei parallel ablaufende Transaktionen braucht, um das zu zeigen:

```
t1: add(/foo)
t2: add(/foo)
t1: commit -> ok
t2: commit -> sollte einen nachvollziehbaren Fehler bekommen
```

2024-03-19 14:08 UTC, louika commented
die `zeit/workflow/browser/tests` sind lokal alle grün. #selenium

2024-03-19 14:15 UTC, louika commented
`vivi.core.src.zeit.content.article.edit.browser.tests.test_recipelist.FormLoader` ist lokal auch grün

2024-03-19 14:45 UTC, louika commented on core/src/zeit/connector/postgresql.py
>          self.add(resource)
können wir diesen Test hinterher schieben, in einem weiteren PR?

2024-03-20 09:07 UTC, wosc requested changes

2024-03-20 09:07 UTC, wosc commented on core/src/zeit/connector/testing.py
> +    def listCollection(self, id):  # XXX Why is this a generator?
Das ist eine Optimierung: Der hauptsächliche Usecase ist `for x in`, dafür muss mans also nicht erstmal vorher aufsammeln, sondern kann _einmal_ drüberlaufen. Insofern frage ich mich, wo uns das denn auf die Füße fällt, dass es keine Liste ist?

(Andererseits, die Mengen, um die es geht, sind meistens ja ziemlich überschaubar, insofern könnte man es auch generell auf Liste umstellen, wenn das sehr störend sein sollte.)

2024-03-20 09:07 UTC, wosc commented on core/src/zeit/connector/tests/test_contract.py
> +    copy_inherited_functions(zeit.connector.testing.ConnectorTest, locals())
Das sollte eigtl unnötig sein. Rumkopieren muss man AFAIU nur `test_*` Funktionen, weil pytest sonst mit den Layers durcheinanderkommt. Hilfsfunktionen sollten davon aber nicht betroffen sein.

2024-03-20 10:25 UTC, wosc commented on core/src/zeit/connector/postgresql.py
>          self.add(resource)
Bei näherer Betrachtung stellt sich allerdings raus, das Fass ist vmtl größer als nur "wir prüfen mal Locks". Der ursprüngliche Ausgangspunkt war ja, "in DAV ist in setitem ne Sonderbehandlung dafür, dieses Verhalten brauchen wir in SQL halt auch" -- aber vmtl gilt das gleiche (man darf nicht gleichzeitig) genauso auch für copy+move, wo grade gar nicht so klar ist, wie DAV sich dazu verhält. Insofern ist es zum drüber Nachdenken evtl doch einfacher, es rauszutrennen --> ZO-4978

2024-03-20 10:36 UTC, louika commented on core/src/zeit/connector/postgresql.py
>          self.add(resource)
Thema besprochen und neues [Ticket](https://zeit-online.atlassian.net/browse/ZO-4978?atlOrigin=eyJpIjoiZTdjYzdkMTUzYzllNGVhMmI3OGZjZGIxZmQxOTJiNWYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ) erstellt.

2024-03-20 12:02 UTC, louika commented on core/src/zeit/connector/testing.py
> +    def listCollection(self, id):  # XXX Why is this a generator?
ich schau mal, was der Grund hier ist. Habe die Funktion eigentlich nur von rechts nach links kopiert.

2024-03-20 12:49 UTC, louika commented on core/src/zeit/connector/testing.py
> +    def listCollection(self, id):  # XXX Why is this a generator?
wir testen in im Contract in `test_delitem_collection_raises_error_if_children_are_locked` und in `test_listCollection_returns_name_uniqueId_pairs` ob der Ordner leer ist `self.assertEqual([], self.listCollection('http://xml.zeit.de/testing'))`. und weiteren Test, ob bestimmte Fehler auftreten. Wenn man dann das Generatorobjekt in der Hand hat, dann bekommt man den Fehler nicht. Also ist das hier reine Convenience für die Tests. Würde ich so belassen.

2024-03-20 14:13 UTC, louika commented on core/src/zeit/connector/mock.py
> +        my_lock = not lock_is_foreign(principal)
so rum https://github.com/ZeitOnline/vivi/pull/656/commits/ca12e53c338e0fbcfc529686bb0727352286a9d6?

2024-03-20 15:22 UTC, wosc requested changes

2024-03-20 15:22 UTC, wosc commented on core/src/zeit/connector/mock.py
> +        if id in self._locked and not mylock:
Sorry wenn ich da so drauf rumreite. Aber die korrekte Prüfung auf dieser Ebene ist `if principal is not None`. Damit man eben nicht überall hinkopiert, wie der Lock-Storage hier implementiert ist.

2024-03-20 15:22 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +        status = self._get_lock_status(resource.id)
Das ist hier überflüssig, oder? Es wird ja direkt `add()` aufgerufen, und der prüft das Lock.

2024-03-20 15:22 UTC, wosc commented on core/src/zeit/connector/testing.py
> +    def listCollection(self, id):  # XXX Why is this a generator?
Hrm. Also wegen 2 Stellen find ichs sowieso schon fraglich (kann man doch auch im assert halt `list()` drumrumschreiben), aber da sich das ja nur auf die ContractTests bezieht, find ichs definitiv nicht sinnvoll, das auf die allgemeine TestCase-Basisiklasse draufzupacken.

2024-03-20 15:22 UTC, wosc commented on core/src/zeit/connector/tests/test_contract.py
> +    copy_inherited_functions(zeit.connector.testing.MockTest, locals())
Auch dafür gilt https://github.com/ZeitOnline/vivi/pull/656#discussion_r1531716241

2024-03-20 15:22 UTC, wosc commented on core/src/zeit/connector/tests/test_contract.py
> +    copy_inherited_functions(zeit.connector.testing.SQLTest, locals())
Und hier auch

2024-03-20 15:22 UTC, wosc commented on core/src/zeit/connector/testing.py
> +    def lock_resource(self, name, user, **kw):
Das wird doch nur in `ContractLock` verwendet, dann reicht es doch, es dort hinzutun, muss nicht auf die allgemeine Basisklasse drauf.

2024-03-20 15:40 UTC, louika commented on core/src/zeit/connector/testing.py
> +    def listCollection(self, id):  # XXX Why is this a generator?
in Ordnung, habs zurückgeschoben.

2024-03-20 16:17 UTC, louika commented on core/src/zeit/connector/mock.py
> +        if id in self._locked and not mylock:
Warum ist es lediglich notwendig ist, zu prüfen, ob die Resource von irgendjemandem gesperrt ist? Dann müsste auch konsequenterweise ein `LockingError` anstelle des `LockedByOtherSystemError` geworfen werden. Weil nicht klar ist, ob es wirklich nicht der eigene `principal` ist. Das hat direkt Auswirkungen auf die ContractTests `test_add_on_foreign_locked_resource_raises` und `test_setitem_on_foreign_locked_resource_raises`. 
`setitem` mit eigenem Lock soll funktionieren. Ich habe hierfür nochmal einen Test hinzugefügt.

2024-03-20 16:18 UTC, louika commented on core/src/zeit/connector/mock.py
> +        if id in self._locked and not mylock:
siehe 566f5ee93

2024-03-21 07:32 UTC, wosc commented on core/src/zeit/connector/mock.py
> +        if id in self._locked and not mylock:
Evtl haben wir uns grade missverstanden? Worauf ich rauswill ist: Bitte `locked()` aufrufen, und dessen Rückgabewert(e) auswerten. Sonst nichts, insb nicht `self._locked` betrachten. (Und na klar wird man da das `mylock` anschauen wollen.)

2024-03-21 09:05 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWU5eTRweXZqendrZDZ0YzF2eXRjZXFuanRibG9wNTA1ZWxuamw4MCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/E0KmHELTpq9pK/giphy.gif)

2024-03-21 09:06 UTC, merged