ZO-4917: implementation of locking timeout
ZeitOnline/vivi pull request #657
Opened 2024-03-18 07:02 UTC by stollero

### Checklist

- [ ] ~~Documentation~~
- [x] Changelog
- [x] Tests
- [ ] ~~Translations~~

### gif
![]()

2024-03-18 09:56 UTC, wosc requested changes

2024-03-18 09:56 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +            transaction.commit()
Mitten im Domain-Code darf man die Transaktion nicht anfassen, das passiert immer "weiter außen", im Framework (Web/Celery/etc) oder CLI-Skript, oder sowas.

2024-03-18 09:56 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +            self.session.delete(lock)
Eine eigentlich lesende Operation hinter den Kulissen doch schreibend zu machen, kann zu unerwartetem Verhalten führen ("warum ist das so langsam, das liest doch nur?").

Die Frage ist außerdem, ob wir nicht sowieso zusätzlich einen Aufräum-Cronjob bräuchten (denn sonst bleiben Locks, deren Status halt nie wieder angefragt wird, für immer in der DB liegen), und dann wäre "on the fly" aufräumen gar nicht mehr nötig. (Wobei ich zugebe, dass ein weiteres bewegliches Teil an der Stelle sich etwas nervig anfühlt. Aber ich glaub wir kommen nicht drumrum, oder?)

2024-03-18 09:56 UTC, wosc commented on core/src/zeit/cms/locking/browser/tests/test_lock.py
> +        self.created = time.mktime(datetime(year, 4, 15, 18, 20, tzinfo=pytz.UTC).timetuple())
Was wir damals vmtl noch nicht wussten, als dieser Test geschrieben wurde: doch, man [kann datetime patchen](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/cms/testing.py#L1209), es ist nur mechanisch etwas umständlich. Aber wir haben das ja gekapselt, sodass der jeweilige Test prima lesbar bleibt. Stell den Test hier insofern lieber auf `with clock()` um.

2024-03-18 12:55 UTC, stollero commented on core/src/zeit/cms/locking/browser/tests/test_lock.py
> +        self.created = time.mktime(datetime(year, 4, 15, 18, 20, tzinfo=pytz.UTC).timetuple())
Quadratisch, praktisch, gut :)

2024-03-19 13:27 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +            self.session.delete(lock)
Nach Rücksprache, machen wir noch einen einfachen cronjob, PR für vivi deployment folgt.

2024-03-20 08:22 UTC, wosc requested changes

2024-03-20 08:22 UTC, wosc commented on core/src/zeit/connector/tests/test_postgresql.py
> +            if i % 2 == 0:
Das find ich etwas schwierig zu lesen. Könnte man evtl eine `_create_lock(minutes)` Hilfsfunktion einführen, und die 2x aufrufen? ("2 wird zu 1" müsste doch genau so gut sein wie "4 wird zu 2", oder entgeht mir was?)

```python
self._create_lock(5)
self._create_lock(-10)
```

2024-03-20 08:22 UTC, wosc commented on core/src/zeit/connector/postgresql.py
> +    stmt = delete(Lock).where(Lock.until < datetime.now(pytz.UTC))
Will man da evtl einen "Sicherheitsabstand" einbauen, damit man nicht "aktuellen" Locks auf die Füße tritt, die womöglich "jetzt grade" sowieso jemand unlocken will? (Wobei die Frage dann ist, was ein guter Abstand wäre, dh wie lange Locks typischerweise gehalten werden vs für wie lang sie deklariert werden.)

2024-03-21 08:44 UTC, stollero commented on core/src/zeit/cms/testing.py
> +        dt = original.now(pytz.UTC)
time-machine ist gut 👍

2024-03-21 09:39 UTC, stollero commented on core/src/zeit/connector/tests/test_contract.py
> +        self.assertEqual((None, None, False), self.connector.locked(id))
Ja, geben wir mal extra 100ms. Nicht das hier noch ein weiterer Wackeltest entsteht

2024-03-21 09:47 UTC, stollero commented on core/src/zeit/connector/tests/test_postgresql.py
> +            if i % 2 == 0:
Ne, ist richtig. Mach ich

2024-03-21 14:11 UTC, stollero commented on core/src/zeit/connector/postgresql.py
> +    stmt = delete(Lock).where(Lock.until < datetime.now(pytz.UTC))
Die Wahrscheinlichkeit das ein Unlock zur gleichen Zeit wie der cronjob , welcher nur 1x am Tag triggered, passiert ist extrem gering.

2024-03-25 13:48 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDY4ZHl0ZXU0bmwxdHFlajVsdHZrbDlqeXNqOGU4MXF1a3l1cm85dyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2PC8rzUHZ4PPa/giphy.gif)

2024-03-25 13:48 UTC, merged