ZO-4726: Adds summy publish task
ZeitOnline/vivi pull request #661
Opened 2024-03-20 13:22 UTC by AWieczorreck

Dieser PR fügt einen weitere Publish-Task hinzu, der eine Payload an den Publisher schickt, die von [diesem Summy PR](https://github.com/ZeitOnline/summy/pull/22) ausgewertet wird.
In der Payload sollten immer die Keys `uuid, uniqueId, summy` vorhanden sein.
Ein ignorierter Artikel hat ein leers Objekt also summy-Key in der Payload: `"summy": {}`

### Checklist

[Dazugehöriger Deployment-PR](https://github.com/ZeitOnline/vivi-deployment/pull/897)

Ticket: [ZO-4726](https://zeit-online.atlassian.net/browse/ZO-4726)

- [ ] Documentation
- [X] Changelog
- [X] Tests
- [ ] Translations

### gif
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeWR1dnI5M3BzNDUzbzVtdTJkaDczeWdkYmRxZTlwYWlxcXl3cjV3eiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1flAwtHCYosL6LWnHr/giphy-downsized.gif)

2024-03-20 16:37 UTC, witsch approved these changes
Für mich sieht das soweit okay aus, aber eventuell möchte nochmal ein:e vivi Expert:in drüberschauen? 😊

2024-03-21 07:21 UTC, stollero requested changes
Danke für die Umsetzung, ein paar kleinere Anmerkungen sind vorhanden :) 👍

2024-03-21 07:21 UTC, stollero commented on core/src/zeit/workflow/publish_3rdparty.py
> +                return True
Hier würden wir das gerne in eine Subfunktion auslagern, damit wir nicht immer wieder das gleiche machen müssen :)

Weiter oben macht die Klasse `Speechbert` auch schon das gleiche, perfekt um es zusammenzuführen :)

2024-03-21 07:21 UTC, stollero commented on core/src/zeit/workflow/publish_3rdparty.py
> +            body.append({'content': ' '.join([x.strip() for x in text]), 'type': elem.tag})
Das gehört eigentlich in den Artikel, ``core/src/zeit/content/article/article.py``. Vielleicht magst du dem `Article` eine Funktion spendieren :)

Ach hier, Speechbert hat den gleichen Code bereits. Können wir dann gleich mal aufräumen ;)

2024-03-21 07:21 UTC, stollero commented on core/src/zeit/connector/testcontent/zeit-magazin/wochenmarkt/rezept
> +    <attribute ns="http://namespaces.zeit.de/CMS/document" name="avoid_create_summary">no</attribute>
Können wir vielleicht das Setting ``avoid_create_summary`` umbennen in ``create_summary``? Eigentlich haben wir in Vivi immer keine Negation der Einstellungen. Das würde uns freuen, Danke

2024-03-21 08:09 UTC, stollero commented on core/src/zeit/workflow/publish_3rdparty.py
> +            ignore_genres = config.get('summy-ignore-genres', '').lower().split()
Bitte die settings dokumentieren 🙇, kann natürlich auch in der summy Dokumentation erfolgen in `Betriebshandbuch-Konfiguration` 

Ich bedanke mich

2024-03-21 09:10 UTC, AWieczorreck commented on core/src/zeit/connector/testcontent/zeit-magazin/wochenmarkt/rezept
> +    <attribute ns="http://namespaces.zeit.de/CMS/document" name="avoid_create_summary">no</attribute>
[Das Ticket dazu](https://zeit-online.atlassian.net/browse/ZO-4724) wollte aber eine Negierung haben.
Müsste dann die dazugehörige Check auch umdrehen (von "Keine Zusammenfassung erstellen" in "Zusammenfassung erstellen"). Ich frage mal ob das auch umgedreht werden kann.

2024-03-21 11:37 UTC, AWieczorreck commented on core/src/zeit/workflow/publish_3rdparty.py
> +            ignore_genres = config.get('summy-ignore-genres', '').lower().split()
Kommt in vivi-deployment PR dazu

2024-03-21 14:09 UTC, stollero approved these changes

2024-03-21 14:09 UTC, merged

2024-03-21 17:41 UTC, witsch commented on core/src/zeit/workflow/publish_3rdparty.py
> +        ]
Also ich find' ja die [Variante aus d0082987 wäre zwar hübscher gewesen](https://github.com/ZeitOnline/vivi/pull/661/commits/d0082987ac63f8eab8991b47d8bd79da1bfd5c74#diff-95cfbfb389e9e904700a4567f290e20077e7e604c0cec4336159353962cd54cbL324-R324), aber nun ja… 😅

2024-03-22 07:04 UTC, stollero commented on core/src/zeit/workflow/publish_3rdparty.py
> +        ]
Stimmt, https://github.com/ZeitOnline/vivi/pull/662/commits/af4ba821ca9e211c70ca7fb2b0b8ae4449a9cfd1