ZO-4666: fix to save checkbox value for mobile images
ZeitOnline/vivi pull request #681
Opened 2024-04-03 13:43 UTC by thomasbaumann

### Checklist

- [ ] Documentation
- [ ] Changelog
- [ ] Tests
- [ ] Translations

### gif
![]()

2024-04-12 11:40 UTC, wosc requested changes

2024-04-12 11:40 UTC, wosc commented on core/src/zeit/content/cp/blocks/block.py
> +    force_mobile_image = zeit.cms.content.property.ObjectPathAttributeProperty(
Ne, das muss in die blocks/automatic.py. Ich hatte wohl in 7e1992b da zu viel rausgerissen.

2024-04-12 11:40 UTC, wosc commented on core/src/zeit/cms/content/property.py
> +        if value is None or value == 'False':
Das wirkt falsch. (Und sollte für die anliegende Aufgabe auch unnötig sein.)

2024-04-12 11:48 UTC, thomasbaumann commented on core/src/zeit/cms/content/property.py
> +        if value is None or value == 'False':
Achso... das hatte ich ja noch gefragt, weil mein (und auch Martins) Eindruck war, dass das falsch wirkt... Es hat aber (zumindest meinem Eindruck nach) das Problem gelöst, dass das Häkchen immer wieder gesetzt ist, nachdem man es entfernt und auch im XML 'False' steht.

2024-04-12 15:12 UTC, thomasbaumann commented on core/src/zeit/cms/content/property.py
> +        if value is None or value == 'False':
Okeee... wenn ich `force_mobile_image` in `blocks/automatic.py` packe, dann fluppt's - nämlich _auch_, dass das Häkchen nicht immer wieder gesetzt ist _und_ ich nicht diese falsch wirkende `False`-Sache brauche. Und ohne die, funktioniert auch der Test.

2024-04-23 05:33 UTC, merged

2024-04-23 07:44 UTC, thomasbaumann commented
👍 https://github.com/ZeitOnline/vivi/compare/d2cf0e658be9c542b80db4fc410004442f108190..28b4281c0894e1d235c903d01969388d136c2082