ZO-5050: read facebook credentials from secret store instead of config file
ZeitOnline/vivi pull request #684
Opened 2024-04-04 05:42 UTC by stollero

…

### Checklist

- [ ] Documentation
- [x] Changelog
- [ ] Tests
- [ ] Translations

### gif
![]()

2024-04-08 13:21 UTC, wosc requested changes
Insgesamt sauber und nachvollziehbar, und eine nette Idee mit dem named Utility. Ich glaube/fürchte, an einer Stelle passt es noch nicht (siehe Kommentar unten).

2024-04-09 05:58 UTC, stollero commented on core/src/zeit/push/message.py
> +        service = self.push.get(type='facebook', account='fb-main')
Ach, du hast Recht 😭. Etwas umständlicher nun den Token zu erhalten.

2024-04-09 09:41 UTC, wosc requested changes

2024-04-09 09:41 UTC, wosc commented on core/src/zeit/push/facebook.py
> +        for account in zope.component.getAllUtilitiesRegisteredFor(
Wenn es keinen passenden Account findet, wurde der Request vorher trotzdem ausgeführt, mit `invalid` als Token, also (sichtbarem) Fehler. Das sollten wir denke ich beibehalten.

Und frag ich mich ja, ob man dem `SocialConfig` nicht 2 Klassenmethoden verpassen will, `for_type` und `for_name` (oder ein anderes Naming ;), sodass man die ZCA-Besonderheiten nicht im ganzen Client-Code verstreuen muss.

2024-04-10 09:34 UTC, stollero commented on core/src/zeit/push/facebook.py
> +        for account in zope.component.getAllUtilitiesRegisteredFor(
Danke für deinen Hinweis,

ich habe die Klasse jetzt nicht in mit in `FacebookConfig` gepackt, da wir sonst Probleme mit dem zirkulärem Import bekommen. Hoffe es passt 😄

2024-04-10 13:52 UTC, wosc requested changes

2024-04-10 13:52 UTC, wosc commented on core/src/zeit/content/article/edit/browser/tests/test_push.py
> -            {'account': 'fb-test', 'enabled': 1, 'override_text': 'fb-main', 'type': 'facebook'},
Sorry für die Tendenz zur unendlichen Geschichte, aber: Muss man die Tests wirklich anfassen? (Nicht nur hier, kommt weiter unten auch noch paarmal.) Der resultierende String sollte doch genau der gleiche wie vorher sein, das ist doch genau der Witz, oder?

(Man kann dann sicherlich nochmal diskutieren, wann man in Tests Literale und wann Variablen/Referenzen verwenden will/soll für den "expected" Teil der Assertions, aber das würd ich für den PR hier lieber weglassen, bzw wenn dann mind in einen separaten Commit trennen.)

2024-04-10 13:52 UTC, wosc commented on core/src/zeit/push/interfaces.py
> +class SocialConfig:
Ah ja, Kreisimport, verstehe. Good catch!

2024-04-11 06:33 UTC, wosc requested changes
Danke fürs Nachziehen! Dabei hat sich allerdings ein copy&paste Problem eingeschlichen. :)

2024-04-11 06:33 UTC, wosc commented on core/src/zeit/content/article/browser/breaking.py
> +                    'account': 'fb-test',
Das hier ist leider kein Test, sondern echter Code, der muss `SocialConfig` verwenden.

2024-04-11 06:33 UTC, wosc commented on core/src/zeit/push/facebook.py
> +            log.debug('Sending %s, %s to %s', text, link, account)
Hmm, _schicken_ tun wir den Request immer, auch wenn wir keine Token haben, insofern sollte die Logmeldung vmtl außerhalb des if?

2024-04-11 06:36 UTC, stollero commented on core/src/zeit/content/article/browser/breaking.py
> +                    'account': 'fb-test',
Uff hatte ich doch geändert, uargh muss beim rebase nicht aufgepasst.

2024-04-11 07:07 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWptMjB6bjNrdnZ0a2h1aWJ0YmdydXR5Y3Bma2V4cGR5N29tcXBwayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fQ293BB62WNwn2PaDU/giphy.gif)

2024-04-11 07:08 UTC, merged