ZO-5192: Report complete video url to google pub/sub
ZeitOnline/vivi pull request #737
Opened 2024-05-07 15:38 UTC by louika

[zeit.web](https://github.com/ZeitOnline/zeit.web/blob/main/src/zeit/web/core/template.py#L763-L765) baut sich Video URLs aus dem seo-slug und der uniqueId zusammen, genau so wie die [PushURL](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/content/video/video.py#L158-L161).

### Checklist

- [ ] ~~Documentation~~
- [x] Changelog
- [x] Tests
- [ ] ~~Translations~~

### gif
![waiting](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXNrZmgyNzNndGZyeG1pa3B4Mzk2dmZyYmthbDZlMXVuZWJrNjc4aCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l3ZrVw8NkxIly/giphy.gif)

2024-05-08 06:12 UTC, wosc requested changes

2024-05-08 06:12 UTC, wosc commented on core/src/zeit/content/video/interfaces.py
> +    _url = zope.schema.URI(title=_('URL'), required=False)
Dem fehlt noch ein `readonly=True`.

2024-05-08 06:12 UTC, wosc commented on core/src/zeit/content/video/interfaces.py
> +    _url = zope.schema.URI(title=_('URL'), required=False)
Finden wir noch einen klareren Namen? `full_url`, `seo_url`, `public_url` ...?

2024-05-08 06:12 UTC, wosc commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +    def test_video_bigquery_is_published(self):
eher `_contains_seo_slug_in_url` oder? ;)

2024-05-08 06:12 UTC, wosc commented on core/src/zeit/workflow/publish_3rdparty.py
> +    def publish_json(self):
Es gibt sogar schon `BigQueryMixin.live_url`, das sollte man hier überschreiben/anpassen.

2024-05-08 06:12 UTC, wosc commented on core/src/zeit/workflow/tests/test_publish_3rdparty.py
> +        assert json['properties']['meta']['url'] == ('http://xml.zeit.de/video/seo-slug-cookies')
Das ist ziemlich sicher nicht das gewünschte, sondern `https://www.zeit.de/...`, vgl `BigQueryMixin.live_url`

2024-05-10 08:58 UTC, louika commented on core/src/zeit/content/video/interfaces.py
> +    _url = zope.schema.URI(title=_('URL'), required=False)
fand schon den Namen `url` sehr grenzwertig, weil es zu diesem Zeitpunkt noch eine uniqueId plus dem seo slug ist.  `public_url_base`?

2024-05-10 09:42 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2lrNm5wYTc0czFjZmxmb3dxbzRoN3B1c2Z4eG9uOGNheTVzY2x0cSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fQ293BB62WNwn2PaDU/giphy.gif)

2024-05-10 09:42 UTC, merged