Zo 4274 dont copy meta data
ZeitOnline/vivi pull request #756
Opened 2024-05-23 16:04 UTC by louika

### Checklist

- [ ] Documentation
- [ ] Changelog
- [ ] Tests
- [ ] Translations

### gif
![]()

2024-06-25 13:46 UTC, wosc requested changes
Ein ganz schöner Ritt. :)

2024-06-25 13:46 UTC, wosc commented on core/src/zeit/cms/checkout/tests/test_helper.py
> +                co.xml.replace(co.xml.find('body'), lxml.etree.fromstring('<body>foo</body>'))
Das sollte überflüssig sein? Der Mock-Connector basiert seinen Conflict-Check doch nur auf der `DAV:etag` Property. (Was keine besonders saubere Implementierung ist, aber wir wollen perspektivisch ja eh ZO-4530 und daher eher nicht den Mock-Connector noch groß verbessern.)

2024-06-25 13:46 UTC, wosc commented on core/src/zeit/cms/checkout/browser/conflict.txt
> +Change content:
Sollte auch überflüssig sein.

2024-06-25 13:46 UTC, wosc commented on core/src/zeit/cms/checkout/tests/test_manager.py
> +        del self.repository['testcontent']
Ich fürchte ich steh auf dem Schlauch: Was will dieser Test testen? Auch die Commit-Message von e1148aa erhellt mich nicht wirklich.

2024-06-25 13:46 UTC, wosc commented on core/src/zeit/content/article/README.txt
> +We change some attributes now and see that the changes are partly reflected in the
Yo ne. Nix mehr wird ins XML kopiert. Der ganze Abschnitt ist überflüssig.

Genauer gesagt, die ganze doctest-Datei ist überflüssig. Wenn ich es richtig sehe, sind die einzigen zwei interessanten Schnipsel, dass a) textLength automatisch gesetzt wird und b) es die ISearchableText Funktionalität gibt. Lass uns doch lieber für die beiden kurze Unit-Tests schreiben, und die readme.txt dann löschen.

2024-06-26 05:46 UTC, stollero commented on core/src/zeit/cms/checkout/tests/test_manager.py
> +        del self.repository['testcontent']
Ich stell mich mal mit auf den Schlauch 🤔

2024-06-26 06:42 UTC, stollero commented on core/src/zeit/cms/checkout/tests/test_helper.py
> +                co.xml.replace(co.xml.find('body'), lxml.etree.fromstring('<body>foo</body>'))
Der mock Connector schaut tatsächlich auch auf den Inhalt: https://github.com/ZeitOnline/vivi/blob/afb69f68a51e59482d86ab46b9acaad31e65df8d/core/src/zeit/connector/mock.py#L121

2024-06-26 08:01 UTC, wosc commented on core/src/zeit/cms/checkout/tests/test_helper.py
> +                co.xml.replace(co.xml.find('body'), lxml.etree.fromstring('<body>foo</body>'))
Tatsache. Danke, das hatte ich nicht auf dem Schirm.

2024-06-26 08:02 UTC, wosc commented on core/src/zeit/cms/checkout/tests/test_manager.py
> +        del self.repository['testcontent']
Okay, dann entferne ich den Commit erstmal.

2024-06-26 08:02 UTC, wosc commented on core/src/zeit/cms/checkout/tests/test_manager.py
> +        del self.repository['testcontent']
@louika kannst du uns hier evtl erhellen?

2024-06-26 08:30 UTC, wosc commented on core/src/zeit/cms/checkout/tests/test_manager.py
> +        del self.repository['testcontent']
Ha. Ich glaub ich habs gefunden, der Test war früher mal ein doctest https://github.com/ZeitOnline/vivi/blob/ZO-4274_dont_copy_meta_data/core/src/zeit/cms/content/xmlsupport.txt#L75-L83

2024-06-26 10:26 UTC, merged