ZO-4617: allow only imagegroups in teasers
ZeitOnline/vivi pull request #795
Opened 2024-07-03 11:24 UTC by thomasbaumann

### Checklist

- [ ] Documentation
- [ ] Changelog
- [ ] Tests
- [ ] Translations

### gif
![]()

2024-07-08 08:58 UTC, wosc requested changes

2024-07-08 08:58 UTC, wosc commented on core/src/zeit/content/image/interfaces.py
> -        if IImage.providedBy(value):
Jo. Das hier ist der Knackpunkt, um den es geht. Allerdings: indem der Sonderfall-Code hier entfernt wird, 
a) gehört auch der zugehörige "das ist nur für bw-compat" Kommentar entfernt
b) tut die ganze Methode nichts mehr außer super aufrufen, dh sie gehört insgesamt entfernt (denn sie wurde hier exakt nur deswegen überhaupt überschrieben, um diesen Sonderfall zu realisieren)

2024-07-08 08:58 UTC, wosc commented on core/src/zeit/workflow/publish.py
> +                        errormessage = zope.i18n.translate(_(args[0]), target_language='de')
Also _wenn_ wir den Code hier ändern, sollten wir einen Test haben, der uns zeigt, warum das relevant ist. Und wir sollten genauso die im Kommentar verlinkte Stelle anschauen/testen/korrigieren.

2024-07-08 10:07 UTC, thomasbaumann commented on core/src/zeit/content/image/interfaces.py
> -        if IImage.providedBy(value):
(a) Kommtentar: Stimmt
(b) hatte ich sogar erwogen, aber an einer Stelle Zweifel bekommen, ob ich mich nicht vergrabe. Ich schau nochmal.

2024-07-12 07:44 UTC, thomasbaumann commented on core/src/zeit/workflow/publish.py
> +                        errormessage = zope.i18n.translate(_(args[0]), target_language='de')
Wie gestern im Daily besprochen: erstmal ohne Test (inbs. die im Kommentar verlinkte Stelle). Ich habe mich nochmal vergewissert, dass die Stelle auch wirklich übersetzt wird wie gewünscht.

2024-07-12 08:44 UTC, louika commented on core/src/zeit/locales/de/LC_MESSAGES/zeit.cms.po
> +"X-Generator: Poedit 3.4.1\n"
poedit bei Gelegenheit updaten 😄

2024-07-12 08:46 UTC, louika commented on core/docs/changelog/ZO-4617.change
> +ZO-4617: do not allow IImage as teaser images anymore
vllt. eher "Only allow imagegroups as teasers, not single images"

2024-07-12 11:18 UTC, thomasbaumann commented on core/src/zeit/locales/de/LC_MESSAGES/zeit.cms.po
> +"X-Generator: Poedit 3.4.1\n"
Mach ich _jetzt_. Danke für den Hinweis :)

2024-07-12 11:19 UTC, thomasbaumann commented on core/docs/changelog/ZO-4617.change
> +ZO-4617: do not allow IImage as teaser images anymore
sry, wieder keine Notifications bekommen über deine Kommentare (zumindest nicht dort, wo ich hingucke: Slack). Deshalb erst jetzt geändert.

2024-07-12 11:20 UTC, thomasbaumann commented on core/docs/changelog/ZO-4617.change
> +ZO-4617: do not allow IImage as teaser images anymore
Äh... und da ist dann auch ncoh was schiefgegangen...?

2024-07-12 11:26 UTC, thomasbaumann commented on core/docs/changelog/ZO-4617.change
> +ZO-4617: do not allow IImage as teaser images anymore
jetzt aber...

2024-07-12 11:41 UTC, louika requested changes
leider sehe ich die Fehlermeldung nicht.
die Reproduktionsanleitung von Sonja (danke fürs weiterhelfen, Hippo!) besagt localhost:8080/repository/kultur/film/2023-10/matthew-perry-tod-friends-schauspieler-54-jahre versuchen zu publishen" veröffentlichen und dann auf `trotzdem veröffentlichen` klicken. dann sehe ich 
![Screenshot 2024-07-12 at 13 35 18](https://github.com/user-attachments/assets/14f8cf62-c884-4db5-afe9-fe5f301b63cf)
die Sprache von meinem Firefox ist auf deutsch. (Siehe zum Beispiel "Quelltext anzeigen" im Screenshot)
Ich habe ein frisches vivi-deployment.
Bitte nochmal schauen 🙏 oder mich korrigieren, vllt. habe ich einen Fehler bei der Reproduktion gemacht.
ok moment, celery restart versuche ich nochmal

2024-07-12 12:19 UTC, louika approved these changes
👍  tut nach Schluckauf
![yay](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcmc4amV5am1sbG1wczhxN3RiZWkzazhkdzlhODZ5ZjF2bHpoZjlmNSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xTiN0L7EW5trfOvEk0/giphy.gif)

2024-07-12 12:26 UTC, louika commented
ich merge jetzt, den Fix für die Englische Variante kann man bestimmt einfach hinterher schieben. Es war ja zu erwarten, dass die Fehlermeldung im Englischen Browser deutsch ist, da die `target_language` hardgecoded ist.

2024-07-12 12:29 UTC, merged