ZO-5737: modify print ressort form
ZeitOnline/vivi pull request #799
Opened 2024-07-08 08:23 UTC by Sinnaj94

Ticket: [ZO-5737](https://zeit-online.atlassian.net/jira/software/c/projects/ZO/boards/152?selectedIssue=ZO-5737)
- Ressort (Druck) zu Print-Ressort umbenannt
- Byline (Von-Zeile) entfernt

Es fehlt noch folgendes, daher zunächst als Draft: 

> Dropdown aus [contenthub-config](https://github.com/ZeitOnline/config/blob/main/contenthub/production/ir2vivi-printressorts.yaml)

### Checklist
- [ ] Documentation
- [ ] Changelog
- [ ] Tests
- [ ] Translations

### gif
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZXh6ZnBjMnR4ajdvODNtOG4zYTB1bzA0cGllcTZzcGJzd3BiazU5bCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/14wXMGbHjXK2k0/giphy-downsized.gif)

2024-07-11 08:54 UTC, wosc requested changes
Passt insgesamt, aber es hat 2 Test-Failures (auch nach Rerun noch ;)

2024-07-11 08:54 UTC, wosc commented on core/src/zeit/cms/browser/listing.py
> -    @zope.cachedescriptors.property.Lazy
Bitte die Commits in [logische Einheiten](https://docs.zeit.de/backend-team/standards/general.html#commits) einteilen, z.B.

* Print-Ressort schreibbar machen
* Übersetzung für Print-Ressort anpassen
* byline entfernen
* byline aus Übersetzungen rauswerfen (ich hab mir angewöhnt [bin/i18nextract etc](https://docs.zeit.de/vivi/development/translations.html#id1) in eigene Commits zu tun, denn das hilft enorm bei Merge-Konflikten)

2024-07-11 08:54 UTC, wosc commented on core/src/zeit/cms/content/interfaces.py
> +    printRessort = zope.schema.TextLine(title=_('Print ressort'), readonly=False, required=False)
`readonly=False` ist der Default, das schreiben wir nicht extra dazu.

2024-07-11 15:21 UTC, Sinnaj94 commented on core/src/zeit/cms/content/interfaces.py
> +    printRessort = zope.schema.TextLine(title=_('Print ressort'), readonly=False, required=False)
Done with [a97ce6d](https://github.com/ZeitOnline/vivi/pull/799/commits/a97ce6d2eaa9e19afcf9c3a1dcb2866bc6132c16)

2024-07-12 06:16 UTC, Sinnaj94 commented on core/src/zeit/cms/browser/listing.py
> -    @zope.cachedescriptors.property.Lazy
Mache ich nächstes mal gerne!

2024-07-12 07:53 UTC, Sinnaj94 reviewed
Nächstes mal mit mehr spezifischen Git-Commits 😁

2024-07-12 12:01 UTC, Sinnaj94 commented on core/src/zeit/cms/browser/listing.py
> -    @zope.cachedescriptors.property.Lazy
Hi Wolfgang, ich habe die Commit-Historie entsprechend angepasst.

2024-07-12 12:34 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExemV3MWV6dzM2dHVhMzQxNmkxemM4b2JzOHdzdjBmM3E0a3N4ZHh2cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/6whrgZbPXGJwrhwMAz/giphy.gif)

2024-07-12 13:41 UTC, merged