Fix repair image encoder parameters not loading
ZeitOnline/vivi pull request #815
Opened 2024-07-24 06:39 UTC by Sinnaj94

Es gab einen kleinen Typo beim Laden der `encoders.xml`, die für die Einstellungen der Kompression / Umwandlung für verschiedene Bildformate zuständig war. Dadurch wurde die Konfiguration nicht geladen, das wurde in diesem PR gefixt. Außerdem wurden Tests hinzugefügt.
### Checklist

- [ ] Changelog
- [ ] Tests

### gif
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExamNodGNkanY4eDAxZHRjYW8yc3psbTR5am5wODNucGo3Z2JlazJydCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/11JA9axStWivLUyhsB/giphy-downsized.gif)

2024-07-24 06:40 UTC, Sinnaj94 commented on core/src/zeit/content/image/tests/test_transform.py
> +    def test_encoder_parameters_configuration_loads_correctly(self):
Hier war ich mir nicht ganz sicher, ob das der richtige Ort für diesen Test ist.

2024-07-24 07:37 UTC, wosc requested changes

2024-07-24 07:37 UTC, wosc commented on core/src/zeit/content/image/tests/test_transform.py
> +    def test_encoder_parameters_configuration_loads_correctly(self):
So wie der Test jetzt aufgeschrieben ist, würde er per Konvention nach `test_interfaces.py` gehören. Ich würde aber sagen, lass uns lieber in `test_transform.py` behalten, und dafür mit etwas größerem Scope aufschreiben, also indem wir entweder ein echtes Transform aufrufen, und prüfen, dass die Parameter sich auswirken (Pseudocode siehe unten), oder notfalls das `image.save` mocken und prüfen, dass die Parameter übergeben werden.

```python
def test_encoder_parameters_are_configurable(self):
    group = create_image_group(...)
    transform = ITransform(image)
    default = transform.image.copy().thumbnail(200, 200).save()
    configured = transform.thumbnail(200, 200)
    self.assertLess(configured.size, default.size)  # assumes the configured quality is less than the default
```

2024-07-24 07:57 UTC, Sinnaj94 commented on core/src/zeit/content/image/tests/test_transform.py
> +    def test_encoder_parameters_configuration_loads_correctly(self):
Ja das hört sich nice an. Das mach ich gleich mal.

2024-07-24 14:40 UTC, Sinnaj94 commented on core/src/zeit/content/image/tests/test_transform.py
> +    def test_encoder_parameters_configuration_loads_correctly(self):
Ich habe es jetzt überarbeitet, bin mir aber nicht sicher, ob es so passt. Auf die Weise aus deinem Code-Snippet hab ich's leider nicht ganz verstanden, vielleich können wir morgen noch einmal gemainsam rüberschauen :D

2024-07-25 08:24 UTC, wosc commented
Habens im Pairing nochmal neu aufgebaut: #816

2024-07-25 08:24 UTC, closed without merging