qWcm 268 less exports to ir
ZeitOnline/vivi pull request #832
Opened 2024-08-19 16:05 UTC by louika

### Checklist

- [ ] Documentation
- [x] Changelog
- [x] Tests
- [ ] ~~Translations~~

### gif
![flop](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGt5cnBpNWpuejVzZG55eHM2a2JkOGdrOHlveXVtbjI0dWFvazBrcSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o6fJbwYFe3SmVVQ4M/giphy.gif)

2024-08-21 11:08 UTC, stollero requested changes
Gefällt mir. Schön übersichtlich und funktional. `checkout` Module ist wahrscheinlich auch nicht ganz der richtige Ort für die Funktionalität aber das akzeptieren wir, da mir auf Anhieb auch kein besserer einfällt 😁 .

Ich habe eigentlich nur eine Bitte, nämlich Dokumentation. Ich habe nichts zu dieser Konfiguration bzw. Webhooks gefunden. Wir sollten die Gelegenheit nutzen um das zu machen.

2024-08-21 11:08 UTC, stollero commented on core/src/zeit/cms/checkout/webhook.py
> +            notify_webhook.apply_async((context.uniqueId, hook.id), countdown=5)
Ein Vorschlag, aber kein Muss. Vielleicht können wir die Übersichtlichkeit etwas verbessern, wenn wir ein mapping definieren und das dann nutzen.

```
HOOK_EVENTS = {
   'AfterPublish': ['all_events', 'published'],
   ...
}

def create_webhook_job(context, event_type):
    for hook in HOOKS:
        if hook.id in HOOK_EVENTS[event_type]:
            log.info(
                '%s: Creating async webhook job for %s',
                event_type,
                context.uniqueId,
            )
            notify_webhook.apply_async((context.uniqueId, hook.id), countdown=5)

@grok.subscribe(zeit.cms.interfaces.ICMSContent, zeit.cms.checkout.interfaces.IAfterCheckinEvent)
def notify_after_checkin(context, event):
    create_webhook_job(context, 'AfterCheckin')

@grok.subscribe(zeit.cms.interfaces.ICMSContent, zeit.cms.workflow.interfaces.IPublishedEvent)
def notify_after_publish(context, event):
    create_webhook_job(context, 'AfterPublish')

@grok.subscribe(zope.lifecycleevent.IObjectAddedEvent)
def notify_after_add(event):
    context = event.object
    if not zeit.cms.interfaces.ICMSContent.providedBy(context):
        return
    if zeit.cms.repository.interfaces.IRepository.providedBy(context):
        return
    if zeit.cms.workingcopy.interfaces.IWorkingcopy.providedBy(event.newParent):
        return
    create_webhook_job(context, 'AfterAdd')
```

2024-08-21 11:08 UTC, stollero commented on core/src/zeit/cms/checkout/webhook.py
> +        if hook.id in ['default', 'checkin']:
Ich überlege ob wir für `default` lieber eine sprechendere Variante finden. `any_events`, `all_events`, `all` 🤔

2024-08-21 11:08 UTC, stollero commented on core/src/zeit/cms/checkout/webhook.py
> +    hook = HOOKS.factory.find(id)
Nur eine weitere Idee. Können wir nicht eigentlich direkt den hook übergeben? Dann müssten wir ihn nicht noch einmal "finden".

2024-08-21 11:08 UTC, stollero commented on core/src/zeit/cms/content/sources.py
> +        self.counter = counter
Da brauchen wir Dokumentation über die Bedeutung dieser Variable und dessen Werte 🤓 .

2024-08-21 13:54 UTC, louika commented on core/src/zeit/cms/checkout/tests/test_webhook.py
> +class WebhookEventTest(FunctionalTestCase):
jetzt in `add`, `checkin`, und `publish` aufgeteilt

2024-08-21 13:55 UTC, louika commented on core/src/zeit/cms/checkout/webhook.py
> +        if hook.id in ['default', 'checkin']:
`default` ist nun komplett rausgeflogen

2024-08-21 13:55 UTC, louika commented on core/src/zeit/cms/content/sources.py
> +        self.counter = counter
🫡

2024-08-21 15:51 UTC, louika commented
Oh sagmal, sollte man bei einem `IBeforeCheckinEvent`, das ja seit neuestem weiß, ob es sich um einen Veröffentlichungsvorgang handelt oder nicht, einfach `return` sagen, und das Benachrichtigen des Contenthubs einfach dem `IPublishedEvent` überlassen?

2024-08-21 16:25 UTC, louika commented
soo hier ist [Doku](https://github.com/ZeitOnline/vivi-deployment/pull/1120)

2024-08-22 07:24 UTC, stollero commented on core/src/zeit/cms/checkout/webhook.py
> +        return
Gut gesehen 😄 . Die Log-Meldung können wir uns sicherlich sparen. Wir wollen doch zeitnah den Checkout-Checkin aus dem Publish Vorgang entfernen und Kibana ist doch jetzt schon so überfordert mit den ganzen Logs 😁

2024-08-22 07:25 UTC, stollero approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjluYmQ3bHN5d2VyMnJtMmo4MnJtejkxZmk0dTJsc21hNmVyYXc1cyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/kBZBlLVlfECvOQAVno/giphy.gif)

2024-08-22 09:20 UTC, merged