WCM-307: add teaser title, teaser text and background color to volume
ZeitOnline/vivi pull request #846
Opened 2024-09-04 09:59 UTC by Sinnaj94

In diesem Pull-Request wird das Ausgaben-Objekt durch folgende, optionale Attribute erweitert:

- Teaser-Title
- Teaser-Text
- Hintergrundfarbe

Dabei wird die Hintergrundfarbe validiert.

Beschreibung des Sachverhaltes ist auch in Ticket [WCM-308](https://zeit-online.atlassian.net/browse/WCM-308) beschrieben.

### Checklist

- [ ] Documentation
- [ ] Changelog
- [ ] Tests
- [ ] Translations

### gif
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3oxZHNvencyeXQxNmZnOW11OWpwdzc4amFybjh6Nm9jZmFuZWhweCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xUPGcAMxlZ1F7cyqNG/giphy-downsized.gif)

2024-09-04 12:35 UTC, wosc requested changes

2024-09-04 12:35 UTC, wosc commented on core/src/zeit/content/volume/volume.py
> +        ('date_digital_published', 'year', 'volume', 'title', 'teaser', 'background_color'),
Hm, die neuen Felder `title` und `teaser` sind (genau wie `year/volume/product`) Felder aus `ICommonMetadata`. Ich denke, es ist immernoch sinnvoll, das _nicht_ zu beerben, aber wir sollten die gleichen Namen (und Property-Namen) verwenden. `title` ist okay (siehe _dazu_ auch ZO-788, seufz), aber `teaser` sollte wohl `teaserText` heißen.

2024-09-04 12:35 UTC, wosc commented on core/src/zeit/content/volume/tests/test_volume.py
> +        self.assertEqual('Obamas Rede', volume.title)
In solchen Fällen schreib ich (nur) nen Browser-Test, der einmal das Form aufruft, den Kram reinschreibt, und schaut dass er gespeichert wird -- denn man will/muss ja eh schauen, dass man es im Formular ordentlich verdrahtet hat, und dann kriegt man den Test, dass das Objekt selber es versteht, gleich gratis mitgeliefert

2024-09-04 14:40 UTC, Sinnaj94 commented on core/src/zeit/content/volume/volume.py
> +        ('date_digital_published', 'year', 'volume', 'title', 'teaser', 'background_color'),
Das Problem ist, es gibt bereits [teaserText](https://github.com/ZeitOnline/vivi/blob/a940a8aad168b9e17153e876c6c18072316aa1e2/core/src/zeit/content/volume/interfaces.py#L40). Das wird in Vivi dann *Ausgaben-Hinweis* genannt... Soll ich die Variable vielleicht dann auch umbenennen oder ist Ausgaben-Hinweis in dem Fall das gleiche wie `teaser`, und wir können eines von beiden rausschmeißen?

2024-09-04 15:42 UTC, greengiraffe commented on core/src/zeit/content/volume/volume.py
> +        ('date_digital_published', 'year', 'volume', 'title', 'teaser', 'background_color'),
Ich finde title/teaser nicht _falsch_, aber auch sehr überladen und hätte diese Alternativvorschläge:

- `lead_title` und `lead_teaser`

Oder auch:
- `headline` ("Schlagzeile") und `extract` (so ist der Aufmachertext im Figma benannt)

2024-09-05 07:30 UTC, wosc commented on core/src/zeit/content/volume/volume.py
> +        ('date_digital_published', 'year', 'volume', 'title', 'teaser', 'background_color'),
Right. Bei dem bisherigen Feld geht es um `Dieser Artikel stammt aus der ZEIT Nr. {name}/{year}. Hier können Sie die gesamte Ausgabe lesen.` ([Beispiel](https://friedbert-preview.zeit.de/2024/34/reitsport-olympia-pferde-leistungssport-paris)). Das hat aus damaliger Sicht schon gewissen Sinn gehabt, _das_ `teaserText` zu nennen. Aber im Zshg mit dem aktuellen Ticket muss man ja schon sagen, dass _das_ die eigentliche Berechtigung hat, `teaserText` zu heißen (weil es auf Teaser-Modulen in CPs verwendet werden soll).

Insofern würde ich tatsächlich sagen, wir sollten das bisherige Feld umbenennen (und die 337 Bestandsinhalte migrieren, siehe `select concat(parent_path, '/', name), unsorted->'document'->'teaserText' from properties where type='volume' and unsorted @@ 'exists(\$.document.teaserText)'`), und dann `teaserText` für das jetzt neue Feld verwenden.

2024-09-05 08:03 UTC, wosc commented on core/src/zeit/content/volume/volume.py
> +        ('date_digital_published', 'year', 'volume', 'title', 'teaser', 'background_color'),
Sonja prüft, ob wir das bisherige Feld am Volume-Objekt überhaupt brauchen, oder ob man das da anhand des Products generieren kann (und nur bei Bedarf am Artikelmodul überschreiben).

2024-09-05 13:14 UTC, greengiraffe commented on core/src/zeit/content/volume/volume.py
> +        ('date_digital_published', 'year', 'volume', 'title', 'teaser', 'background_color'),
> Insofern würde ich tatsächlich sagen, wir sollten das bisherige Feld umbenennen

In zeit.web muss dann diese Zeile im Template angepasst werden, damit die Volume-Teaser nicht plötzlich anderen Text ausspielen: https://github.com/ZeitOnline/zeit.web/blob/main/src/zeit/web/core/templates/inc/asset/volume.html#L30

2024-09-05 13:21 UTC, greengiraffe commented on core/src/zeit/content/volume/volume.py
> +        ('date_digital_published', 'year', 'volume', 'title', 'teaser', 'background_color'),
> (weil es auf Teaser-Modulen in CPs verwendet werden soll :)

Das _"das"_ hat mich verwirrt. Du sprichst hier vom aktuellen `teaserText`, richtig ? In dem Kontext ergibt der Name ja wirklich noch Sinn und verhält sich analog zu anderen Teasern, die das gleiche Feld haben. Würde für mich doch eher _gegen_ eine Umbenennung sprechen, oder? Die Ausgabenseite macht ja eher die Extrawurst.

2024-09-05 13:32 UTC, wosc commented on core/src/zeit/content/volume/volume.py
> +        ('date_digital_published', 'year', 'volume', 'title', 'teaser', 'background_color'),
Aus meiner Sicht ist das bisherige Feld ("Hier können Sie die gesamte Ausgabe lesen") nicht wirklich ein `ICommonMetadata.teaserText` in dem Sinn, wie wir das sonst überall verwenden. Das war damals nur begrifflich am ähnlichsten, deshalb haben wir den Namen verwendet, anstatt uns für Ausgabenobjekte einen besonderen Namen auszudenken. Das neue Feld hingegen finde ich ist mit `teaserText` aber inhaltlich exakt treffend beschrieben.

2024-09-17 06:03 UTC, stollero approved these changes
Sieht soweit voll in Ordnung aus, bis auf das Layout und mein fehlender Colorpicker. Oh je das ist echt eine Sache für sich. Aber das verfolgen wir erst einmal nicht weiter. Wenn wir mal wieder am Volume sind 👍 

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExYnhmeXVna2kwdzhpNjF1ZjkxbmNkbmN0eXg5aDY5bHB5MnZocjY5diZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/tIeCLkB8geYtW/giphy.gif)

2024-09-17 06:17 UTC, merged