Wcm 285 3
ZeitOnline/vivi pull request #857
Opened 2024-09-24 05:56 UTC by stollero

### Checklist

- [ ] Documentation
- [ ] Changelog
- [ ] Tests
- [ ] Translations

### gif
![]()

2024-09-24 13:48 UTC, stollero commented on core/src/zeit/connector/models.py
> +            if isinstance(v, datetime):
Wir können in `unsorted` natürlich nur `JSON serializable objects` schreiben. `datetime` bspw. funktioniert nicht. Heißt schreibend in beide, bis alle Daten auch innerhalb der neuen Felder zu finden sind und dann können wir hier die `properties` überspringen, welche bereits in eigene Spalten geschrieben worden sind.

Ich überlege, welche sinnvolle Lösungsmöglichkeiten es gibt (unabhängig von dem Ansatz, den ich hier ausgebaut habe).

2024-09-24 14:27 UTC, wosc requested changes

2024-09-24 14:27 UTC, wosc commented on core/src/zeit/connector/models.py
> +            if isinstance(v, datetime):
Ich glaube, die Lage ist sogar noch etwas anders: Im `unsorted` stehen bisher nur Strings drin, weil wir die Werte 1:1 aus dem DAV dorthin migriert haben, und dort waren nur Strings möglich. Und die `IDAVPropertyConverter` gehen auch davon aus, dass da nur Strings drinstehen. Wir fangen jetzt zwar mit den "MetadataColumns" an, da ausnahmen zuzulassen, aber da geht es ja nur um Felder, die _nicht_ in `unsorted` stehen.

Der langen Rede kurzer Sinn: Wenn in `IResource.properties` ein non-String Wert drinsteht, der weder als internal deklariert noch in seine eigene Spalte umgezogen ist, so ist das ein Programmierfehler. Den sollten wir denke ich also definitiv nicht verschlucken (`continue`) -- ich würde aber sagen, dazu tun wir hier (nach wie vor) einfach gar nichts, sondern das kann dann gern "weiter hinten" als "not json serializable" knallen.

2024-09-24 14:27 UTC, wosc commented on core/src/zeit/connector/converter.py
> -import datetime
Das war leider durchaus komplette Absicht, dass dieser "Converter"-Code in `filesystem.py` lebte, denn nur genau dafür war und ist er gedacht (und soll perspektivisch dann, zusammen mit dem FS-Connector, gelöscht werden). Könntest du ihn bitte dorthin zurückschieben?

2024-09-25 09:19 UTC, wosc requested changes
Danke für den Rückbau! Für die Channels tut das jetzt leider noch nicht das gewünschte. (Falls Du lieber erstmal nur den Rückbau machen willst, und die richtige Channels-Implementierung dann in einem separaten PR, könnten wir das meinetwegen auch tun.)

2024-09-25 09:19 UTC, wosc commented on core/src/zeit/connector/filesystem.py
> +class DictConverter(grok.Adapter):
Die Aufgabe dieser Converter ist, mal platt gesagt, vorhandene `.meta` Files in den zeit.web Testdaten zu parsen, um die Datentypen draus zu machen, die sowieso rauskämen, wenn es SQL wäre. Dh konkret gesprochen brauchen wir hier einen, der für Channels aus `"chan1;chan2 sub1;chan2 sub2"` dann `[['chan1', None], ['chan2', 'sub1'], ['chan2', 'sub2']]` macht, und umgekehrt (dafür könnte man vmtl den `CollectionTextLineProperty/ChannelProperty` Code aufrufen, um die Implementierung nicht duplizieren zu müssen).

2024-09-25 09:19 UTC, wosc commented on core/src/zeit/connector/filesystem.py
> +class DictConverter(grok.Adapter):
Die nächste Frage ist dann, wie man den passenden `Converter` findet, weil es jetzt ja losgeht, dass wir SQL-seitig sagen "jo klar, ist halt json", aber je nach dem konkreten Feld in dem json dann Dict oder Liste oder sonstwas drinsteht. Das heißt aber, dass es nicht mehr ausreicht, den `IConverter` rein anhand des Column-Typs nachzuschlagen. Insofern würde ich vorschlagen, dass wird den "Haupt-Adapter" (derzeit `converter_from_column_type`) umbenennen und erweitern, und im ersten Schritt schauen, ob es einen named Adapter für genau diesen `namespace/name` gibt (darauf könnte man dann `document/channels` hängen), und erst im zweiten Schritt anhand des Typs schauen.

2024-09-25 12:13 UTC, merged