WCM-285: custom typ for jsonb to work with channels tuple type
ZeitOnline/vivi pull request #866
Opened 2024-09-30 14:06 UTC by stollero

### Checklist

- [ ] Documentation
- [x] Changelog
- [x] Tests
- [ ] Translations

### gif
![]()

2024-10-02 06:55 UTC, wosc requested changes

2024-10-02 06:55 UTC, wosc commented on core/src/zeit/connector/models.py
> +        return value
Also, das scheint zwar zu funktionieren, wenn man hier `list` rausgibt (was mich ehrlich gesagt wundert, ich hätte eigentlich erwartet, dass `zope.schema.Tuple` sich darüber beschwert), aber ich denke, zur Klarheit sollten wir besser "`tuple` rein / `tuple` raus" einheitlich umwandeln, [ungefähr so](https://github.com/ZeitOnline/vivi/commit/f585db4356687caf5696f2a8a86839a46b8c9d20) vermutlich?

2024-10-02 06:55 UTC, wosc commented on core/src/zeit/connector/tests/test_mock.py
> +class CollectionPropertyTest(zeit.connector.testing.MockTest):
Da deckst du in der Tat eine Testlücke auf, das hatten wir in WCM-271 vergessen, die filesystem-Converter abzudecken. Habe WCM-436 dafür angelegt.

2024-10-02 06:55 UTC, wosc commented on core/src/zeit/connector/tests/test_postgresql.py
>          properties = {('print-publish', DOCUMENT_SCHEMA_NS): self.TIMESTAMP}
Hat mit diesem PR nichts zu tun, aber ich seh es grade zum ersten Mal: ich glaube, dieser ganze `WorkflowColumnsTest` dupliziert eigentlich nur, was der `ContractProperties` Test schon prüft, kann das sein? Insofern könnte der evtl entfallen?

2024-10-02 07:05 UTC, stollero commented on core/src/zeit/connector/models.py
> +        return value
zope.schema folgt wohl dem Robustness principle

> be conservative in what you do, be liberal in what you accept from others

Wobei ich der Ansicht bin, das ich lieber ganz genau wissen möchte was ich von den anderen erhalte 😄. Ganz früher waren sogar überall Assertions im Code um die Argumente zu prüfen 🫢 

Danke für den Vorschlag, `cherry-pick f585db4356687caf5696f2a8a86839a46b8c9d20`

2024-10-02 07:07 UTC, stollero commented on core/src/zeit/connector/tests/test_postgresql.py
>          properties = {('print-publish', DOCUMENT_SCHEMA_NS): self.TIMESTAMP}
Da hast du Recht, Contract macht dasselbe

2024-10-02 07:08 UTC, stollero commented on core/src/zeit/connector/tests/test_mock.py
> +class CollectionPropertyTest(zeit.connector.testing.MockTest):
Tests für Dinge, welche wir gar nicht haben wollen und in Zukunft raus werfen 😁

2024-10-07 10:56 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmJkdzJrendyM3BkMHRvNW0zdmdlZDdleWliMmlxYW13bHUwMTZyeSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gz5LShlg2CG6Q/giphy.gif)

2024-10-07 10:56 UTC, wosc commented on core/src/zeit/connector/types.py
> +"""Module for custom sql alchemy types
💡 oh das ist ne gute Idee.

2024-10-07 10:56 UTC, merged