Wcm 401
ZeitOnline/vivi pull request #872
Opened 2024-10-04 08:30 UTC by Sinnaj94

Neuer Audio-Objekt-Typ `Intro` hinzugefügt und `teaser`-Attribute von `ICommonMetadata` in der Form genutzt.

Ticket: [WCM-401](https://zeit-online.atlassian.net/browse/WCM-401)

[WCM-401]: https://zeit-online.atlassian.net/browse/WCM-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-10-04 10:12 UTC, Sinnaj94 commented on core/src/zeit/content/audio/tests/test_audio.py
> +        assert isinstance(images_adapter, zeit.content.image.imagereference.ImagesAdapter)
Ich hab mich gefragt, ob man hier das Bild direkt testen sollte. Also xml vom Audio:
```
[...]
<head><image base-id="xml.zeit.de/abc"/></head>
[...]
assert images_adapter.image.uniqueId="xml.zeit.de/abc/"
```
Oder genügt das so?

2024-10-04 10:14 UTC, Sinnaj94 commented on core/src/zeit/content/audio/audio.py
> +        return zeit.content.image.imagereference.ImagesAdapter(context)
Hier sollten wir entscheiden, ob einfach alle `audio_type`s bis auf `podcast` den `ImagesAdapter` bekommen oder ausschließlich `audio_type=='manual'`.

2024-10-08 11:08 UTC, Sinnaj94 commented on core/src/zeit/content/audio/audio.py
> +    return None
Hier gibt's noch ein Problem: `TypeError: ('Could not adapt', <zeit.content.audio.audio.Audio (unknown)>, <InterfaceClass zeit.content.image.interfaces.IImages>)
`

2024-10-08 13:47 UTC, Sinnaj94 commented on core/src/zeit/content/audio/audio.py
> +    return None
Gefixt..

2024-10-09 06:38 UTC, stollero commented
Wieso fehlt denn die Checkliste in deinem PR 🤔 ?

- Documentation <-
- Changelog <-
- Tests
- Translations <-

2024-10-09 07:00 UTC, wosc requested changes

2024-10-09 07:48 UTC, Sinnaj94 commented on core/src/zeit/content/audio/interfaces.py
> +        'standalone': _('Standalone Audio'),
Bei einer Slack Diskussion heute morgen kam raus, weder noch. `custom` wird es sein.

2024-10-09 09:47 UTC, Sinnaj94 commented on core/src/zeit/content/audio/browser/tests/test_form.py
> +        ).value = 'http://xml.zeit.de/bilder/2007/01/aktuell/teaser_artikel/somalia-291206-410.jpg'
Hab es jetzt geschafft endlich 😁 Zur Dokumentation, wo ich Probleme hatte:

Erstmal fragte ich Wolfgang:
> JJ: Hi Wolfgang, ich bekomme irgendwie einen Error bei create_image_group:
(Pdb) group = zeit.content.image.testing.create_image_group()
*** TypeError: ('Could not adapt', <zeit.content.image.imagegroup.ImageGroup http://xml.zeit.de/image-group>, <InterfaceClass zeit.connector.interfaces.IResource>)
Hast du eine Idee woran es liegen könnte?
WS: yo, du musst z.c.image in der ftesting.zcml von z.c.audio anziehen

Ich habe in der `audio/ftesting.zcml` -->  `<include package="zeit.content.image" file="ftesting.zcml" />` hinzugefügt.  Dann bekam ich:
```
    raise ConfigurationExecutionError(info, sys.exc_info()[1])
zope.configuration.config.ConfigurationExecutionError: File "/Users/jannis.jahr/Repos/vivi-deployment/work/source/vivi/core/src/zeit/content/image/configure.zcml", line 222.2-222.47
    <utility factory=".mdb.from_product_config"/>
    KeyError: 'mdb-api-url'
```
Habe auch versucht, die `mdb-api-url` etc. im Config Layer von audio/testing.py einzutragen, selbes Ergebnis. Dann hatte ich gesehen, es wurde bei `CONFIG_LAYER.bases` zum Beispiel beim Author `zeit.find.testing.CONFIG_LAYER`, statt `zeit.cms.testing.CONFIG_LAYER,`  eingetragen - hier bekam ich wiederum einen Circular Import Error

Habe dann die Lösung gefunden:

 https://github.com/ZeitOnline/vivi/blob/1e13d1f96f309214d8b3d76fc11c40944381bbae/core/src/zeit/content/audio/testing.py#L19

2024-10-09 14:47 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnlpdnR0MzZsNTUzZ2RjZWZtZ2Jibnh3dGdvaHdvcmpwM3U2aDR2OSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Ph624wsTrPk3z6n2tq/giphy.gif)

2024-10-09 14:59 UTC, merged