WCM-456: Write toggle must not break checkin
ZeitOnline/vivi pull request #889
Opened 2024-10-16 14:40 UTC by louika

Die API Änderung des DAVPropertyConverters ist das Problem, dass sich durch das Zurückdrehen des `write_metadata_columns` Toggles gezeigt hat. 

Der Toggle hat dafür gesorgt, dass nicht nur die Daten in die neuen Spalten geschrieben werden, sondern auch, dass in den Properties der Resource keine Strings, sondern Python Objekte drin stehen. Beispielsweise `PropertyKey(name='year', namespace='http://namespaces.zeit.de/CMS/document'): 2008` statt `PropertyKey(name='year', namespace='http://namespaces.zeit.de/CMS/document'): '2008'`. Oder `PropertyKey(name='date_created', namespace='http://namespaces.zeit.de/CMS/document'): DateTime(2024, 10, 16, 15, 5, 32, 67016, tzinfo=Timezone('Europe/Berlin'))` statt `PropertyKey(name='date_created', namespace='http://namespaces.zeit.de/CMS/document'): '2024-10-16T15:56:36.967542+02:00'`.

Damit kann aber weder die `unsorted` Spalte, noch der `IDAVPropertyConverter` umgehen.
siehe
```
  File "/Users/louisa.huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/cms/content/dav.py", line 85, in __fetch__
    value = converter.fromProperty(dav_value)
   - __traceback_info__: (<zeit.content.article.article.Article http://xml.zeit.de/08e96b04-bcff-4c54-9a3e-39c32237ecdf.tmp>, <zope.schema._field.Tuple object at 0x13ab3f350 zeit.cms.content.interfaces.ICommonMetadata.channels>, 'channels', (('Kultur', None),))
  File "/Users/louisa.huelsen/Projects/vivi-deployment/work/source/vivi/core/src/zeit/cms/content/dav.py", line 430, in fromProperty
    found = value.find(';', start)
  ``` 

Deshalb darf sich die API des `IDAVPropertyConverter`s erst ändern, wenn sich sowohl read, als auch write einig über den Datentyp sind, mit dem sie hantieren. 

Jetzt ist der Write-Toggle wirklich nur darauf beschränkt im Connector in die neuen Spalten zu schreiben. Das schien mir sinnvoller als ein Pflaster in `from_webdav` in Richtung:
```
if not isinstance(v, str):
    # Support unsetting write_metadata_columns toggle. Must write json serializable
    # values to unsorted
    column = self.column_by_name(k, ns)
    if column is not None:
        converter = zeit.connector.interfaces.IConverter(column)
        unsorted[ns.replace(self.NS, '', 1)][k] = converter.serialize(v)
else:
    unsorted[ns.replace(self.NS, '', 1)][k] = v
```
### Checklist

- [ ] ~~Documentation~~
- [x] Changelog
- [x] Tests
- [ ] ~~Translations~~

### gif
![monday](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcTV5em9xZTd5d3JvbWZobDVqY3R1NDRybHN5NXE3aDcxMmo0NW9pZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o6fJbwYFe3SmVVQ4M/giphy.gif)

2024-10-17 06:52 UTC, wosc reviewed
Ich stimme Dir zu, im Connector-Code Typkonvertierungs-Geschichten zu machen, ohne dass irgendein Toggle aktiv ist, klingt erstmal eher verwirrend, und wollen wir _vmtl_ lieber vermeiden.

Wenn ich das richtig verstehe, funktioniert der Ansatz hier deshalb, weil 3912aba bei aktivem Toggle `write` die Properties "notfalls" sowieso deserialisiert. Und _dann_  frage ich mich (auch wenn man zb noch 3309064 mit anschaut), ob wir nicht sogar noch etwas weiter gehen sollten, bzw. umgekehrt, ob wir grade zu viel auf einmal wollen. 

Also ja, perspektivisch wollen wir, dass die `DAVPropertyConverter` so weit möglich rausfliegen, weil wir uns auf sql(alchemy) stützen können&wollen. Aber wäre es für die Übergangszeit (also während wir noch hin und her togglen) nicht evtl doch einfacher, als API stabil zu halten, `IWebDAVProperties` enthält nur Strings als Werte? Also ja, das wäre etwas ineffizient, weil dann die DAVProperties alles immer erst serialisieren, und der Connector es dann wieder deserialisiert, und umgekehrt. Damit könnten wir aber vmtl. leben, soo teuer ist das denke ich nicht. Aber wenn wir jetzt eh schon halb da sind, würde es nicht das Verständnis erheblich erleichtern, es durchzuziehen?

2024-10-22 07:00 UTC, wosc requested changes
Die Richtung stimmt zwar, der Ansatz ist aber leider noch nicht vollständig umgesetzt.

2024-10-22 07:00 UTC, wosc commented on core/src/zeit/connector/tests/test_contract.py
>          example_date = datetime(2010, 1, 1, 0, 0, tzinfo=pytz.UTC)
Wenn dieser PR dann fertig ist, muss man die storage-api entsprechend anpassen, siehe auch WCM-446

2024-10-22 07:04 UTC, wosc commented on core/src/zeit/cms/content/dav.py
>          self.has_sql_type = ConnectorModel.column_by_name(*propertykey) is not None
Das `has_sql_type` fliegt dann auch mit raus.

2024-10-22 12:11 UTC, louika commented
entschuldigung? was ist denn nun kaputt?

2024-10-22 12:26 UTC, louika commented
jetzt ist der `PropertiesColumnTest` lokal auch manchmal kaputt, je nachdem, ob ich ihn im Set oder einzeln laufen lasse 😬

2024-10-22 13:30 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbnYwZDE5cDllOGM3aDdrczExdWU3eTRiNm5xemZreWFjZXV1czA4dyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/yaUG0KDAcIcWA/giphy.gif)

2024-10-22 13:30 UTC, merged