ZO-6156: Add dropdown selection for liveblog teaser timeline
ZeitOnline/vivi pull request #897
Opened 2024-10-30 15:33 UTC by madeyemocki

### Checklist

- [ ] Documentation
- [ ] Changelog
- [ ] Tests
- [ ] Translations

### gif
![]()

2024-11-04 09:08 UTC, madeyemocki commented
@Sinnaj94 kannst du da vlt nochmal drauf schauen? :)

2024-11-08 10:45 UTC, madeyemocki commented
danke @Sinnaj94!
Kann ich dann mergen? :)

2024-11-08 11:09 UTC, Sinnaj94 commented
Noch nicht :D Jetzt hab ich die Tests nochmal gemacht, dann können wir mergen denke ich :)

2024-11-11 08:39 UTC, wosc requested changes

2024-11-11 08:39 UTC, wosc commented on core/src/zeit/content/article/edit/interfaces.py
> +        default='disabled',
Vorher war der Default "ja bitte anzeigen", wird das absichtlich auf "nichts anzeigen" geändert?

2024-11-11 08:39 UTC, wosc commented on core/src/zeit/content/article/edit/interfaces.py
> +        default='disabled',
Wenn es keinen dringenden Grund gibt, bitte das übliche Vorgehen verwenden, und das Feld auf `required=False` setzen und den daraus resultierenden Standard-Default `None` für "nichts anzeigen" verwenden, anstatt extra einen Wert `disabled` dafür einzuführen.

2024-11-11 08:39 UTC, wosc commented on core/src/zeit/content/article/edit/liveblog.py
> -        'show-timeline-in-teaser',
Denkt dran, dass man den Bestandscontent dann nachziehen muss. Liveblog-Artikel sollten ja relativ wenige sein, dh das kann man vmtl problemlos manuell tun.

2024-11-11 08:42 UTC, Sinnaj94 commented on core/src/zeit/content/article/edit/interfaces.py
> +        default='disabled',
Tatsächlich ja: https://zeit-online.atlassian.net/browse/ZO-6156 🤔

2024-11-11 08:54 UTC, Sinnaj94 commented on core/src/zeit/content/article/edit/liveblog.py
> -        'show-timeline-in-teaser',
Ja, haben wir bedacht 😁

2024-11-12 07:14 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGpieGJtdjRiOWVxeThqc2EzZDd1cjg2ZDBxcTM5ZmEwZDdxcjc3bCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ONuQzM11fjvoY/giphy.gif)

2024-11-12 07:14 UTC, merged