WCM-527: add content query fields print-volume, -year and -ressort
ZeitOnline/vivi pull request #910
Opened 2024-11-14 11:02 UTC by stollero

### Checklist

- [ ] Documentation
- [x] Changelog
- [x] Tests
- [ ] Translations

### gif
![]()

2024-11-15 07:56 UTC, wosc requested changes
An sich super, ich habe eine Konsistenzbitte.

2024-11-15 07:56 UTC, wosc commented on core/src/zeit/contentquery/interfaces.py
> +        'printRessort': _('query-type-printRessort'),
Der Einheitlichkeit halber sollten wir hier `snake_case` verwenden. Das `ICommonMetadata.printRessort` ist nur `camelCase` als historischer Unfall -- den wir dann jetzt halt mal korrigieren sollten, schließlich haben wir vivi+zeit.web ja komplett in der Hand.

2024-11-15 07:56 UTC, wosc commented on core/src/zeit/content/cp/tests/test_automatic.py
> +            ('printRessort', 'eq', 'DIE ZEIT'),
Warum funktioniert das überhaupt? :) Das ist kein gültiger Wert [in der Fixture-Config](https://github.com/ZeitOnline/vivi/blob/main/core/src/zeit/cms/content/print-ressorts.xml).

2024-11-15 09:52 UTC, stollero commented on core/src/zeit/contentquery/interfaces.py
> +    print_ressort = zope.schema.Choice(
In Rücksprache mit Sonja wählen wir hier nun doch ein Textfeld um historische Daten zu unterstützen. Sonst würde die Dropdown Box automatisch auf den ersten Eintrag springen, wenn ein Wert unbekannt ist und eine Person was händisch an einer älteren Ausgabenseite macht (warum auch immer).

2024-11-15 10:51 UTC, stollero commented on core/src/zeit/contentquery/interfaces.py
> +        'printRessort': _('query-type-printRessort'),
Sehr guter Hinweis. Wenn wir mal dran sind :)

2024-11-18 07:51 UTC, wosc requested changes
Super, danke fürs gradeziehen des Namings. Mir ist dann noch siedenheiß ein inhaltlicher Punkt aufgefallen.

2024-11-18 07:51 UTC, wosc commented on core/src/zeit/contentquery/interfaces.py
> +        'page': _('query-sort-order-page'),
Das Feld muss für die Übergangszeit auch noch bei `zeit.contentquery.query.CustomContentQuery.ES_ORDER` entsprechend eingetragen werden.

2024-11-18 07:51 UTC, wosc commented on core/src/zeit/cms/content/metadata.py
> +    def printRessort(self):
Eigentlich sollten wir der Testabdeckung in zeit.web trauen können, dh wenn wir dort vivi hochziehen, müssten uns die Failures genau sagen, welchen Code wir alles anpassen müssen (ich hab geschummelt und schonmal gegreppt, wenn ichs richtig sehe, wird das Feld an exakt 1 Stelle verwendet). Insofern würde ich hier genau _kein_ bw-compat reintun, sondern zeit.web dann eben synchron aktualisieren.

2024-11-18 09:07 UTC, stollero commented on core/src/zeit/contentquery/interfaces.py
> +        'page': _('query-sort-order-page'),
Ja, sollten wir synchron halten falls wir am Baukasten dann doch etwas zurück drehen müssen 👍

2024-11-18 09:07 UTC, stollero commented on core/src/zeit/cms/content/metadata.py
> +    def printRessort(self):
Ist wieder entfernt

2024-11-18 09:16 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdzNvcHJ2d2luNWoxbzBvMGhmcDdpeTIycHdmc3ZsMzhjYWg2bmkwcyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cCbfB1iDFYAEuiVIzW/giphy.gif)

2024-11-18 09:22 UTC, merged