WCM-558: remove urbanairship push from vivi
ZeitOnline/vivi pull request #929
Opened 2024-11-26 15:27 UTC by stollero

(publisher is responsible for this)

### Checklist

- [ ] Documentation -> vivi-deployment!
- [x] Changelog
- [x] Tests
- [ ] Translations

### gif
![]()

2024-11-27 14:02 UTC, wosc requested changes

2024-11-27 14:03 UTC, wosc commented
Ich würde zusätzlich außerdem sehr für #930 plädieren. Wenn wir das schon als eigenen Service drin hängen haben, lass uns ganz klar sagen, dass wir den im bulk publish abklemmen, und uns nicht auf irgendwelche Monkeypatches verlassen.

2024-11-29 06:59 UTC, stollero commented on core/src/zeit/content/video/tests/test_browser.py
> -    def test_push_to_social_media_is_done_on_publish(self):
👍 Commits habe ich sauberer voneinander getrennt.

2024-11-29 07:06 UTC, stollero commented on core/src/zeit/push/workflow.py
> +            if config['type'] == 'mobile' and config.get('enabled'):
> Aber vielleicht ist das auch bisschen viel auf einmal

Ja, ich habe im Wahn alles nach push-aussehende entfernt und homepage halbwegs verdrängt. Änderungen nochmal zurück und Fokus auf airship und toggle 👁️

2024-11-29 14:06 UTC, wosc approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXY1OWNtZmF6M2d2ZHl0NTR1ZHJpZzF4ZnJiOXVsdWY1bjByNXN5cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BILk8Oiyby8Jq/giphy.gif)

2024-11-29 14:06 UTC, merged