ZO-6758: Resolve account name in Bluesky post url
ZeitOnline/vivi pull request #947
Opened 2024-12-09 14:44 UTC by adrian-zon

### Checklist

- [ ] Documentation
- [x] Changelog
- [x] Tests
- [ ] Translations

### gif
![chicago sky basketball - d3MKJmSzFWKGTizm](https://github.com/user-attachments/assets/7f95aca4-535c-40ce-bd4d-0c952770ecfd)

2024-12-10 12:07 UTC, stollero requested changes
Immer wieder schön dich auch mal hier im vivi Code zu sehen 😀

2024-12-10 12:07 UTC, stollero commented on core/src/zeit/content/article/edit/browser/edit.py
> +            if match[2].startswith('did:'):
Was ist ein `did`? :) `domain id`? 🤔

2024-12-10 12:07 UTC, stollero commented on core/src/zeit/content/article/edit/browser/edit.py
> +        api_result = None
Passend zum Thema Exception, wenn du diese erfasst brauchst du diese Variable auch nicht mehr 👯

2024-12-10 12:07 UTC, stollero commented on core/src/zeit/content/article/edit/browser/edit.py
> +            api_result = requests.get(f'{api_url}?handle={match[2]}', timeout=5)
`timeout` bitte konfigurierbar 🙇 , Danke schöööön

2024-12-10 12:07 UTC, stollero commented on core/src/zeit/content/article/edit/browser/edit.py
> +            api_result = requests.get(f'{api_url}?handle={match[2]}', timeout=5)
Kommt man da einfach so ein die API ohne Token und alles? 😲

2024-12-10 12:20 UTC, stollero commented on core/src/zeit/content/article/edit/browser/edit.py
> +            api_result = requests.get(f'{api_url}?handle={match[2]}', timeout=5)
Frage selbst beantwortet. Geht tatsächlich 😬

2024-12-12 10:30 UTC, adrian-zon commented on core/src/zeit/content/article/edit/browser/edit.py
> +        api_url = 'https://public.api.bsky.app/xrpc/com.atproto.identity.resolveHandle'
`xrpc` irritiert mich auch ^^

2024-12-12 10:33 UTC, adrian-zon commented on core/src/zeit/content/article/edit/browser/edit.py
> +                'api_result={api_result}): {e}'
Ups!

2024-12-12 10:34 UTC, adrian-zon commented on core/src/zeit/content/article/edit/browser/edit.py
> +            if match[2].startswith('did:'):
https://atproto.com/guides/glossary#did-decentralized-id:
> DIDs, or Decentralized IDentifiers, are universally-unique identifiers which represent [data repos](https://atproto.com/guides/glossary#data-repo). They are permanent and non-human-readable. DIDs are a [W3C specification](https://www.w3.org/TR/did-core/). The AT Protocol currently supports did:web and did:plc, two different DID methods.

2024-12-12 10:36 UTC, adrian-zon commented on core/src/zeit/content/article/edit/browser/edit.py
> +            api_result = requests.get(f'{api_url}?handle={match[2]}', timeout=5)
Auf welcher Ebene soll das konfigurierbar sein? Wirklich so Vivi-Config?

2024-12-13 10:03 UTC, stollero commented on core/src/zeit/content/article/edit/browser/edit.py
> +            api_result = requests.get(f'{api_url}?handle={match[2]}', timeout=5)
Genau, einmal in die vivi config :)

2024-12-16 06:37 UTC, adrian-zon commented on core/src/zeit/content/article/edit/browser/edit.py
> +            api_result = requests.get(f'{api_url}?handle={match[2]}', timeout=5)
So? Soll ich dann auch direkt in vivi-deployment einen Wert eintragen? :)

2024-12-16 07:06 UTC, stollero commented on core/src/zeit/content/article/edit/browser/edit.py
> +            api_result = requests.get(f'{api_url}?handle={match[2]}', timeout=5)
Merci.

Ne, ich würde aber den default-Wert möglichst niedrig auf 1s setzen. Ist ja ein zusätzlicher Request, das die UI blockiert.

2024-12-16 07:07 UTC, adrian-zon commented on core/src/zeit/content/article/edit/browser/edit.py
> +            api_result = requests.get(f'{api_url}?handle={match[2]}', timeout=5)
Erledigt

2024-12-16 07:39 UTC, stollero commented on core/src/zeit/content/article/edit/browser/edit.py
> +        if FEATURE_TOGGLES.find('resolve_bsky_embed_url') and data['url'].startswith(
Ach, data kann auch `None` sein 😬

2024-12-16 07:40 UTC, stollero commented
@adrian-zon Ist DSGVO und Consent auch bereits in der Klärung? Das müssen wir auch noch beachten bei neuen Social Embeds

> Sämtliche auf zeit.de verwendeten Embeds müssen auf (Tracking-)Code von Drittanbietern überprüft werden

2024-12-16 11:08 UTC, adrian-zon commented
> @adrian-zon Ist DSGVO und Consent auch bereits in der Klärung? Das müssen wir auch noch beachten bei neuen Social Embeds
> 
> > Sämtliche auf zeit.de verwendeten Embeds müssen auf (Tracking-)Code von Drittanbietern überprüft werden

Danke! Das wird in https://zeit-online.atlassian.net/browse/ZO-6814 behandelt.

2024-12-17 08:12 UTC, stollero approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmU1ZGoybmV1bHA4ODF3bXo1cXI2em52cXRlZ2NibzRkYjRyMDRvayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ailnj2AMt9e9i/giphy.gif)

2024-12-17 08:28 UTC, merged